* 引言
你认为基督徒是什么样的人？常见的回答就是：基督徒很好，做好事，心地良善，道德高尚，乐于助人。最开始听到这种回答的时候，很开心，因为把我算到道德高尚的那一类人中。等我更多地认识自己，认识神后，再听到这种回答，打心底出来的滋味很复杂。惭愧的是因为我觉得自己不是那种人，鼓舞的是那些生命成熟的基督徒在世人面前为主做了美好的见证，欣慰神的眼光跟世人的眼光不同，不然我就不配做基督徒，跟基督无份了。五年前坐在我旁边的一个同事，虽然不信主，我看他比我心地良善多了，更乐于助人。同事有需要，他总是主动伸出双手帮助别人，同事要搬家的时候，他主动提出来帮忙他们搬家。男女同事一起活动的时候，他总是表现出一副女士优先的姿态。上下楼梯的时候，他彬彬有礼地主动礼让。我相信很少有基督徒能够像他那样有爱心。想起来他比我更像基督徒。我们出生在礼仪之邦，但周围每天发生的事情都在嘲讽这个称号，地铁上男女对骂的现象见怪不怪，但从他身上还能看出礼仪之邦的残余影子。他身上确实有值得我学习的地方。但是我知道我是真正的基督徒，虽然生命中没有像他那样散发出爱的芬芳，也比不上他的行为举止。但我知道我对基督是有信心的，基督是我的救主。基督拯救我们，是因为我们有信心，而不是因为我们比其他人高尚。 

* 加拉太人的归主经历
** 活画的耶稣并祂钉十字架
   我们信的是什么？就是耶稣基督钉十字架。这个是信仰的中心，相信耶稣基督钉十架才是基督徒的开始。我们在跟人传福音的时候，一般先讲罪，然后讲耶稣基督十字架上的拯救。有一批人不认为自己有罪，承认自己有罪的一批人中又有一批人不相信耶稣钉十字架。信佛的人基本上也承认自己有罪。加拉太人是保罗传福音结出的果子，当加拉太人被引（yin）诱背离福音的时候，保罗对他们的责备和提醒是：“无知的加拉太人哪，耶稣基督钉十字架，已经活画在你们眼前”。但是这一幕从他们的眼前消失了，他们忘了，反而去追随其它的教训。

钉十架是古代罗马的一种酷刑，在历史中只出现过一段时间就消失了，因为太惨不人道。在当时的社会，这个处分是一种忌讳，所以一年通常只有处分几个人。除非是极度重犯，否则不会轻易采用这种刑（xing）罚。是因为什么原因，要钉耶稣十字架呢？当时的原告就是犹太人的祭司长，长老还有百姓，他们的列出的罪状是什么呢？我们看看路加福音22:66-71：天一亮，民间的众长老连祭司长带文士都聚会，把耶稣带到他们的公会里，说：“你若是基督，就告诉我们。”耶稣说：“我若告诉你们，你们也不信；我若问你们，你们也不回答。从今以后，人子要坐在神权能的右边。”他们都说:"这样，你是神的儿子吗？"耶稣说：“你们所说的是。”他们说：“何必再用见证呢？他亲口所说的，我们都亲自听见了”，所以原告列的罪状就是耶稣宣告自己是神的儿子。而法官就是彼拉多。彼拉多听了百姓的陈词之后，自己亲自审问，但他查不出耶稣有什么罪。彼拉多又把耶稣解押到希律王那里，请希律王来裁决，同样希律王也查不出耶稣的罪状。路加福音23:13-16：彼拉多传齐了祭司长和官府并百姓，就对他们说：“你们解这人到我这里，说他是诱惑百姓的。看啦我也曾将你们告他的事，在你们面前审问，并没有查出他什么罪来，就是希律也是如此，所以把他送回来。可见他没有做什么该死的事。故此，我要责打他，把他释放了”。最终法官迫于原告的压力，把主耶稣钉了十字架。从人的角度看，钉耶稣的罪魁祸首就是祭司长，帮凶就是当时的公会、百姓以及彼拉多。而二千年后的我们，好像跟耶稣的死毫无关系，我们没有喊着要钉他十字架。我们只是这件历史的观众，没有参与其中，耶稣的死跟我们的关系在什么地方呢？耶稣的死是人类史上的一段真实历史，但人类历史的背后是神实行拯救的历史。英语中“历史”的意思不是我们的故事，而是他的故事，就是神的故事。在神那里，这件事跟我们有直接的关系。以赛亚书53:6，我们都如羊走迷，个人偏行己路，耶和华使我们众人的罪孽都归在他身上。这里说的众人，不单单是跟耶稣同时代的人，而是在历史长河中曾经出现的，现在活着的，以后来到这个世界的所有人。神把众人的罪孽归在耶稣身上，其中包括我的罪，你的罪。所以在神那里，耶稣的死跟我们有直接到关系，耶稣是因你我的罪而死。不信主的人，即使认罪，要么觉得大不了投胎做个低等动物，也没事大不了的事，要么认为大伙都一样，只要我不比周围的人差就行了，反正大家一起受罪。信主的人，时间长了对罪麻木了，反正耶稣的宝血已经洗净了我的罪。但我们如果思考耶稣死的方式，就会有更多的领受，他不是被砍头体面地死去，而是被人唾弃，死在被人藐视的十字架上。在耶稣死的方式上可以看到神对罪的态度，深恶痛绝，掩面不看，极其厌恶。因为罪和神圣洁的性情完全相违背。圣经告诉我们，神就是爱。以赛亚书49:15说，夫人焉能忘记她吃奶的婴孩，不怜恤她所生的儿子？即或有忘记的，我却不忘记你。人间最伟大的爱就是母爱，但神对我们的爱超越母爱。一个如此爱我们的神为什么要致死一个罪人？我们听说过大义灭亲的成语，一个母亲虽然爱她的孩子，如果她的孩子悖逆，顽梗，为非作歹，最后母亲的选择只能是大义灭亲。虽然神爱世人，但世人恶贯满盈的时候，神也必定实行审判，神不会纵容世人为所欲为。来9:22告诉我们，若不流血，罪就不得赦免。这是神对罪实行的公义审判。神的终极审判在人活着的时候不会来到，来9:27,按着定命，人人都有一死，死后且有审判。人对如何审判的认识左右着他活在世上的方式和态度，人的悲剧就是不知道将来的审判，但今天神已经通过圣经启示我们了。十字架表达的不仅仅是神拯救的爱，也表达了神对罪恶的审判。如果错误地以为死后没有审判，这个人可能会很勇敢，认为死了不过就是脖子上一个碗口大的伤疤。错误的认识带领错误的行动。敢跟老虎正面交锋的牛，是不认识老虎的牛。说我不下地狱谁下地狱的人，他对地狱没有清楚的认识。他的勇气来自于他对死后审判的错误认识。就像跟耶稣同钉十架的强盗，他还有心情讥诮耶稣。当人能明白审判是何等的审判的时候，我们就只会恐惧战兢。只有耶稣知道审判的程度如何。路加福音22:43-44，有一位天使从天显现，加添他的力量，耶稣及其伤痛，祷告更加恳切，汗珠如血点，滴在地上。耶稣对审判的程度清清楚楚，祂虽然得到了天使所加的力量，但在那一刻即将来临的时候，即将替我们承受审判的时候，他的汗珠如血点。吓得一身冷汗是我们对极度恐惧的反应，但耶稣对审判的惊恐的反应的汗珠如血点，已经超出常人的想象。我无法描述出神对罪的审判到底多重，透过十字架，和耶稣在面临十架刑罚的反应，只能知道是我们绝对、万万担当不起的。但慈爱的神因着祂的无比大爱，让祂儿子耶稣代替我们该受的刑罚，洗清我们的罪，好让我们在神面前能被算作一个无罪的人，只要我们承认自己的罪，相信耶稣。在神十字架的拯救计划中，没有看到人主动的影子，人都是被动的，都是神自己主动做成的。神主动把我们众人的罪孽归到耶稣身上，只要你相信神所作的，你的罪就归算在耶稣身上，否则只能自己承担罪恶的苦果。现在耶稣已经进入天堂，祂盼望世人都能相信祂，不至灭亡，反得永生。只要相信祂，祂就要把我们带到天堂，那里没有罪，没有痛苦，没有悲伤，没有失望，也没有眼泪，因为神要擦去我们眼泪。那里有的是满满的喜乐，深深的平安，因为神与我们同在。


我们再看这节经文：“无知的加拉太人啊，耶稣基督钉十字架，已经活画在你们眼前”。保罗传讲十字架上的耶稣的时候，极富感情色彩，有很强的渲染力，将历史上真实发生的事情用激烈的情感表达出来了。因为他属天的眼睛看到十字架上的神公义的审判，和神对世人的无比大爱。保罗对十字架的宣讲不是缺乏感情色彩的事实描述，不是事不关己高高挂起的态度，更不是冷冰冰的教条，而是活画出来。就是把耶稣和十字架的信息传讲得让人好像看得见，好像用画画出一样，在听众心里刻下深刻的印象。他比听众更容易激动，因为他知道末后审判没人能担当，迫切盼望他们能够相信福音。对那些不信的人，他以悲痛的心情讲述他的失望：“我屡次告诉你们，现在又流泪地告诉你们：他们的结局就是沉（chen）沦”。在福音的宣扬上，保罗注入了他所有的身心情感。保罗效法的是基督的榜样，耶稣也曾为耶路撒冷哀哭：“我多次愿意聚集你的女儿，好像母鸡把小鸡聚集在翅膀的地下，只是你们不愿意。”求神照明我们基督徒的眼睛，更深认识罪人的可怕结局，和神预备的美善救恩，好让我们在宣讲十字架信息的时候也能活画出来。


** 受圣灵是因福音而非律法
   
 十字架的救恩信息虽然很美好，真实，但很多人不喜欢。人的罪性常常迷惑我们的眼睛，周围的世界也在引诱离开救恩。加拉太人也被引诱，要靠律法行事为人，觉得如果不做点什么，怎么可能得到救恩呢？但保罗责备他们，受圣灵，不是因为行律法而是因为听信福音。当相信耶稣的时候，就会接受圣灵，作为得救恩的证据。不是因为常常拾金不昧，常常助人为乐，常常见义勇为，常常帮助乞讨的人，丰功伟绩、好人好事超过了周围的人，所以就满怀希望地去领取永生的奖赏。不是这样的！！！这些人确实很有价值，为社会做了贡献，但价值只是在地上的，不足以换取天堂的门票。社会需要的尊重那些有能力，有智慧的人。每个人都希望被认同，被承认。当你要得到社会的认可时，不可避免的是自己要付出努力，天下没有免费的午餐，只有靠着自己的努力才能被认可。所以从小就开始好好学习，天天向上，从小就开始了人生的赛跑，人生的起跑线画在妈妈的肚皮上，还没有出生的时候就开始胎教。因为周围的人，整体的文化都告诉我们要奋斗，才能换取灿烂的明天。努力是世人获得尊严的首要武器。当你比众人努力时，你会赢（ying）得掌声，称赞，认同。但是在救恩上，你会发现有力没地方使，你的努力没有半点效果。因为在神那里你所做的没有半点价值，因为你是个罪人，有功效的都是神在十字架上做成的。你们得救是本乎恩，也因着信，这并不是并不是出于自己，乃是神所赐的。
保罗曾经就这想靠自己的善行，严格遵守律法而换取救恩。但他认识神后，就有不同的看法了。腓3：6， 就律法上的义说，我是无可指摘（zhai）的。保罗比他同时代的人更为努力，是时代的佼佼者。但他后来转向相信基督，而不是依靠律法。腓3：9，并且得以在他里面，不是有自己因律法而得的义，乃是有信基督的义，就是因信上帝而来的义。  

** 成圣靠福音而非律法
加3:3你们即靠圣灵入门，如今还靠肉身成全吗？你们是这样无知吗？靠圣灵就是指靠福音，靠神。靠肉身就是靠律法，靠行为。不但我们的得救是完全靠着福音，我们在基督里的成长，或者说成圣，也是完全靠着福音。那些想要靠律法、靠行为在基督里成长的人，保罗责备他们无知。我们说要祷告，但如果是像法利赛人的那种祷告,对生命的成长没有帮助。我们说不可停止聚会，但参加聚会只是为了见到熟人，好像参加俱乐部，而不是敬拜神神，不能说没有一点价值，毕竟在聚会的地方比私下一人能更多地经历神，但不能得到最大的果效。祷告，聚会都是蒙恩的管道，从神得恩典的方式。有人打了个贴切的比方，信徒的一生像在海中航行的帆船，神恩典的东风吹来的时候，你要做的就是打开帆船的帆，接受神恩典的风，顺风而行。腓1：6，我深信那在你们心里动了善工的，必成就这工，直到耶稣基督的日子。所以从始至终都是神在我们心里做工，顺服神的带领和感动。如果按着天然的本性靠律法，靠行为，最终只会失败。

我们属灵的生命，如何成长？圣经说，不可停止聚会。不可停止聚会也可能成为我们的律法，以为聚会多了，生命自然就成长。有时我们可以反过来想：因为神在你心里动善工，引导你，吸引你来教会聚会，而你顺服神的带领，来到这里，这正是你生命成长的标志。这样看来，你来聚会就是生命成熟的象征。苹果树上结的苹果，表明这颗苹果树有生命。但把一个苹果挂在刺树上的时候，这颗苹果最后只会腐烂。聚会也一样，如果你因着福音而来聚会，聚会就是苹果树上的苹果。不然就是刺树上挂上去的苹果。
 当我信主后，好长时间没有团契，只是参加主日聚会，跟弟兄姐妹之间没有交通，基本上只是听听道而已。但是依然坚持主日，偶尔几次不想去的时候，我太太鼓励我参加。在人看，好像是自己坚持不懈地参加聚会，不违背不可停止聚会的命令，让我可以一直在基督里成长。现在回头想想，我是因着福音的缘故而一直坚持聚会。真的是神在一路带领，如果不是天父的爱吸引我们，没人会靠近主耶稣。天父的爱也吸引我们，引导我们在基督里成长。因为神叫万事互相效力，叫爱神的人得益处。
 

* 信心为本的人得祝福
** 亚伯拉罕因信称义
   加3:3, 亚伯拉罕信神，就算为他的义。
亚伯拉罕是旧约圣经中很伟大的人物，创世纪中有大量的篇幅讲述亚伯拉罕的人生经历。他被神看为朋友，被设立为万国之父。他在神面前是个义人，那他的义是怎么来的呢？圣经说，亚伯拉罕信神，就算为他的义。
希伯来书第十一章列举了亚伯拉罕典型的信心：来11：8 亚伯拉罕因着信，蒙召的时候，就遵命出去，往将来要得为业的地方去，出去的时候，还不知往哪里去。来11：17， 亚伯拉罕因着信，被试验的时候，就把以撒献上，这便是那欢喜领受应许的，将自己独生的儿子献上。头一个信心是进入未知之地的信心，后一个是献上儿子的信心。神操练我们信心的时候，带领我们信心一步一步跨越，我相信后一个信心比头一个信心更大。

献上儿子的信心是亚伯拉罕信心的巅峰，让我们回到当时的场景，看看亚伯拉罕因着什么原因可以献上儿子。亚伯拉罕献以撒的时候，亚伯拉罕有两个儿子，大的是以实玛利，小的是以撒。以实玛利是从使女夏甲生的，在亚伯拉罕心中的地位远远不及以撒。而且献以撒的故事发生在创世纪第22章，在第21章，圣经告诉我们以实玛利已经被赶走，不在亚伯拉罕身边，此时他身边只有一个孩子。以撒在亚伯拉罕心中的地位可以说是心头肉，是他晚年的全部。当我们年轻的时候，有奋斗的事业，对孩子可能还不是那么重视。但当我们进入晚年的时候，事业就不像年轻的时候那么重要，孩子变得比之前更重要，每个老年人都应该有这个的感受。亚伯拉罕生以撒的时候都已经100岁，献上以撒的时候，神学家估计那时以撒20岁左右，那么亚伯拉罕就120岁。20岁的以撒对亚伯拉罕来说是比他自己的性命重要的。但当神试验他的时候，他就因着信心愿意献上以撒。这是什么样的信心呢？创21：12后半句话：因为从以撒生的，才要称为你的后裔。亚伯拉罕相信神的话，他也必然相信以撒要生孩子。但献以撒的时候，还没有孩子。按照常人的理解，献上以撒之后，绝对不可能还能从他留下后裔。信神的人有时想通过自己的方式帮助上帝，亚伯拉罕也做过这样的事，曾经和侍女夏甲生下以实玛利，希望能从通过以实玛利留下后裔，替神解决难题，结果亚伯拉罕帮了倒忙。如今的亚伯拉罕没有通过人的方法来解决献上以撒及从以撒存留后裔的矛盾。总不能在献上以撒之前先赶紧娶个媳妇，生个孩子吧？理性已经到了尽头，信心的火被点燃。

回到亚伯拉罕对神的认识，他在创14：22说：“我已经向天地的主，至高的神耶和华起誓”。他相信神是天地的主，是至高的。他的信心在献以撒的时候展翅上腾了，来11：18-19，论到这儿子，曾有话说：“从以撒生的才要称为你的后裔。”他相信神能叫人从死里复活，他也仿佛从死中得回他的儿子来。信心引导理性，亚伯拉罕以为，在献上以撒之后，神要叫以撒死里复活。这样从以撒得后裔的应许就可以实现了。我们现在相信死人能够复活，是因为耶稣已经死里复活，如果没有圣经的记载，我们都无法相信死人能复活。亚伯拉罕有没有死人复活的历史可供参考呢？完全没有。如果死的时候，整个尸体是完整的，死人复活相对容易相信，如果把以撒作为祭献上，就得烧成骨灰，复活不要说是异想天开，连想都想不到。但就是在这个情况下，亚伯拉罕能“相信”神能叫人从死里复活，他的信心实在是一个标杆，难怪我们称呼他为信心之父。死里复活的信心，从亚伯拉罕开始，并且成为人的得救的必要条件，罗10：9，你若口里认耶稣为主，心里信神叫他从死里复活，就必得救。

如果亚伯拉罕不是因着信心献上以撒，他就是冷血动物，不近人情，杀人犯，应当受到谴责的。虎毒不食子，如果不是因着信心献上自己的儿子，他就比老虎都可怕。神称赞的不是亚伯拉罕献以撒的行为，而是称赞他的信心。罗4:2， 倘若亚伯拉罕是因行为称义，就有可夸的，只是在神面前并无可夸。亚伯拉罕不能对神说：“你看我把独生的儿子都献给你了，做了这么一件常人做不了的事情，这下你总得称我为义吧”。他在神面前没有可夸口的。神因他的信心，算他为义。

当年神向亚伯拉罕说话，亚伯拉罕就完全相信神。今天神借着圣经对我们说话，我们是否也完全相信神在圣经上所记载的？相信神创造天地？相信童女怀孕吗？相信耶稣用五饼二鱼喂饱5000人，相信耶稣在海面上行走，相信耶稣让死后发臭的拉撒路死里复活吗？更重要的是相信耶稣为了洗尽你我的罪而受死，从死里复活，现在坐在天父的右边吗？凡相信的人都是有福的。

** 亚伯拉罕的子孙以信为本
   从犹太来的假教师欺骗加拉太人，使他们以为单单靠福音还不够，必须加上割礼才算完全。割礼来自于亚伯拉罕时代，创17：9-10，神对又亚伯拉罕说：“你们所有的男子都要受割礼，这就是我与你，并你的后裔所立的约，是你们当遵守的”。假教师告诉加拉太人，要成为亚伯拉罕的后裔就必须受割礼。但罗马书说外面肉身的割礼不是真割礼，真割礼是心里的。耶利米9：25：“看啊，日子将到，我要刑（xing）罚一切受过割礼，心却未受割礼的”。 犹太人因着肉身血缘的关系而成为亚伯拉罕的子孙，在神那里人因着信心的缘故成为亚伯拉罕的子孙。 借着信心心里受割礼的人才是亚伯拉罕的真子孙。当年神应许亚伯拉罕的子孙将要多得像海边的沙，天上的星。算算亚伯拉罕肉身的子孙，现在的以色列中犹太人不到700万，不到上海人口的三分之一。在上海人面前说以色列人像海边的沙那么多，他们会偷笑。我们赞美信实的神，他成全了对亚伯拉罕的应许，因为以信为本的人，就是我们这些相信耶稣的人，才是亚伯拉罕的后裔，全世界有二十多亿。
   

** 以信为本同得祝福
加3：8-9，并且圣经既然预先看明，神要叫外邦人因信称义，就早已传福音给亚伯拉罕，说：“万国都必因你得福。”
神不仅仅是犹太人的神，也是外邦人的神，祂是全地的主。神的旨意是凡相信的人，不管是美国人，英国人，中国人，日本人，韩国人，朝鲜人，只要相信，就和亚伯拉罕一样得福。今天，每个周日，基本上任何一个国家，都有人进入教会敬拜神。因着信，和亚伯拉罕一同得福。 说到福气我们想到什么呢？世人要想的福气不外乎名利双收，事业如日中天。但没有不落的太阳，总会有夕阳西下的时刻。我以前很喜欢一首歌，叫做“向天再借五百年”，歌词中表现出来的英雄气概，每个人都很羡慕，敬仰。“我站在风口浪尖紧握住日月旋转”，一幅谁能横刀立马的气概。我曾经认为这种人好有福气，大英雄啊。但是......然后.......有一天你不得不躺在床上，然后.....有一天，幸运、有福的话，可能有人把你的黑白照片挂在墙上，然后........就没有然后了。诗篇103:15-16，至于世人,他的年日如草一样。他发旺如野地的花。经风一吹,便归无有。他的原处,也不再认识他。再或许你想要的福气是儿女双全，但孩子长大了总有一天会离开了你，甚至不孝顺。你的人生或者活得很精彩，但剧终的那一刻就在前面等着你。总的来说，世人的福气就是一个肥皂泡，有的肥皂泡大一些，有的漂亮一些，不管怎样，都会有破裂的时候。但不认识神的人乐此不彼地要吹大肥皂泡，不愿意面对，不愿意去思考肥皂泡破裂的时候。总结就是，世人的福气是兔子的尾巴，长不了。 神赐给我们的福气是什么样的呢？那是眼睛没有看见过，耳朵没有听见过，心里也没有想过的福气。那是天上的福气。就是赦罪的平安，神同在的喜乐，神话语的甘甜，心灵里的满足，弟兄姐妹彼此相交的温暖，虽然经过死阴的幽谷却不怕遭害的那种胆量，从神的仗，神的杆而来的安慰，在基督里的自由，对未来满有底气的盼望。不仅仅是今生的这些福气，还有主耶稣再来以后所赐给我们永活的，完美的，没有瑕疵的完全生命。天堂里没有痛苦，没有疾病，神会擦去我们一切的眼泪，那里有永远的喜乐。你信吗？我们在地上的痛苦，就算得了医治，那也是暂时的，以后我们会慢慢衰老，痛苦还会再一次临到人，直到我们死去的那一刻。但是在天堂那里，我们将得到永远的医治。
这些福气神只赐给那些和亚伯拉罕一样，以信为本的人。罗5：22~24，所以这就算为他的义。”算为他义“的这句话，不是单为他写的，也是为我们将来得算为义之人写的，就是我们这信神使我们的主耶稣从死里复活的人。

* 律法为本的人被咒诅
** 不全守律法被诅咒
   圣经中所说的律法不是国家制定的法律，而是上帝赐给人的生活标准，用来治理人的心灵，思想，言语和行为。

犹太人从摩西领（ling）受了从神而来的律法，并用文字的形式记录在圣经中。犹太人对律法引以为豪，因为万国之中，只有他们得到了从神而来的直接教导。申（shen）命（ming）记4：7-8，哪一大国的人有神与他们相近，像耶和华我们的神，在我们求告祂的时候与我们相近呢？又哪一大国有这样公义的律例、典章，像我今日在你们面前所 陈明的这一切律法呢？

犹太人有他们的律法，我们中国人呢？我们的祖先很有智慧地说：“是非之心，人皆有之，善恶之心，人皆有之”。但他们自己也不明白这种分辨是非曲直的心从哪里来。 圣经告诉我们，是神刻在人心里的。罗2：14 对于没有律法的外邦人若顺着本性行律法上的事，他们虽然没有律法，自己就是自己的律法。这是显出律法的功用刻在他们心里，他们是非之心同作见证，并且他们的思念互相较量，或以为是，或以为非。

所以不管犹太人，还是犹太以外的人，都有神所赐的律法。不一样的是犹太以外的人的律法刻在心里，在良心之中。而犹太人的律法记载在圣经中。全世界的人有不同的肤色，不同国家有不同的风俗习惯。但绝对没有那个国家称赞偷窃行为，绝对没有那个国家鼓励顶撞父母，不孝敬父母，绝对没有那个国家认为撒谎是一钟美德，更没有那个国家夸奖杀人放火。中国外国没有不一样。同样，古代现代也没有不一样。唐代的人以胖为美，唐贵妃就是例子，而现在的人以瘦为美。但当不管是唐代人，现在的人，做人该有的基本准则不会随着时间而变化。为什么会这样？因为无论古今中外的人，独一的神耶和华把律法刻在他们心里。

但因为罪的缘故，刻在心里的律法模糊不清。如果一个人总是昧着良心做事，我们会说他良心被狗吃了，他们心里律法的作用就很弱。所以要回到圣经上用文字记载下来的律法。旧约中的十诫是律法的缩影（ying），包括不可杀人，不可奸淫，不可偷窃，孝敬父母，不可贪恋别人的妻子，不可贪恋别人的钱财，要爱上帝。当我们听到一条条的律法的时候，心里怎么想，是不是：“这一条我做到了，加10分，那一条做的也不错，算8分，一共92分，比大部分人都强”。当我们判断人的好坏的时候，是把遵守律法而得的分数加起来，再一分高下。但神是怎么说的呢？加3：10下，凡不常照律法书上所记一切之事去行的，就被咒诅。这里强调的是两点，第一点是常常，没有例外的情况，没有所谓的情有可原，比如老板给你穿了小鞋，回家后正巧碰到父母做了件不如你意的事，平时还能忍住不顶撞他们，此时就忍不住而发火了。第二点是一切事，也许你做了不杀人，你做到了爱神吗？人没有常常，没有一切律法都遵守，圣经说他们是被咒诅的。人有个虚假的安全感，我比周围大部分的人都强，我就安全了。但我们要知道在律法的考试中，即使你是全班第一，十条诫命，每条10分，总分100分，你拿了99分，够高了吧，但在神那里及格线是满分1000分。因为要做到常常，要做到一切事才是及格线。


** 没有人能全守律法
拉3：11-12，没有一个人靠着律法在神面前称义，这是明显的，因为经上说：“义人必因信得生。”律法原不本乎信，只说：“行这些事的，就必因此活着”。
永远的生命只有通过相信耶稣才能得到。圣经上虽然说行律法上的事，就可以活着，但实际没有一个人能得的到。看看主耶稣是怎么谈到律法的，太5：22， 只是我告诉你们：凡向弟兄动怒（nu）的，难免受审判。凡骂弟兄是拉加的，难免公会的审断；凡骂弟兄是魔利的，难免地狱的火。拉加是废物的意思，魔利是笨蛋的意思。当我们骂人是废物，笨蛋，白痴的时候，圣经说以后免不了地狱的火。我们自己反省一下一年之中有几次骂人是废物，笨蛋。神在审判的时候不仅仅要追讨骂出口的罪，也要追讨憋人心里骂，还骂出口的罪，因为在心里骂人也是罪。

回想我们的人生经历，很小的时候贪吃但不贪财，因为不知道钱财是啥东西，等明白了钱财是什么，就开始贪财。再长大点就开始贪色，贪名。人生失意的时候就开始恨，恨孩子读书不争气，恨丈夫工作不努力，赚钱不够多，不理解自己，恨妻子无理取闹，泼妇骂街，恨父母对待自己不公。

如果扪心自问，谁能够全受律法呢？大卫说：”我知道我的过犯,我的罪常在我面前“。学习雷锋好榜样，雷锋是国人心中的大好人，但在审判的时候，他的良心会告诉他自己，他也是个罪人。周围的人对我们的评价远远高过当得评价，因为他们不知道我们心里的肮脏，污秽，黑暗。但神查看人心，看得清清楚楚。诗篇130：3，主耶和华啊，你若纠察罪孽，谁能站立得住呢？当你尽力要做好人的时候，就会发现好人真难做。我们会怪罪于环境，错误地以为周围的环境让我做不了好人，但其实是因为自己骨子里带着从亚当而来的罪。耶稣是我们的榜样。按照旧约律法，犯奸淫的人要用石头打死他。有人当场抓住犯奸淫的女人，带到耶稣面前，问耶稣怎么办她，耶稣说：“你们中间谁是没有罪的，谁就可以先拿石头打她”。结果没有一人先出手拿石头打她，从老到少一个接一个离开了。因为他们知道自己也没有遵守律法。为啥是从老到少呢？因为越是年长的，犯的罪越多，也越知道自己是个罪人。·罗3:17~20 平安的路，他们未曾知道。 他们眼中不怕神。我们晓得律法上的话，都是对律法以下之人说的， 好塞住各人的口，叫普世的人都伏在神审判之下。所以凡有血气的，没有一个因行律法能在神面前称义，因为律法本事叫人知罪。

罗3:21 因为世人都犯了罪，亏欠了神的荣耀。
神造出大海陆地的时候，神看着是好的；造出树木蔬菜的时候，神看着是好的；造出日月星(xing)辰(chen)的时候，神看着是好的；造出海里的鱼，天空的鸟的时候，神看着是好的；神造出陆地上的动物的时候，神看着是好的。而当神造出人的时候，圣经告诉我们：“神看着一切所造的都甚（shen）好”，非常的好，不是一般的好。人是神所有创造中的极品（pin），因着人的被造，宇宙万物从“好的”变成“很好”。我们会惊叹于宇宙穹苍的深邃，不可测度，但我们人类自己才是神创造中的精品。人的被造本来要为宇宙万物增色，应当显出神的荣耀，这是神造人的目的。但现实告诉我们，在周围的世界，我们看不出神的荣耀来。因为我犯了罪，因为你犯了罪，因为世人都犯了罪，亏缺了神的荣耀。如果有人说你是好人，心里不要自喜。如果有人说你是好人，可以享平安，上天堂，你更要谨慎。耶6:14“他们轻轻忽忽地医治我百姓的损伤，说，平安了。平安了。其实没有平安。”

当专门教导律法的律法师试探耶稣：“律法上的诫命，哪一条是最大的呢？”。耶稣回答：“你要尽心，尽性，尽意爱主你的神”。即使是成熟的基督徒，这一条也做不到。参加主日崇拜的时候会迟到。唱赞美诗的时候，可能只是陶醉于诗歌的旋律，并没有真心地敬拜神。祷告的时候，想到的可能仅仅是自己的需要和难处。读圣经的时候，也许就是为了完成任务。祷告时留下的眼泪里也许带着自怜的成分。这些我都经历过。但神安慰我们：我们的得救，在基督里的成长，不是因为遵守律法，而是耶稣已经代替我们受了咒诅。



** 基督代信徒受咒诅
但我们因违背律法而该受的咒诅，因着主耶稣愿意代替我们承担的缘故，他就成为了咒诅，好叫我们免了咒诅。
亚伯拉罕撒谎的罪，耶稣替他承担；大卫犯奸淫，杀人的罪，耶稣替他承担；约拿不顺服神的罪，彼得三次不认主的罪，保罗迫害基督徒的罪，耶稣替他承担。你我贪爱钱财的罪，贪爱这个世界的罪，不尽（jin）忠的罪，不尽心尽性尽力尽意爱主的罪，耶稣都替我们承担。没有一个罪大得耶稣承担不起，也没有一个罪太恶心得耶稣不愿意为我们承担。祂愿意，也能够替我们担当一切的罪。
当耶稣用祂的血和生命替我们承担咒诅的时候，我们就得到了平安。因祂受的刑罚，我们得平安；因祂受的鞭伤，我们得医治。当你相信耶稣的时候，你就是属祂的人，神将成为你的避难所，你的安息地。信靠祂的人，必不至于羞愧。祂会保守我们一生，将生命的道路指教给我们，行在正道当中，等到耶稣第二次再来的时候，祂会把我们接在荣耀里。

* 结论
正如司布真所言，“生不足喜，可喜的是有主同在；死不足惧，可惧的是不认识主而死”
