* 引言
你认为基督徒是什么样的人？常见的回答就是：基督徒很好，做好事，心地良善，道德高尚，乐于助人。最开始听到这种回答的时候，很开心，因为把我算到道德高尚的那一类人中。等我更多地认识自己，认识神后，再听到这种回答，打心底出来的滋味很复杂。惭愧的是因为我觉得自己不是那种人，鼓舞的是那些生命成熟的基督徒在世人面前为主做了美好的见证，欣慰神的眼光跟世人的眼光不同，不然我就不配做基督徒，跟基督无份了。五年前坐在我旁边的一个同事，虽然不信主，我看他比我心地良善多了，更乐于助人。同事有需要，他总是主动伸出双手帮助别人，同事要搬家的时候，他主动提出来帮忙他们搬家。男女同事一起活动的时候，他总是表现出一副女士优先的姿态。上下楼梯的时候，他彬彬有礼地主动礼让。我相信很少有基督徒能够像他那样有爱心。想起来他比我更像基督徒。我们出生在礼仪之邦，但周围每天发生的事情都在嘲讽这个称号，地铁上男女对骂的现象见怪不怪，但从他身上还能看出礼仪之邦的残余影子。他身上确实有值得我学习的地方。但是我知道我是真正的基督徒，虽然生命中没有像他那样散发出爱的芬芳，也比不上他的行为举止。但我知道我对基督是有信心的，基督是我的救主。基督拯救我们，是因为我们有信心，而不是因为我们比其他人高尚。 

* 加拉太人的归主经历
** 活画的耶稣并祂钉十字架
   我们信的是什么？就是耶稣基督钉十字架。这个是信仰的中心，相信耶稣基督钉十架才是基督徒的开始。我们在跟人传福音的时候，一般先讲罪，然后讲耶稣基督十字架上的拯救。有一批人不认为自己有罪，承认自己有罪的一批人中又有一批人不相信耶稣钉十字架。信佛的人基本上也承认自己有罪。加拉太人是保罗传福音结出的果子，当加拉太人被引（yin）诱背离福音的时候，保罗对他们的责备和提醒是：“无知的加拉太人哪，耶稣基督钉十字架，已经活画在你们眼前”。但是这一幕从他们的眼前消失了，他们忘了，反而去追随其它的教训。

钉十架是古代罗马的一种酷刑，在历史中只出现过一段时间就消失了，因为太惨不人道。在当时的社会，这个处分是一种忌讳，所以一年通常只有处分几个人。除非是极度重犯，否则不会轻易采用这种刑（xing）罚。是因为什么原因，要钉耶稣十字架呢？当时的原告就是犹太人的祭司长，长老还有百姓，他们的列出的罪状是什么呢？我们看看路加福音22:66-71：天一亮，民间的众长老连祭司长带文士都聚会，把耶稣带到他们的公会里，说：“你若是基督，就告诉我们。”耶稣说：“我若告诉你们，你们也不信；我若问你们，你们也不回答。从今以后，人子要坐在神权能的右边。”他们都说:"这样，你是神的儿子吗？"耶稣说：“你们所说的是。”他们说：“何必再用见证呢？他亲口所说的，我们都亲自听见了”，所以原告列的罪状就是耶稣宣告自己是神的儿子。而法官就是彼拉多。彼拉多听了百姓的陈词之后，自己亲自审问，但他查不出耶稣有什么罪。彼拉多又把耶稣解押到希律王那里，请希律王来裁决，同样希律王也查不出耶稣的罪状。路加福音23:13-16：彼拉多传齐了祭司长和官府并百姓，就对他们说：“你们解这人到我这里，说他是诱惑百姓的。看啦我也曾将你们告他的事，在你们面前审问，并没有查出他什么罪来，就是希律也是如此，所以把他送回来。可见他没有做什么该死的事。故此，我要责打他，把他释放了”。最终法官迫于原告的压力，把主耶稣钉了十字架。从人的角度看，钉耶稣的罪魁祸首就是祭司长，帮凶就是当时的公会、百姓以及彼拉多。而二千年后的我们，好像跟耶稣的死毫无关系，我们没有喊着要钉他十字架。我们只是这件历史的观众，没有参与其中，耶稣的死跟我们的关系在什么地方呢？耶稣的死是人类史上的一段真实历史，但人类历史的背后是神实行拯救的历史。英语中“历史”的意思不是我们的故事，而是他的故事，就是神的故事。在神那里，这件事跟我们有直接的关系。以赛亚书53:6，我们都如羊走迷，个人偏行己路，耶和华使我们众人的罪孽都归在他身上。这里说的众人，不单单是跟耶稣同时代的人，而是在历史长河中曾经出现的，现在活着的，以后来到这个世界的所有人。神把众人的罪孽归在耶稣身上，其中包括我的罪，你的罪。所以在神那里，耶稣的死跟我们有直接到关系，耶稣是因你我的罪而死。不信主的人，即使认罪，要么觉得大不了投胎做个低等动物，也没事大不了的事，要么认为大伙都一样，只要我不比周围的人差就行了，反正大家一起受罪。信主的人，时间长了对罪麻木了，反正耶稣的宝血已经洗净了我的罪。但我们如果思考耶稣死的方式，就会有更多的领受，他不是被砍头体面地死去，而是被人唾弃，死在被人藐视的十字架上。在耶稣死的方式上可以看到神对罪的态度，深恶痛绝，掩面不看，极其厌恶。因为罪和神圣洁的性情完全相违背。圣经告诉我们，神就是爱。以赛亚书49:15说，夫人焉能忘记她吃奶的婴孩，不怜恤她所生的儿子？即或有忘记的，我却不忘记你。人间最伟大的爱就是母爱，但神对我们的爱超越母爱。一个如此爱我们的神为什么要致死一个罪人？我们听说过大义灭亲的成语，一个母亲虽然爱她的孩子，如果她的孩子悖逆，顽梗，为非作歹，最后母亲的选择只能是大义灭亲。虽然神爱世人，但世人恶贯满盈的时候，神也必定实行审判，神不会纵容世人为所欲为。来9:22告诉我们，若不流血，罪就不得赦免。这是神对罪实行的公义审判。神的终极审判在人活着的时候不会来到，来9:27,按着定命，人人都有一死，死后且有审判。人对如何审判的认识左右着他活在世上的方式和态度，人的悲剧就是不知道将来的审判，但今天神已经通过圣经启示我们了。十字架表达的不仅仅是神拯救的爱，也表达了神对罪恶的审判。如果错误地以为死后没有审判，这个人可能会很勇敢，认为死了不过就是脖子上一个碗口大的伤疤。错误的认识带领错误的行动。敢跟老虎正面交锋的牛，是不认识老虎的牛。说我不下地狱谁下地狱的人，他对地狱没有清楚的认识。他的勇气来自于他对死后审判的错误认识。就像跟耶稣同钉十架的强盗，他还有心情讥诮耶稣。当人能明白审判是何等的审判的时候，我们就只会恐惧战兢。只有耶稣知道审判的程度如何。路加福音22:43-44，有一位天使从天显现，加添他的力量，耶稣及其伤痛，祷告更加恳切，汗珠如血点，滴在地上。耶稣对审判的程度清清楚楚，祂虽然得到了天使所加的力量，但在那一刻即将来临的时候，即将替我们承受审判的时候，他的汗珠如血点。吓得一身冷汗是我们对极度恐惧的反应，但耶稣对审判的惊恐的反应的汗珠如血点，已经超出常人的想象。我无法描述出神对罪的审判到底多重，透过十字架，和耶稣在面临十架刑罚的反应，只能知道是我们绝对、万万担当不起的。但慈爱的神因着祂的无比大爱，让祂儿子耶稣代替我们该受的刑罚，洗清我们的罪，好让我们在神面前能被算作一个无罪的人，只要我们承认自己的罪，相信耶稣。在神十字架的拯救计划中，没有看到人主动的影子，人都是被动的，都是神自己主动做成的。神主动把我们众人的罪孽归到耶稣身上，只要你相信神所作的，你的罪就归算在耶稣身上，否则只能自己承担罪恶的苦果。现在耶稣已经进入天堂，祂盼望世人都能相信祂，不至灭亡，反得永生。只要相信祂，祂就要把我们带到天堂，那里没有罪，没有痛苦，没有悲伤，没有失望，也没有眼泪，因为神要擦去我们眼泪。那里有的是满满的喜乐，深深的平安，因为神与我们同在。


我们再看这节经文：“无知的加拉太人啊，耶稣基督钉十字架，已经活画在你们眼前”。保罗传讲十字架上的耶稣的时候，极富感情色彩，有很强的渲染力，将历史上真实发生的事情用激烈的情感表达出来了。因为他属天的眼睛看到十字架上的神公义的审判，和神对世人的无比大爱。保罗对十字架的宣讲不是缺乏感情色彩的事实描述，不是事不关己高高挂起的态度，更不是冷冰冰的教条，而是活画出来。就是把耶稣和十字架的信息传讲得让人好像看得见，好像用画画出一样，在听众心里刻下深刻的印象。他比听众更容易激动，因为他知道末后审判没人能担当，迫切盼望他们能够相信福音。对那些不信的人，他以悲痛的心情讲述他的失望：“我屡次告诉你们，现在又流泪地告诉你们：他们的结局就是沉（chen）沦”。在福音的宣扬上，保罗注入了他所有的身心情感。保罗效法的是基督的榜样，耶稣也曾为耶路撒冷哀哭：“我多次愿意聚集你的女儿，好像母鸡把小鸡聚集在翅膀的地下，只是你们不愿意。”求神照明我们基督徒的眼睛，更深认识罪人的可怕结局，和神预备的美善救恩，好让我们在宣讲十字架信息的时候也能活画出来。


** 受圣灵是因福音而非律法
   
 十字架的救恩信息虽然很美好，真实，但很多人不喜欢。人的罪性常常迷惑我们的眼睛，周围的世界也在引诱离开救恩。加拉太人也被引诱，要靠律法行事为人，觉得如果不做点什么，怎么可能得到救恩呢？但保罗责备他们，受圣灵，不是因为行律法而是因为听信福音。当相信耶稣的时候，就会接受圣灵，作为得救恩的证据。不是因为常常拾金不昧，常常助人为乐，常常见义勇为，常常帮助乞讨的人，丰功伟绩、好人好事超过了周围的人，所以就满怀希望地去领取永生的奖赏。不是这样的！！！这些人确实很有价值，为社会做了贡献，但价值只是在地上的，不足以换取天堂的门票。社会需要的尊重那些有能力，有智慧的人。每个人都希望被认同，被承认。当你要得到社会的认可时，不可避免的是自己要付出努力，天下没有免费的午餐，只有靠着自己的努力才能被认可。所以从小就开始好好学习，天天向上，从小就开始了人生的赛跑，人生的起跑线画在妈妈的肚皮上，还没有出生的时候就开始胎教。因为周围的人，整体的文化都告诉我们要奋斗，才能换取灿烂的明天。努力是世人获得尊严的首要武器。当你比众人努力时，你会赢（ying）得掌声，称赞，认同。但是在救恩上，你会发现有力没地方使，你的努力没有半点效果。因为在神那里你所做的没有半点价值，因为你是个罪人，有功效的都是神在十字架上做成的。你们得救是本乎恩，也因着信，这并不是并不是出于自己，乃是神所赐的。
保罗曾经就这想靠自己的善行，严格遵守律法而换取救恩。但他认识神后，就有不同的看法了。腓3：6， 就律法上的义说，我是无可指摘（zhai）的。保罗比他同时代的人更为努力，是时代的佼佼者。但他后来转向相信基督，而不是依靠律法。腓3：9，并且得以在他里面，不是有自己因律法而得的义，乃是有信基督的义，就是因信上帝而来的义。  

** 成圣靠福音而非律法
加3:3 你们即靠圣灵入门，如今还靠肉身成全吗？你们是这样无知吗？
靠圣灵就是指靠福音，靠神。靠肉身就是靠律法，靠行为。不但我们的得救是完全靠着福音，我们在基督里的成长，或者说成圣，也是完全靠着福音。
那些想要靠律法在基督里成长的人，被保罗责备为无知。

我们说教导要祷告，但如果是像法利赛人的那种祷告。对生命的成长没有帮助。
我们说不可停止聚会，但参加聚会只是为了见到熟人，而不是敬拜神神。我不能说没有一点价值，毕竟在聚会的地方比私下一人能更多地经历神，但不能得到最大的果效。祷告，聚会都是蒙恩的管道，从神得恩典的方式。有人打了个贴切的比方，信徒的一生像在海中航行的帆船，神恩典的东风吹来的时候，你要做的就是打开帆船的帆，接受神恩典的风，接风而行。

耶和华所命定的福，通常是在集体，教会的聚集中。
蒙恩的渠道，但不是恩典本身。

腓1：6，我深信那在你们心里动了善工的，必成就这工，直到耶稣基督的日子。我们属灵的生命，如何成长？圣经说，不可停止聚会。不可停止聚会也可能成为我们的律法，以为聚会多了，生命自然就成长。

在世人眼中，有的只是机缘巧合。但在神那里，都是神命定的，或者允许的。没有任何一件事情不在神的掌管之中。作为神的儿女，当你面对艰难的处境，神仍然在掌管你的人生，祂没有缺席。当我信主后，好长时间没有团契，只是参加主日聚会，跟弟兄姐妹之间没有交通，基本上只是听听道而已。但是依然坚持主日，偶尔几次不想去的时候，我太太鼓励我参加。在人看，好像是自己坚持不懈地参加聚会，不违背不可停止聚会的命令，让我可以一直在基督里成长。现在回头想想，真的是神在一路带领。如果不是天父的爱吸引我们，没人会靠近主耶稣。天父的爱也吸引我们，引导我们在基督里成长。

神叫万事互相效力，叫爱神的人得益处。
