* 引（yin）言
 杞人忧天的故事大家都知道。他头顶蓝天，却整天担心蓝天会崩塌下来，脚踏大地，却成天害怕大地会陷落下去，以致睡不着觉，吃不下饭。
有个人去开导他，说：“天不过是积聚的气体罢了，没有哪个地方没有空气的。你一举一动，一呼一吸，整天都在天空里活动，怎么还担心天会塌下来呢？”
杞个人说：“天如果是气体，那日月星辰不就会掉下来吗？”
开导他的人说：“日月星辰也是空气中发光的东西，即使掉下来，也不会伤害什么。”
杞人又说：“如果地陷下去怎么办？”
开导他的人说：“地不过是堆积的土块罢了，填满了四处，没有什么地方是没有土块的。 你行走跳跃，整天都在地上活动，怎么还担心会陷下去呢？”
经过这个人一解释，那个杞国人放下心来，很高兴。 

当我处在这种乌云密布的环境中的时候，我心里也会闪过一丝念头，天不会塌下来吧。

现在科技发达了，又有各种行星撞地球的预测。这种预测是不是现代版的杞人忧天呢？

也许杞人经历过这种乌云压顶的天气，而担心天会塌下来。
也许他没有见过，而只是头脑中有很多思考而已，那说明杞人是一个很有前瞻性的人。

因为天地确实有废去的时候。
彼后3：10
"那日，天必大有响声废去，有形质的都要被烈火销化。地和其上的物都要烧尽了。“
彼后3：13
"但我们照他的应许，盼望新天新地，有义居在其中"
当我们确信这天地万物都是神创造，护理的时候。
在末日之前，我们就不用担心。
因为神用权能的命令托着万有，托住天地万物。
到了末日的时候，那是我们信徒热切盼望的时刻，进入新天新地的时候。
那一刻，杞人会发现自己的忧虑是对的。而那个好心劝解他的人发现自己其实是在忽悠。


杞人在被人劝解后，也许不再担忧天塌下来。也许他开始担忧人生了，他的生活，工作，婚姻。因为人生不如意之事十之八九。
杞人担忧天地崩溃，只有在他认识神后，明白神创造天地万物的旨意后，他才能真真得安慰。
对生活的担忧，只有在明白、深信神造人的目的后，才能得到缓解。



* 神创造第一个人
  
** 神造人的背景
5节：野地还没有草木，田间的菜蔬还没有长起来，因为耶和华神还没有降雨在地上，也没有人耕（geng）种。


经文告诉我们，没有草木，没有菜蔬的原因，是神没有降雨，人没有耕种。只有神和人同时做工，神才命定好的结果。在神造人之前，神对人就有期待，期待他来耕种。
全能的神完全可以自己包办所有的事情，在不需要人的情况下，就使菜蔬长起来。但神选择了与人同工，在还没有造你我之前，就已经选择了与你我同工。有点像父母带着小孩子画画，写字一样，父母自己可以画的更好，写的更好，但带着孩子做的时候，不仅父母喜悦，小孩子也开心。

** 神创造亚当
  耶和华神用地上的尘（chen）土造人，将生气吹在他鼻孔里，他就成了有灵的活人。
圣经告诉我们人的来龙去脉。这一节经文告诉我们人是怎么来的。圣经还告诉我们关于人的几个重大问题的答案。
 比如人活着是为了什么？荣耀神。人为什么会死？因为罪。死后会怎么样？死后有审判，要么复活得生，要么复活定罪。
只有圣经对人的存在和意义给出了完整的答案。250年前的进化论看起来回答了生命之谜，其实他们是在走一条多年前的老路，3000多年前，大卫在诗篇14：1中说， 愚顽人心里说：“没有神”。不信神不是文明进步的产物，3000年前也有人说没有神。如果进化论想解释人的起源，其实就是那心里说没有神的人。按照适者生存的观点，
一个生命越来越适应环境，他按道理一代比一代活得长。按着适者生存的推论，生命的进化目标就是长生不死。但圣经说罪的代价就是死。
因着罪进入世界，死就临到众人。我们看到的实际情况是，人的寿命并没有什么提高，摩西活到120岁，现在很少看到人活到120。

我们都是神所造的，都是亚当的后裔。各色人种，土著（zhu）人，野蛮人，食人族的人，都是亚当的后裔。

神造田地万物时，说有就有，命立就立，有点像在做脑力劳动。但是在造一个不到两米的人的时候，经文的意思看起来是
是在做体力劳动。首先用地上的尘土造人，造人的“造” 这个词，描述的画面就是一个陶（tao）匠用泥土塑造器皿的画面，用手在捏泥土。
吹气在人鼻孔里，是用嘴气起的一个动作。当然这些都是拟人化的描述，因为神是个灵，没有我们这样的身体。

神是何等的地爱人啊，他造我们用了高规格的方式，不同于其他的万物。神造的宇宙这么大，而人的眼光盯着的就是一个小小的自我，一个
躺在地上不到2平方米的一个存在。
诗8：3~4 我观看你指头所造的天，并你所陈设的月亮星宿，便说，人算什么，你竟（jing）眷顾他？大卫是个放羊娃，有时他会躺在
草地上看天上的星（xing）星月亮，对比人类的在星空下渺小的影子，发出感慨，神啊，你竟然如此眷顾人。浩瀚的天空,神一句话
就造好了，而神却乐意从尘土中塑造我们，吹给我们生命的气息。我们都是蒙恩的尘土。
我们比大卫更能深入的认识宇宙，但愿从星空和人的对比中，让我们知道自己的渺小，就去赞美神的伟大。当我们在患难中的时候，推开家里的窗户，看看天空，感受神的能力，体会神是怎么创造我们的，也许能帮助我们缓解紧张的压力。

有些人只想生孩子，不愿养孩子。神不但造了人，同时也为人安排生活。


* 神安排人的生活
** 神为人预备住所
创2：8 耶和华神在东方的伊甸立了一个园子，把所造的人安置在那里。
我们每个人都想往一个优美的住处，安静美丽环境。租房的想要一个自己的房子。多层的想要个高层。高层的想要个别墅。别墅的想要个山庄。
但是神所预备的比人能够想到的更美，是伊甸园。
伊甸园在什么地方呢？经上说这个地方有四条河，现在还在的有幼发拉底和底格里斯河。其他2条河流已经干涸了。按着经文记载，伊甸园在4条河的交界处。
幼发拉底河跟底格里斯河在两个地方汇合，由此推断伊甸园的位置大概在地图上的这两个位置（出示地图）。

那里各样的树
能悦人的眼目，上面结满了各样的果子。不打农药，不用化肥，没有害虫，没有虫眼，不用零度保鲜。
而且园子里气候适宜，应该是四季如春的环境，因为当年的亚当夏娃赤身露（lu）体，都没有觉得冷。
更别说园子中间的那棵生命树，能延长人的寿命。这个是世人梦寐以求但靠人自己无论如何也得不到的。
伊甸园里有生命树，神也赐给我们生命树。耶稣说：“我就是道路、真理、生命；若不借着我，没有人能到父那里去“。凡是相信耶稣是神的儿子，相信祂死了复活，洗净你的罪的人，你就得到了 生命树的果子。

神为人安排了住所，也赐下工作，来实现人生的意义和价值。

** 神为人预备工作
创2：15 耶和华神将那人安置在伊甸园，使他修理看守。
修理就是做园丁，看守就是当保安。神创造我们的时候，给了我们做工的需要。
工作不仅仅是养家糊口的途径，更是神的呼召。在英文中，职业也是天命，神召的意思。
神透过基督徒的工作来治理这个世界，借着基督徒的工作显出神的荣耀。现在我们所享受的很多便利，都是基督徒做工的结果。
医院，福利院，孤儿院，姐妹们不用裹小脚，如果追溯他们的来历，就会看到基督徒开拓性的工作。


工作要按着神的旨意治理这地。工作本身没有贵贱之分，世人有脑力劳动和体力劳动的贵贱之分，但圣经并没有差异化对待。
神造人的时候，使用尘土造人，吹气在人的鼻孔里， 都是体力劳动的标志。
主耶稣在世上的时候出身也是木匠。对待工作，一方面不能当做一个负担，同时不能让工作成为自己的偶像。
因为工作是神的呼召，所以在上班的时候我们可以向神祷告，求神给智慧和能力做好当天的工作。

在人类犯罪之前，神已经为人安排了工作。进入天国之后我们还会有工作。神安排的都是好的，工作都是对我们有益处的。但我们常常不能享受工作。
主在地上行走的时候，祂享受祂的工作。主耶稣说：“我的食物就是遵行差我来者的旨意，做成祂的工”。主耶稣把做工比喻成食物。

而我却做不到，因为我在工作中服侍的不是神，而是偶像。这个偶像很多时候不是工作，而是金钱。
我读书的时候学的是工业自动化，因为IT好找工作，就自学计算机后来做IT。IT中有很多不同的领域，我又自学，进入一个更好找工作的领域。

撒旦有时会用动听的词来掩饰我们的真实情况。敬业是一个很好的词，热爱工作也是很好的词。但是同样的卖力工作，不一定配得上敬业和热爱工作，因为我们的心可能只是为了钱财而已，如果薪水降一半，还会一样敬业，热爱工作吗？

看起来我爱我所做的工作，但是当有更好的机会的时候，放下这个工作，再找一个。我找工作的动力，其实说白了就是为了更好的待遇。就是热爱更好的待遇，更直白一点就是爱财。但是这个爱财的词不好听。我在工作中的满足感，在于薪水的调整。但神给我们的工作是为了修理看守，修理就是把无须的变得有序，把杂乱无章变为井井有条，把堕落变为洁净。我们身边的堕落的灵魂，等着我们去传讲福音。

另一方面，更好薪水，对神的国也有益处，首先是十一奉献多了。更重要的是，那些薪水高的行业，压力大，他们也许除了钱之外，穷得什么都没有，他们也更难信主，因为财主进天国是难的，所以更需要弟兄姐妹帮助他们，带给他们福音。

我们周围也有很多真正热爱工作的例子。
李冬传道愿意弟兄姐妹跟他一起吃饭，他的要求是吃饭的钱要么平(ping)摊，要么他自己承担，不愿意给他人增加负担。在他的这种工作里，做的是亏本的买卖，这个就是单纯的热爱工作。
楚阿姨她们探访医院，这是神给她们的工作，没有从人来的回报，只有从人来的白眼和不屑一顾，还是坚持。人看是不务正业，在神看是敬业，热爱工作，这就是神所说的修理的工作，承担这个世界的盐的作用，显出神的荣耀。

神安排了工作后，又赐下诫命。
** 神为人颁布诫命
 16节：“耶和华神吩咐他说：‘园中各样树上的果子，你可以随意吃，只是分别善恶树上的果子，你不可吃，因为你吃的日子必定死’”
神为人预备了一个伊甸园，预备了丰盛的食物，园中各样树上的果子，你可以随意吃。在这里没有缺乏，有的是神丰丰富富的供应。唯独一个树上的果子，不可以吃。吃的日子必定死。

可惜的是因着亚当犯罪的缘故，伊甸园已经成为历史，成为挥之不去的回忆，那是人类美好的家乡。
我们现在所处的环境，不管怎么改造，也不能让人满足，不能造成自己的伊甸园，因为我们没法除掉这个世上的罪。
但我们是有盼望的人。
因着主耶稣流血牺牲的拯（zheng）救，让我们这本离开伊甸园的人，可以重新回到更美的乐园。在路23：43中，耶稣对那位有信心的强盗说，“我实在告诉你，今日你要同我在乐园了”。
因着对圣灵的顺从，让我们这些离开生命树的人，有一天可以再得到生命树的果子。
在启示录中2：7，圣灵向众教会所说的话，凡有耳的，就应当听。得胜的，我必将神乐园中生命树的果子赐给他吃。

神也满足我们情感的需要，为我们预备配偶。
* 神为人预备配偶
人生活在好的环境中还不够，还需要有一个配偶。
神在第六天造好了亚当后，神说“那人独居不好”，这是创世过程中，唯一一次被神称为不好的地方。但在第六天结束前，圣经说：神看着一切所造的都甚好。
因着什么缘故导致不好到甚好的转变呢？是因着夏娃的被造。
同时圣经用一节经文讲述亚当的被造，而用六节经文讲述夏娃的被造。由此可见神很重视女性。圣经是古代文化中唯一一个重视女性的书卷。


我们从三个方面查考神为人预备配偶这件事。
** 神知道人的需要
人是神创造的，神比人更知道人的需要。
在伊甸园中亚当有美味水果做食物，有花草树木悦人的眼目，有各种飞鸟（niao）走兽做朋友，有各种各样宠物陪伴。
他是名副其实的动物之王，能管理指挥所有的动物。但他好像缺少点什么，好像少一个能跟他搭配的。
他自己有点孤独，虽然他被周围的一群动物包围着。
但这个能跟他搭配的该是什么样的呢，能跟他对话吗？能都和他谈心吗？亚当都不知道，他只觉得缺少些什么。
有些需要在你看到别人拥有而自己缺乏时的时候，才能真正明白自己的需要。一个心里没有平安的人，当他真的发现基督徒心里有真正（zhenzheng）平安的时候，
他就会明白自己心里需要同样的平安。
当时的亚当周围没有其他的人，他无法具体地知道自己想要什么，需要得到指点。
神完全知道亚当的需要，也把亚当的需要指给他看。
神精心策划了一个场面，让亚当自己去感受自己的需要。当神把飞鸟走兽一对一对带到亚当面前的时候，亚当按着每个动物的性情为它们起名字，
当亚当看着这些动物一对一对经过的时候，亚当为他们起名字的同时，他心里一定有些痒痒的：“为什么只有我是孤家寡人呢？”。等所有的动物经过后，亚当肯定有些失落，
他找不到一个他的同类，更别说遇到一个配偶。在这个经历中，亚当深深地知道自己的缺乏。

引申开来，当神所爱的人沉迷在世界，不明白最大的需要是生命，离开那唯一能够满足我们需要的神，这个时候，神透过各种事情，环境让人知道自己的需要，就像神把飞鸟走兽带了亚当面前一样。如果我们还不醒悟，神就用苦难的杖把我们从沉睡中敲醒，好让人知道自己需要神。

我们再看看神怎么满足亚当的需要

** 神满足人的需要
亚当睡了，神就用亚当的肋骨造了一个女（nu）人。
有的神学家说这里的睡，是一种意识清（qing）醒（xing）的状态，只是没有感觉。有点像全身麻醉，无痛，但知道自己身上的切割。当时的人没有麻醉的概念，没法用麻醉这个词来表达。我个人倾向这个看法。神把造夏娃的经历通过圣经启示我们，让我们的益处，对待自己的妻子要想对待骨中的骨一样。如果要把最大的益处带给亚当，我想神会让亚当亲眼看见，自已体验夏娃是从他的肋骨出来的。当时的亚当有点像剖（pou）腹产的母亲，感受到自己身上的肉被割开。人间最伟大的母爱，是因为母亲自已体验到孩子是从自己身体里出来的。

亚当沉（chen）睡中起来的时候，看到对面站着的一个人，是从自己肋骨里出来的，而且和自己正好互补，亚当发出惊叹，他用很朴实的话讲出了夏娃的来由，“她是我骨中的骨，肉中的肉”。
我们在对表达对配偶的情感的时候，常常会说：“你是的心上人”。听起来很感动人，仔细一想很多时候他不是你的心上人。工作的时候心被工作所占据，空闲的时候心被
微信占据，带孩子的时候心被焦虑所占据，看到自己的日子没别人好过的时候心被忧虑（lv）占据，生病的时候被恐惧占据，留给配偶的空间几经很少了。
配偶在丈夫心中的位置就像家里的厨房，位置不大，平时不去，只有在肚子饿了的时候去那里找点吃的。
但亚当用更客观的描述表达了他对夏娃的认识，他没有说我们常说的那种违心话。这种认识让亚当爱夏娃就像爱自己一样。我们弟兄们，要换个角度来认识妻子。她是我骨中的骨，肉中的肉；她是我的一部分。

    神在创造飞鸟（niao）走兽的时候，都是一下子就成双成对地造好了。但在造人的时候，并没有直接就造一对。而是先造一个男人，然后说“那人独居不好，我要为他造一个配偶”，再为他造一个配偶。为什么不简单、直接了当地造一对呢？何必这么周折地从男人的肋骨造一个女人。圣经没有讲神为什么这么做。当我带着这个问题思考神创造女人的过程，让我对神的爱有更多的认识。


如果神同时造亚当夏娃，亚当就不知道什么是孤独。如果神用尘土造夏娃，而不是用亚当的肋骨，亚当就会把夏娃完全看做一个独立的个体，而不是他身体的一部分。经历了孤独的亚当，看到从自己出来的夏娃时，他懂得珍惜。
世人眼中的夫妻，就是两个独立的个体，因着婚姻而绑在一起。在亚当眼里，在我们信徒眼里，夫妻本来就是一体的。

我们生活的堕落的时代，夫妻之间有很多不和谐的地方。这时我们要想想起初的时候，丈夫妻子虽然是两个不同的个体，但本来都是从一个个体出来的。夫妻是一同承受生命之恩的。

我在预备讲章的时候，有机会重新思考我跟太太之间的关系。从前我看她的时候，她是一个独立的人。现在我看到她的时候，就会想到我的肋骨。
    
** 神设计夫妻关系
   24：“因此，人要离开父母与妻子联合，二人成为一体”

这个过程建立了一个全新的小家庭，虽然不同于父家，但并没有切断与父家的联系。在圣经世界中，小家庭和大家庭住得很近，互相依赖。但丈夫要在心智上独立，并且在事情的优先次序上，要首先考虑妻子，再考虑父家。在这一点上，据我的观察，好像弟兄做的比较好。姐妹成家后，很长时间都把娘（niang）家的优先次序摆在丈夫的前面。可能因为亚当亲眼看到夏娃出自自己的肋骨，而夏娃没有亲眼见过。但是这里神告诉我们，夫妻二人成为一体，所以次序上夫妻的关系要先于父家，娘（niang）家。同时对于做父母的，当孩子长大成家了，父母不再是孩子心中分量最重的，他们以后要成立自己的小家。

二人成为一体，是人间最亲密，最重要的关系。夫妻同心是世人所羡慕的。
但是，夫妻二人也要同时行在神的旨意当中。第三章讲到的亚当夏娃一起背叛神。新约中的亚纳尼亚和撒非喇同心欺哄圣灵。都是神给我们的教训。
当一方有悖于圣经教导的时候，另一方就需要带领他回到圣经的原则。而不是因着爱他就一起离开神。
因着爱配偶而离开神，那不是真爱，因为离开神就是离开了生命。真爱是把他带到神的面前，好让他得生命。

神设计的婚姻是很美，我们都想进入婚姻。
但中国的离婚率持续上升，最近发布的离婚率数据中，黑龙江63%，天津（jin）62%，上海49%，北京48%。
离婚的原因很复杂，我们就看看工作对婚姻的影响。(PPT下一页) 这些职业有什么相似点？都是高薪行业。现在大学生最好就业，薪水最高的行业就是IT，但这个行业也是出离婚重灾区。
撒旦用重金购买我们的灵魂，诱惑我们的全身心在工作中服侍这个世界。
当你因着工作繁忙而没有时间跟配偶心连心地交流的时候，配偶一方面因着沟通的缺乏而埋怨，一方面因着你拼命赚钱带来的经济效益而暗自高兴。
结果就是配偶因着夫妻关系在情感上的冷谈而受伤，同时因着金钱的积累夫妻一同打造金牛犊。此时你会发现维系夫妻关系的支柱是玛门，而不是神赐下的合一。

神是赐安息的神，在工作一段时间之后神让我们安息。所以每周里都应当安排时间，从工作中安息。
但这个世界改变了工作的性质，让工作成为我们的重担。有多少人回到家里还想着工作上的事？
当你想着工作时，配偶明白你的心不在家里，不在配偶身上，两人之间的沟通就有障碍，就会伤害婚姻关系。我以前回家忙工作的时候，妻子跟我说话，我想搭理也没有精力搭理。要是小孩跟我说话，回话就是：“爸爸在忙，等会再说”，这个还是算客气的。
在婚姻里，妻子是丈夫骨中的骨，是互补帮补的关系，当你受伤的时候，对方会安慰，帮扶你，永不离开你。
在工作中，公司和员工之间就是一个互相利用的关系。员工发挥不了价值，公司就开除。员工觉得自己不受重视，薪水不够理想就跳槽。
因为薪水高，华为成为一个令人想往的公司。每年吸引清华北大无数的高材生。
有个人，他叫魏延政，北京大学计算机本科，新加坡工程硕士，英国南安普顿大学博士，2006年任华为无线营销部总裁助理。
2011年2月得了癌症，2013年6月6日是他的生日，也是他最难受的一天。
这一天，华为给了他一个生日大礼包后，还通知他签离职协议。
对于公司，他说：“在我癌症截肢后最无助的时候，500强给我踹了最狠一脚，终止合同，人飘荡在半空！”他感叹人走茶凉。
对于妻子，他说：“患癌后，老婆一直鼓励、支持着我，从没有嫌弃过我！”


工作是神所设立的，我们在工作中服侍神，荣耀神的时候,信主的配偶也会为你的工作向神感恩，加深夫妻的感情。
娇红在家里服侍神，当她周五晚上辛苦为弟兄姐妹准备晚饭的时候，炳杞看着就很开心。
媛媛在学校带人信主，李冬就特别为她骄傲。


* 总结
神知道我们的需要，也用最合适的方式成全我们的需要。神预备了完美的婚姻关系，夫妻二人应当同心合一地敬拜神。

求神赐下智慧和恩典，保守我们的工作，引导夫妻关系，保护我们不让亲子关系损害夫妻关系，同时也不要让夫妻关系妨碍跟神的亲近。

伊甸园虽然消失了，但神为我们预备了更美的乐园。我们的盼望就是等候主的再来，等候新天新地。
最后我们看一段视频后结束。在万国万民都归主之后，主必快来。





