yy
* 上帝造人
* 上帝为人预备环境

** 上帝为人预备住所
** 上帝为人预备工作
上帝持续在做工。主耶稣说天父做工直到如今。人也需要做工。第5节：野地还没有草木，田间的菜蔬还没有长起来，因为耶和华神还没有降雨在地上，也没有人耕（geng）地。这节经文告诉我们上帝选择了和人同工的方式来治理这地，为什么田间没有菜蔬，一方面是神没有降雨，另一方面是没有人耕地。只有在神人同工的时候，才会有收成 。我以前以为工作就是养家糊口的途径，后来发现工作也是神的呼召。神透过基督徒的工作来治理这个世界，借着基督徒的工作显出神的荣耀。现在我们所享受的很多便利，都是基督徒做工的结果。医院，福利院，孤儿院，姐妹们不用裹小脚，如果追溯他们的来历，就会看到基督徒开拓性的工作。工作要按着神的旨意治理这地。工作本身没有贵贱之分，世人有脑力劳动和体力劳动的贵贱之分，但圣经并没有差异化对待。神造人的时候，使用尘土造人，吹气在人的鼻孔里， 都是体力劳动的标志。主耶稣在世上的时候出身也是木匠。工作的目的是治理这里，而不是在工作中找到自己的偶像。
** 上帝对人的诫命
* 上帝为人预备配偶

** 上帝知道人的需要
男人
人在寻求终极的意义，上帝给出答案。当人沉迷在世界中的时候，上帝透过各种事情，环境让人知道自己的需要。
*** 人不知道自己的需要
 亚当是第一个被造的人，他

 神就是爱。
**** 有没有喜欢养狗的？姐妹喜欢养狗。
人并不知道自己需要什么，他的需要都是来自于对周围环境的反应。

我需要一个被世人赞许的孩子。周围的孩子在学画画，所以我家的孩子要学画画；周围的孩子在学钢琴，所以我家的还在要学刚请；周围的孩子在学奥数，所以我家的还在要学奥数；周围的孩子在学编程，所以我家的孩子好学编程。这些知识不是不好，但都是表面的东西，不是人深处的需要。
我需要一个舒适的房子，所以长时间租房子后就想要一间自己的房子，再后来就想要大点的房子，再后来就要电梯房，别墅了。

当你想要的都心想事成之后，人生就失去了方向，甚至失去生活的意义。我读大学的时候，有一个热线电话的主此人，很了不起，有人哭哭滴滴，要死要活的打进电话，被他一劝解，就开开心心的离开。他的事业做得如日中天，但在我大学毕业之前，他就自杀了，因为他得到了想要的东西后，就没有了人生的目标。

亚当跟各种飞禽走兽打交道，他觉得自己需要一个配偶，但并不知道是怎样的配偶。亚当是个聪明能忍耐的人，当他环顾四周，找不到一个满足他的需要，找不到合适的配偶的时候，他忍耐地等候神给他预备。他没有在飞禽走兽中挑一个最时髦最漂亮的。
** 上帝满足人的需要

只有上帝知道人最深的需要，只有上帝能满足人最深处的需要。我们在为儿女打算、计划的时候，不要代替了上帝。在这个知识就是力量的时代，不要忘记敬畏耶和华才是智慧的开端。
*** 上帝没有直接造成一对夫妻，而是先造亚当。
    
** 配偶之间的关系
*** 秩序
*** 爱的关系
