* 上帝造人
* 上帝为人预备环境

** 上帝为人预备住所
** 上帝为人预备工作
上帝持续在做工。主耶稣说天父做工直到如今。人也需要做工。我以前以为工作就是养家糊口的途径，后来发现工作也是神的呼召。在英文中，职业也是天命，神召的意思。神透过基督徒的工作来治理这个世界，借着基督徒的工作显出神的荣耀。现在我们所享受的很多便利，都是基督徒做工的结果。医院，福利院，孤儿院，姐妹们不用裹小脚，如果追溯他们的来历，就会看到基督徒开拓性的工作。
当我们按着神的旨意做工后，就可以成为传福音的机会。历代信徒做工带出来的产物都可以成为传福音的切入点，红十字会，医院，大学都打上了基督的烙印，成为神荣耀的见证。

工作要按着神的旨意治理这地。工作本身没有贵贱之分，世人有脑力劳动和体力劳动的贵贱之分，但圣经并没有差异化对待。神造人的时候，使用尘土造人，吹气在人的鼻孔里， 都是体力劳动的标志。主耶稣在世上的时候出身也是木匠。工作的目的是治理这里，而不是在工作中找到自己的偶像。
** 上帝对人的诫命
 16节：“耶和华神吩咐他说：‘园中各样树上的果子，你可以随意吃，只是分别善恶树上的果子，你不可吃，因为你吃的日子必定死’”
神为人预备了一个伊甸园，预备了丰盛的食物，园中各样树上的果子，你可以随意吃。在这里没有缺乏，有的是神丰丰富富的供应。唯独一个树上的果子，不可以吃。吃的日子必定死。这不是说没有堕落之前的亚当不会死。因为只有神是独一不死的。亚当犯罪之前也会死，如果他不吃生命树上的果子的话。3：22中说：“现在恐怕他伸手又摘生命树的果吃，就永远活着。”，所以为了避免他永远活着，神就把他们赶出了伊甸园。因着亚当一人犯罪的缘故，罪就入了世界，人就被赶出了伊甸园，远离了生命树，再也得不到生命树上的果子，导致人最终的死亡。

因着亚当犯罪的缘故，伊甸园已经成为历史，成为挥之不去的回忆，那是人类美好的家乡。我们现在所处的环境，不管怎么改造，也不能让人满足。每个人都有自己心目中的伊甸园。
因着主耶稣的救赎，让我们这本离开伊甸园的人，可以重新回到更美的乐园。在路23：43中，耶稣对那位有信心的强盗说，“我实在告诉你，今日你要同我在乐园了”。
因着对圣灵的顺从，让我们这些离开生命树的人，有一天可以再得到生命树的果子。在启示录中2：7，圣灵向众教会所说的话，凡有耳的，就应当听。得胜的，我必将神乐园中生命树的果子赐给他吃。
* 上帝为人预备配偶

** 上帝知道人的需要
男人
人在寻求终极的意义，上帝给出答案。当人沉迷在世界中的时候，上帝透过各种事情，环境让人知道自己的需要。
*** 人不知道自己的需要
 亚当是第一个被造的人，他
亚当知道自己有需要，需要有一位能帮助他的。但他不知道帮助他的是什么样的。

我们时常觉得生命中有些缺憾的地方，因着这些缺憾对人生就不满意。但到底缺什么，自己也不是很清楚。就像亚当确实以为帮助者一样，但亚当不知道帮助者到底该是什么样子的。
 神就是爱。
**** 有没有喜欢养狗的？姐妹喜欢养狗。
人并不知道自己需要什么，他的需要都是来自于对周围环境的反应。

我需要一个被世人赞许的孩子。周围的孩子在学画画，所以我家的孩子要学画画；周围的孩子在学钢琴，所以我家的还在要学刚请；周围的孩子在学奥数，所以我家的还在要学奥数；周围的孩子在学编程，所以我家的孩子好学编程。这些知识不是不好，但都是表面的东西，不是人深处的需要。
我需要一个舒适的房子，所以长时间租房子后就想要一间自己的房子，再后来就想要大点的房子，再后来就要电梯房，别墅了。

当你想要的都心想事成之后，人生就失去了方向，甚至失去生活的意义。我读大学的时候，有一个热线电话的主持人，很了不起，有人哭哭滴滴，要死要活的打进电话，被他一劝解，就开开心心的离开。他的事业做得如日中天，但在我大学毕业之前，他就自杀了，因为他得到了想要的东西后，就没有了人生的目标。

亚当跟各种飞禽走兽打交道，他觉得自己需要一个配偶，但并不知道是怎样的配偶。亚当是个聪明能忍耐的人，当他环顾四周，找不到一个满足他的需要，找不到合适的配偶的时候，他忍耐地等候神给他预备。他没有在飞禽走兽中挑一个最时髦最漂亮的。
** 上帝满足人的需要

只有上帝知道人最深的需要，只有上帝能满足人最深处的需要。我们在为儿女打算、计划的时候，不要代替了上帝。在这个知识就是力量的时代，不要忘记敬畏耶和华才是智慧的开端。
*** 上帝没有直接造成一对夫妻，而是先造亚当。
    神在创造飞鸟（niao）走兽的时候，都是一下子就成双成对地造好了。但在造人的时候，并没有直接就造一对。而是先造一个男人，然后说“那人独居不好，我要为他造一个配偶”，再为他造一个配偶。为什么不简单、直接了当地造一对呢？何必这么周折地从男人的肋骨造一个女人。圣经没有讲神为什么这么做。当我带着这个问题思考神创造女人的过程，让我对神的爱有更多的认识。如果刚开始的时候，神用尘土造亚当，也造夏娃，亚当夏娃也能成为配偶。

如果亚当从来不知道什么是孤独，从来没有体会到他需要一个帮助者，他就不会体会到配偶对他的重要，也不懂得珍惜。

21-23节：”耶和华神使他沉睡，他就睡了；于是取下他的一条肋骨，又把肉合起来。耶和华神就用那人身上所取的肋骨造成一个女人，领（ling）她到那人跟前。那人说：‘这是我骨中的骨，肉中的肉，可以称（cheng）她为女人’，因为她是从男人身上取出来的“。这是世上第一例的无痛全麻外科手术。虽然亚当沉睡，但他意识还是清醒，知道发生在他身上的外科手术，所以当他看到夏娃的时候，情不自禁地说：”这是我骨中的骨，肉中的肉”。

神没有用尘土造夏娃，而是用亚当的肋骨造夏娃。向我们传递什么意思呢？我想是要我们对夫妻关系有更深的认识。如果神用尘土（chen）造夏娃，亚当看到夏娃的时候，也会很满足，也许会说这是我的心上人。但亚当看到从他自己的肋骨造出来的夏娃的时候，他很朴实地惊叹：”这是我骨中的骨，肉中的肉“。这里不仅仅是世人眼中的夫妻，两个独立的个体一同生活而已。而是本来就是一体的人，

亚当夏娃是夫妻，夏娃也是亚当的骨肉。
    
我们生活的堕落的时代，夫妻之间有很多不和谐的地方。这时我们要想想起初的时候，丈夫妻子虽然是两个不同的个体，但本来都是从一个个体出来的。夫妻是一同承受生命之恩的。

上帝把夏娃带到亚当面前，成为人类婚姻的基础，一男（nan）一女（nv），一夫一妻，一生一世。神为亚当造了一个夏娃，没有造多个。好东西，多了之后就不一定好了。珍惜上帝为你预备的另一半，为他像上帝感恩。
    
** 配偶之间的关系
   24：“因此，人要离开父母与妻子联合，二人成为一体”
这个过程建立了一个全新的小家庭，虽然不同于父家，但并没有切断与父家的联系。在圣经世界中，小家庭和大家庭住得很近，互相依赖。但丈夫要在心智上独立，并且在事情的优先次序上，要首先考虑妻子，再考虑父家。在这一点上，据我的观察，好像弟兄做的比较好。姐妹成家后，很长时间都把娘（niang）家的事优先于丈夫。可能因为亚当亲眼看到夏娃出自自己的肋骨，而夏娃没有亲眼见过。但是这里神告诉我们，夫妻二人成为一体，所以次序上夫妻的关系要先于父家，娘（niang）家。同时对于做父母的，大孩子长大成家了，要知道父母不再是孩子心中分量最重的那一位。
*** 秩序
*** 爱的关系
