
* 上帝创造第一个人
  
** 上帝造人的背景
5节：野地还没有草木，田间的菜蔬还没有长起来，因为耶和华神还没有降雨在地上，也没有人耕（geng）种。
第4节经文直到第24节经文还是讲述第6天的创造，但是补充了更丰富的细节。弟兄姐妹还记得神在哪一天造的植物吗？是在第三天。
创1：12，于是地发生了青草和结种子的菜蔬、各从其类；并结果子的树木、各从其类，果子都包着核。上帝看着是好的。
但2：5节讲的是第六天的事。经文说野地还没有草木，田间的菜蔬还没有长起来，给我们什么印象？是不是很荒凉，一点都不好？
我们人都没觉得好，上帝更不会觉得好。但在创世第三天，当上帝创造了植物之后，上帝说是好的，第三天结束的时候看到的是花草树木，果实累累，一幅生机勃勃、欣欣向荣的图画。
为什么第六天，这野地反而荒凉了呢？是不是矛盾了？不信主的人看圣经发现到处都是漏洞。我们相信的人完全相信圣经没有一点错误，但怎么解释看似矛盾的经文呢？
原因就是： 2：5说的野地，在希伯来原文中指可以表示全地，干地，也可以表示一个特定地方。
如果讲的是全地，就直接和第一章第三天的创造矛盾了，所以应当是一个特定的地方。
这样看来第三天创造的植物，它们生长的范围是整个地球，是个大范围的宏观描述，而创2：5讲的是局部微观的角度。
结合第三天创造的，和第六天开头时候野地的景象，给我们展现的一幅图画是：真个大地总体上看起来蓝天白云，鸟语花香，但有一块野地，光秃秃，没有生机。
就好像从太空看地球，真个地球看起来很美，大部分都是绿的，被森（sen）林或者海水覆盖，但撒哈拉大沙漠那个地方看起来就很荒凉。
为什么这野块地方很荒凉呢？经文说出来原因：因为耶和华神还没有降雨在地上，也没有人耕（geng）种。不是神没有能力把这块地造得美妙绝伦，而是神特意留下一块试验田。
在这个试验田里，只有神和人同时做工才有好的结果。只有神降下雨，人耕地后，才会长出草木，菜蔬。在神造人之前，神对人就有期待，期待他来耕种。
全能的神完全可以自己包办所有的事情，在不需要人的情况下，就使菜蔬长起来。但神选择了与人同工，在还没有造你我之前，就已经选择了与你我同工。
这块野地神如果不降雨，人再怎么信靠耕种也是枉然劳力。所以人要靠着神降雨，然后再耕种就有丰收的果实，让做工的的工价，得赏赐。

因着神降的雨水，我们要向祂感恩。不可忘记祂的一切恩惠。我们是一群常常忘恩的人，因为不知道这雨水是神降下的，以为是自然而然的。
林前3：6-7，我栽种了，亚波罗浇灌了，惟有神叫他生长。可见栽种的算不得什么，浇灌的算不得什么，只在那叫他生长的神。
那些看似自然而然的背后，都有神的作为。我们努力学习，就可以考个好的大学，看似自然而然，但在学业有成的时候，当纪念神背后的作为，因为不是每一个努（nu）力的人都成功了。
当你比周围的人有远见，工作事业一切都顺利，当纪念神背后的作为，因为神给你这样的远见。

我们每位信主的，神已经给我们降下不同的雨水，我们要在不同的田地里耕种。
我们这里有帮子女带孩子的老年弟兄姐妹，神给的田地就是孙子，孙女。做父母的，你的孩子就是你的田地。上班的，公司就是你的田地。
自由自业者，你的职业也是你的田地。我们这老年弟兄姐妹很多，在教养孩子上，你们比年轻的父母有优势：有充足的时间陪伴孩子。
如果能利用这段时间，把福音传给孙子孙女，那就是拯救一个灵魂，在神眼里是极为宝贵的。
年轻的父母很希望自己的小孩能多认字，老年弟兄姐妹可以跟孙辈一起读圣经，一方面能让孩子明白神的话，同样也能让小孩多识字，也许因为
孩子认字的缘故，年轻的父母就不反对了。

** 上帝创造亚当
  耶和华神用地上的尘（chen）土造人，将生气吹在他鼻孔里，他就成了有灵的活人。
圣经告诉我们人的来龙去脉。这一节经文告诉我们人是怎么来的。圣经其他经文还告诉我们关于人的几个重大问题。
 比如人活着是为了什么？荣耀神。人为什么会死？因为罪。死后会怎么样？死后有审判，要么复活得生，要么复活定罪。
只有圣经对人的存在和意义给出了完整的答案。250年前的进化论看起来回答了生命之谜，其实他们是在走一条2000多年前的老路，
诗篇14：1， 愚顽人心里说：“没有神”。如果进化论想解释人的起源，其实就是那心里说没有神的人。按照适者生存的观点，
一个生命越来越适应环境，他理当一代比一代活得长。按着使者生存的推论，生命的进化目标就是长生不死。但圣经说罪的代价就是死。
因着罪进入世界，死就临到众人。我们看到的实际情况是，人的寿命并没有什么提高，摩西活到120岁，现在很少看到人活到120。

我们都是神所造的，都是亚当的后裔。各色人种，土著（zhu）人，野蛮人，食人族的人，他们有一样的骨骼肌肉结构，一样的心跳，
如果是同样的医疗条件，营养状况，寿命也是一样的，都是十月怀胎。不同种族的人通婚一样能生下孩子。
表明所有的人都是一个物种，更是同一位祖先亚当的后裔。

神造田地万物时，说有就有，命立就立，有点像在做脑力劳动，动口不动手。但是在造一个不到两米的人的时候，经文的意思看起来是
是在做体力劳动。首先用地上的尘土造人，造人的“造” 这个词，描述的画面就是一个陶（tao）匠用泥土塑造器皿的画面，用手在捏泥土。
吃气在人鼻孔里，是用嘴吹起的一个动作。当然这些都是拟人化的描述，因为神是个灵，没有我们这样的身体。

====================
      看视频(宇宙和地球)
====================

神是何等的地爱人啊，他造我们用了高规格的方式，不同于其他的万物。神造的宇宙这么大，而人的眼光盯着的就是一个小小的自我，一个
躺在地上不到2平方米的一个存在。愿我们因着神的慈爱和伟大就不再只顾自己。

** 上帝为人预备住所
创2：8 耶和华神在东方的伊甸立了一个园子，把所造的人安置在那里。
我们每个人都想往一个优美的住处，安静美丽环境。租房的想要一个自己的房子。多层的想要个高层。高层的想要个别墅。别墅的想要个山庄。
但是神所预备的比人能够想到的更美，是伊甸园。那是比巴比伦空中花园还美的地方。世界上再美的花园，都不会有伊甸园那么美。那里各样的树
能悦人的眼目，上面结满了各样的果子。不打农药，不用化肥，没有害虫，水果没有虫眼。
而且园子里气候适宜，应该是四季如春的环境，因为当年的亚当夏娃赤身露（lu）体，都没有觉得冷。
相信他们也不是因为热而不穿衣服，而是处在一种自然舒适的环境中，不穿衣服的时候，既不炎热也不寒冷。
更为美好的是园子中间的那棵生命树，能延长人的寿命。这个是世人梦寐以求但靠人自己无论如何也得不到的。

在这个地方还有四条河，现在还在的有幼发拉底和底格里斯河。其他2条河流已经干涸了。按着经文记载，伊甸园在4条河的交界处。
幼发拉底河跟底格里斯河在两个地方汇合，由此推断伊甸园的位置大概在地图上的这两个位置（出示地图）。
** 上帝为人预备工作
创2：15 耶和华神将那人安置在伊甸园，使他修理看守。
修理就是做园丁，看守就是当保安。神创造我们的时候，给了我们做工的需要。工作不仅仅是养家糊口的途径，更是神的呼召。在英文中，职业也是天命，神召的意思。
神透过基督徒的工作来治理这个世界，借着基督徒的工作显出神的荣耀。现在我们所享受的很多便利，都是基督徒做工的结果。
医院，福利院，孤儿院，姐妹们不用裹小脚，如果追溯他们的来历，就会看到基督徒开拓性的工作。
当我们按着神的旨意做工后，就可以成为传福音的机会。历代信徒做工带出来的产物都可以成为传福音的切入点，红十字会，医院，大学都打上了基督的烙印，成为神荣耀的见证。

工作要按着神的旨意治理这地。工作本身没有贵贱之分，世人有脑力劳动和体力劳动的贵贱之分，但圣经并没有差异化对待。神造人的时候，使用尘土造人，吹气在人的鼻孔里， 都是体力劳动的标志。主耶稣在世上的时候出身也是木匠。对待工作，一方面不能当做一个负担，同时不能让工作成为自己的偶像。
因为工作是神的呼召，在上班的时候我们可以向神祷告，求神给智慧和能力做好当天的工作。
** 上帝对人的诫命
 16节：“耶和华神吩咐他说：‘园中各样树上的果子，你可以随意吃，只是分别善恶树上的果子，你不可吃，因为你吃的日子必定死’”
神为人预备了一个伊甸园，预备了丰盛的食物，园中各样树上的果子，你可以随意吃。在这里没有缺乏，有的是神丰丰富富的供应。唯独一个树上的果子，不可以吃。吃的日子必定死。这不是说没有堕落之前的亚当不会死。因为只有神是独一不死的。亚当犯罪之前也会死，如果他不吃生命树上的果子的话。3：22中说：“现在恐怕他伸手又摘生命树的果吃，就永远活着。”，所以为了避免他永远活着，神就把他们赶出了伊甸园。因着亚当一人犯罪的缘故，罪就入了世界，人就被赶出了伊甸园，远离了生命树，再也得不到生命树上的果子，导致人最终的死亡。

因着亚当犯罪的缘故，伊甸园已经成为历史，成为挥之不去的回忆，那是人类美好的家乡。我们现在所处的环境，不管怎么改造，也不能让人满足，因为我们没法除掉这个世上的罪。每个人都有自己心目中的伊甸园。
因着主耶稣的救赎，让我们这本离开伊甸园的人，可以重新回到更美的乐园。在路23：43中，耶稣对那位有信心的强盗说，“我实在告诉你，今日你要同我在乐园了”。
因着对圣灵的顺从，让我们这些离开生命树的人，有一天可以再得到生命树的果子。在启示录中2：7，圣灵向众教会所说的话，凡有耳的，就应当听。得胜的，我必将神乐园中生命树的果子赐给他吃。
* 上帝为人预备配偶
人生活中好的环境中还不够，还需要有一个配偶。
神在第六天造好了亚当后，神说“那人独居不好”，这是创世过程中，唯一一次被神称为不好的地方。但在第六天结束前，圣经说：神看着一切所造的都甚好。
因着什么缘故导致不好到甚好的转变呢？是因着夏娃的被造。
同时圣经用一节经文讲述亚当的被造，而用六节经文讲述夏娃的被造。由此可见神很重视女性。圣经是古代文化中唯一一个重视女性的书卷。
我们从三个方面查考神为人预备配偶这件事。
** 上帝知道人的需要
人是上帝创造的，上帝知道人的一切需要。但人不一定知道自己的需要。亚当在伊甸园中有各种水果为食物，有各种飞鸟（niao）走兽做朋友，但他好像缺少点什么，好像少一个配偶来帮助他。
但这个配偶该是什么样的呢，是一个宠物吗？这个配偶能跟他对话吗？能都和它谈心吗？是他的主人还是他的仆人？亚当都不知道，他只觉得需要一个配偶。
亚当有神赐下的智慧和聪明，当神把飞鸟走兽一个一个带到亚当面前的时候，亚当按着每个动物的性情为它们起名字，但亚当在这些动物里面找不到一个能满足他需要的。
人在寻求终极的意义，上帝给出答案。当人沉迷在世界中的时候，上帝透过各种事情，环境让人知道自己的需要。

 亚当是第一个被造的人，他
亚当知道自己有需要，需要有一位能帮助他的。但他不知道帮助他的是什么样的。

我们时常觉得生命中有些缺憾的地方，因着这些缺憾对人生就不满意。但到底缺什么，自己也不是很清楚。就像亚当确实以为帮助者一样，但亚当不知道帮助者到底该是什么样子的。
 神就是爱。
**** 有没有喜欢养狗的？姐妹喜欢养狗。
人并不知道自己需要什么，他的需要都是来自于对周围环境的反应。

我需要一个被世人赞许的孩子。周围的孩子在学画画，所以我家的孩子要学画画；周围的孩子在学钢琴，所以我家的还在要学刚请；周围的孩子在学奥数，所以我家的还在要学奥数；周围的孩子在学编程，所以我家的孩子好学编程。这些知识不是不好，但都是表面的东西，不是人深处的需要。
我需要一个舒适的房子，所以长时间租房子后就想要一间自己的房子，再后来就想要大点的房子，再后来就要电梯房，别墅了。

当你想要的都心想事成之后，人生就失去了方向，甚至失去生活的意义。我读大学的时候，有一个热线电话的主持人，很了不起，有人哭哭滴滴，要死要活的打进电话，被他一劝解，就开开心心的离开。他的事业做得如日中天，但在我大学毕业之前，他就自杀了，因为他得到了想要的东西后，就没有了人生的目标。

亚当跟各种飞禽走兽打交道，他觉得自己需要一个配偶，但并不知道是怎样的配偶。亚当是个聪明能忍耐的人，当他环顾四周，找不到一个满足他的需要，找不到合适的配偶的时候，他忍耐地等候神给他预备。他没有在飞禽走兽中挑一个最时髦最漂亮的。
** 上帝满足人的需要

只有上帝知道人最深的需要，只有上帝能满足人最深处的需要。我们在为儿女打算、计划的时候，不要代替了上帝。在这个知识就是力量的时代，不要忘记敬畏耶和华才是智慧的开端。
*** 上帝没有直接造成一对夫妻，而是先造亚当。
    神在创造飞鸟（niao）走兽的时候，都是一下子就成双成对地造好了。但在造人的时候，并没有直接就造一对。而是先造一个男人，然后说“那人独居不好，我要为他造一个配偶”，再为他造一个配偶。为什么不简单、直接了当地造一对呢？何必这么周折地从男人的肋骨造一个女人。圣经没有讲神为什么这么做。当我带着这个问题思考神创造女人的过程，让我对神的爱有更多的认识。如果刚开始的时候，神用尘土造亚当，也造夏娃，亚当夏娃也能成为配偶。

如果亚当从来不知道什么是孤独，从来没有体会到他需要一个帮助者，他就不会体会到配偶对他的重要，也不懂得珍惜。

21-23节：”耶和华神使他沉睡，他就睡了；于是取下他的一条肋骨，又把肉合起来。耶和华神就用那人身上所取的肋骨造成一个女人，领（ling）她到那人跟前。那人说：‘这是我骨中的骨，肉中的肉，可以称（cheng）她为女人’，因为她是从男人身上取出来的“。这是世上第一例的无痛全麻外科手术。虽然亚当沉睡，但他意识还是清醒，知道发生在他身上的外科手术，所以当他看到夏娃的时候，情不自禁地说：”这是我骨中的骨，肉中的肉”。

神没有用尘土造夏娃，而是用亚当的肋骨造夏娃。向我们传递什么意思呢？我想是要我们对夫妻关系有更深的认识。如果神用尘土（chen）造夏娃，亚当看到夏娃的时候，也会很满足，也许会说这是我的心上人。但亚当看到从他自己的肋骨造出来的夏娃的时候，他很朴实地惊叹：”这是我骨中的骨，肉中的肉“。这里不仅仅是世人眼中的夫妻，两个独立的个体一同生活而已。而是本来就是一体的人，

亚当夏娃是夫妻，夏娃也是亚当的骨肉。
    
我们生活的堕落的时代，夫妻之间有很多不和谐的地方。这时我们要想想起初的时候，丈夫妻子虽然是两个不同的个体，但本来都是从一个个体出来的。夫妻是一同承受生命之恩的。

上帝把夏娃带到亚当面前，成为人类婚姻的基础，一男（nan）一女（nv），一夫一妻，一生一世。神为亚当造了一个夏娃，没有造多个。好东西，多了之后就不一定好了。珍惜上帝为你预备的另一半，为他像上帝感恩。
    肋骨造人的故事会成为不信的人攻击的一个地方。我在读高中的时候，一个备受尊敬的物理老师在课堂上说：如果女人是用男人的一根肋骨造出来，那么女人的肋骨就应该比男人多一根，事实上男人、女人肋骨一样多，由此证明圣经不可靠。当时我们觉得他讲的很有道理。该怎么回答他们呢？如果一个父亲车祸中断了一条腿，他的后代都少一条腿么？这个不是我想出来的，是我在某个地方看到的。我们对待神的话语，要笃信不疑，假如有不明白的地方，要带着一个谦卑的态度来学习。圣经几千年来，备受攻击，到现在依然屹立不倒，因为他出自于神。
** 配偶之间的关系
   24：“因此，人要离开父母与妻子联合，二人成为一体”
这个过程建立了一个全新的小家庭，虽然不同于父家，但并没有切断与父家的联系。在圣经世界中，小家庭和大家庭住得很近，互相依赖。但丈夫要在心智上独立，并且在事情的优先次序上，要首先考虑妻子，再考虑父家。在这一点上，据我的观察，好像弟兄做的比较好。姐妹成家后，很长时间都把娘（niang）家的事优先于丈夫。可能因为亚当亲眼看到夏娃出自自己的肋骨，而夏娃没有亲眼见过。但是这里神告诉我们，夫妻二人成为一体，所以次序上夫妻的关系要先于父家，娘（niang）家。同时对于做父母的，大孩子长大成家了，要知道父母不再是孩子心中分量最重的那一位。
*** 秩序
*** 爱的关系

工作，配偶，神的慈爱。
