恩上加恩
吴其华

* 经文：加拉太书4:4-7
4:4 及至时候满足，神就差遣祂的儿子，为女人所生，且生在律法以下，

4:5 要把律法以下的人赎出来，叫我们得儿子的名分。

4:6 你们既为儿子，神就差他儿子的灵进入你们的心，呼叫：“阿爸，父”。

4:7 可见，从此以后，你不是奴(nu)仆，乃是儿子了。既是儿子，就靠着神为后嗣。

* 引言：
在出埃及记中，我们看到以色列人在埃及法老的奴役之下，因作苦工，就叹息哀求。上帝听见以色列人的哀声，就纪念他与亚伯拉罕所立的约，带领他们出埃及，离开为奴之地。第一步就是进入旷野。在旷野里以色列人就获得了自由，不再是埃及人的奴仆。他们从一个奴仆的身份成为自由人的身份，这是神所赐的恩典。但得到自由人的身份不是故事的结局，神的恩典没有在此止步。神在以色列人身上有更丰富恩典：下一步神要带领他们进入迦南美地，流着奶与蜜的佳美之地，在那里以色列人承受产业。这个故事告诉我们：以色列人向神所求的仅仅是不再做埃及的奴仆，他们的祈求神应允了；不单如此，神还赐给他们不曾想到的丰盛之地作为产业。神在我们身上的作为也超过了我们的所求所想，神是恩上加恩的神。


* 一、得永生的恩典
4:4 及至时候满足，神就差遣祂的儿子，为女人所生，且生在律法以下，
4:5（1） 要把律法以下的人赎出来
以前我们都在律法以下，被律法定罪。因为没有任何一个人没有犯过罪，世人都犯了罪。而罪的工价乃是死。若不流血，罪就不得赦免了。我们以前都是罪的奴仆，结局就是死亡。但上帝如此地爱我们，就差遣主耶稣在日期满足的时候来了，来到这个在祂眼中充满罪恶、污秽的世界。尊贵的祂从一个由尘土所造的人生出来，经历了婴孩到成人的自然生长过程。创造万有的主甘愿俯就卑微的人，为的是要和人类一样，和人类认同，让人可以认出他，听见他，触摸他。祂和我们一样生在律法以下，但祂没有罪，活出了一个完美的生命。祂在十字架上流出的宝血涂抹我们的过犯罪孽，把我们这些在律法以下的人赎出来。耶稣用祂自己的死，替我们偿还了罪的工价，使我们在神面前成为无罪的，从而把原本与神为仇的敌对关系，扭转成为与神和好的关系。使我们免了地狱的审判，赐给我们永生的恩典。想想地狱中哀苦切齿的声音，还有那不灭的火和不死的虫子，就知道天堂的宝贵了。有人说如果一个地方不是地狱，那里就是天堂了。说的一点不错。只要能脱离地狱，就再好不过了。

中东的一些国家，比如叙利亚，战火纷飞，威胁生命的恐怖分子无孔不入，每天食不果腹，危在旦夕，整个人间地狱的惨状。为了逃离人间地狱，一些人历经(jing)千(qian)辛万苦离开本地本族本乡，穿过土耳其，进入欧洲。在欧洲背井离乡，过上寄人篱下的难民生活。虽是陌生的环境，但是不再受战乱之苦，性命有了保障。这些原本生活在人间地狱的人，有幸能逃离这个悲惨的世界，进入欧洲和平的国家。对他们来说，是不是福音？可以算福音，因为他们不再有性命之忧。

这些难民知足吗？很多难民是很知足了，因为比起他故乡的水深火热中的同胞，他们已经很幸福了，虽然是寄人篱下，但好歹生命有保障，还有供给难民的口粮。我们也是一样，比起周围没有信耶稣的人，我们的结局不知道好到哪里去了，哪能不知足呢？

这些难民的状况已经有很大的改善，但是不完美。因为他们虽然有了性命的保障，可以存活下来，但这不是自己的祖国，没有归属感。他们面对新的语言，新的法律，新的习惯，新的生活模式，他们不适应。他们虽然看起来上生活在欧洲，但其实还是一个局外人。他们在欧洲靠救济得以存活，并不是欧洲的子民。

我们也是这样，如果我们仅仅满足于得救，虽然在永恒中回头看世界很庆(qing)幸（xing），因为自己没有和这个世界一起沉沦。但是不能一直往后头看世界吧，总要回过头来看前方吧，结果发现前方的事物对我们来说好陌生，就像难民看欧洲一样。


这些难民的经历跟我们的经历是不是有些相似？至少跟我的切身经历很像：


我信主后有几年的时间，认为只要能拿张天堂的门票，凭票入座，哪怕是拿个站票躲在一个角落，不至于让地狱之火够到自己，就已经心满意足啦。知足常乐嘛。那时我想有一个及格线，按照个人所作的，只要及格了，就可以顺利抵达天堂，所以我要做的就是：搞明白怎样及格，60分万岁，61分就浪费了。中国人都喜欢打擦边球，我也不例外。我以前距离天堂很遥远，希望通过自己的努力，一步一步靠近天堂，然后抵达天堂和地狱接壤的地方，再迈出一小步，终于站在天堂了。然后在世界上该干嘛就干嘛。既享受世界，又得着永生。这就是我之前的行事方式。现在回想起来，那时根本就不打算学习天堂的新事物。一幅打算在天堂寄居的心态，一幅难民的心态。虽然当时我的盼望仅仅是得救而已，然而这不是神的旨意。神有他更丰盛的恩典。

* 二、得儿子名分的恩典

4:5（2） 要把律法以下的人赎出来，叫我们得儿子的名分。

4:6 你们既为儿子，神就差他儿子的灵进入你们的心，呼叫：“阿爸，父”。

进入永生的人是蒙福的，但神赐给我们的不仅仅是永生，更是儿子的名分。这节经文告诉我们，把我们从律法以下赎出来，目的是叫我们得儿子的名分。儿子的名分是很珍（zhen）贵的。天使也有永远的生命，却没有儿子的名分。神没有把儿子的名分赐给那些没有犯罪的天使，而是赐给我们这些犯罪后被拯救，有着神形象和样式的人。约翰福音1:12 凡接待祂的，就是信祂名的人，祂就赐他们权柄，作神的儿女。从这里也可以看到，神的目的是要我们得儿子的名分。

** 儿子的名分
什么是儿子的名分？就是继承产业的资格，承受天堂的产业。但这个产业看不见，摸不着，如果属灵的眼睛没有打开，就不会重视这些产业，因为你不知道它的存在。你不重视的东西，你就不懂得珍惜，神会不会给你呢？ 如果我们不在乎救恩，就不会得到救恩。只有在我们认罪悔改，为自己灭亡的结局恐惧战兢的时候，神才会赐给我们救恩。如果我对灭亡抱着无所谓的态度，就不会悔改，当然也就得不到救恩。但令人惊叹的是，那些被拯救而不在乎儿子名分的人，神还是给他们儿子的名分。那些上好的，而我们并不知道的，慈爱的神没有留下来不给我们，祂都主动给我们了。

神所赐的超乎我们的所求所想。我们刚开始的时候只求被救赎，神却将儿子的名分给你了。我们只求在天堂有一席之地，神却在天堂为我们预备产业。 如果我们认为福音仅仅是逃脱地狱的审判，仅仅是在天堂有个落脚的地方，就还没有完全理解福音的能力，低估福音的能力和神的恩典。耶稣来，不仅仅是要叫羊得生命，而且得得更丰盛的生命。神要赐给我们的是栽在溪水旁，高大挺拔的长青树的那种生命，不是秋天秋风扫落叶之后那种枯萎的生命，那种生命看起来是活的，跟死的没什么两样，看不到生机，也没有果子。也不是主耶稣看到的那棵看起来枝繁叶茂，但不结果子的无花果。我们以后将要居住的天堂，不是收容所，不是单单为了逃避审判，更是为了承受产业，因为神已经收纳我们为儿子了。我们不是被神所收容，而是被收纳。

*** 应用：
不要把自己想象成了叙利亚的难民。我们是天国的子民，不是到天国逃难的，而是在天国做儿子的。如果你真心相信耶稣的死里复活，承认自己的罪，相信耶稣宝血救赎的果效。按圣经的应许，你就成为神的儿子。
** 神维护儿子名分稳固的方式：调教管教
神一旦赐给你儿子的名分，就不会再收回。
父子关系是世上很稳固人际关系。夫妻关系按照神的旨意应当很稳固，但令人痛心的是因为各种原因而破碎，弟兄关系因为经济冲突反目成仇，或者时间的流逝而冲淡。但父子关系是一生之久。虽然如此，我们还是会听说断绝父子关系的例子，应该说都是父亲的问题。如果孩子没教养好，导致父亲羞于认这个儿子，是这个父亲不称职。或者儿子很出色 ，父亲还是不认儿子，我们会认为这个父亲脑袋有问题。一个负责任人的父亲一定能调教一个优秀的儿子。天父更是负责的父亲，祂更能调教出一个优秀的儿子。我们看看神调教儿子的方法和智慧：

伯5:18 “因为他打破，又缠裹；他击伤，用手医治”。
何6:1 来吧，我们归向耶和华！他撕裂我们，也必医治；他打伤我们，也必缠裹。
希12:8 管教原是众子所共受的。祂管教我们是要使我们在他的圣洁上有份。
*** 应用：
如果有神那样的智慧和方法，对孩子恩威并重，调教出来的孩子品格不好都是个奇迹。
盼望做父母的能从神的智慧中学到怎样教养小孩。
王上1:6 他父亲素来没有使他忧闷，说：“你是做什么呢？”他甚俊美，生在押沙龙之后。
如果一个孩子在父母眼里可爱，更舍不得管教。这种人间的爱带来的是令人痛心的后果。
箴19:18 趁有指望,管教你的儿子,你的心不可任他死亡
撒上2:24-25 我儿阿、不可这样、我听见你们的风声不好、你们使耶和华的百姓犯了罪。
人若得罪人、有士师审判他、人若得罪耶和华、谁能为他祈求呢．然而他们还是不听父亲的话、因为耶和华想要杀他们。
以利管教儿子的时候，可以说声(sheng)情(qing)并茂，苦口婆心。一直跟他儿子讲道理。但我们知道他儿子们的结局。讲道理不是都有用的。要像神那样：先打伤，再缠裹。

** 因有儿子名分而应有的心态
我们既是儿子，就当有儿子的心态，而不是 难民的心态，不是奴仆的心态。
儿子的心态有哪几种？
*** 喜乐的心
儿子在父亲面前有个喜乐的心。当你称呼神为阿爸父的时候，心里一面是对神的敬畏，同时也是一种自豪和喜乐，因为能称呼创造主为父。你跟最伟大的那一位建立了关系。
对难民我们不能要求过高，指望他们喜乐。如果我们是难民的心态，没有喜乐不是什么意外的事。但我们如果有儿子的心态，知道自己是天国的子民，承受应许的，就理当欢喜快乐了。

作为神的儿子，在神面前得的安慰是何等的大呢？求神让我们真的知道神的伟大，从而让我们以祂为乐。罗5:11，不但如此，我们既籍着我主耶稣基督得与神和好，也就籍着他以神为乐。这里讲出了2种生命的状态，基本的一种是与神和好，更高的是以神为乐。作为神的儿子，就应该做到以神为乐。
*** 乐意的心
乐意被管教的心态：
被神管教后不要远离神，而是紧紧抓住神。

我女儿越越有个特点，当我管教她的时候，拿管教杖打她的手，疼得她哭叫起来。令我惊讶的是她跟我说：“我要抱”。我特别感动，特别自豪，紧紧地抱住她。在我看来那是她对我的一份信任，虽然她挨打了，但她知道我爱她。她来投靠我的时候，我内心是非常的开心。我们跟神之间也应该是这样：在我们犯罪的时候，就背对了神，而神在等待我们转过身来看着他，犯罪的时候，虽然还是祂的儿子，但如果不回转就是失去了从天父那里得到的喜乐和平安。当我们回转的时候，就是对神的信靠，神的心意也得到满足。

对比奴仆的心态，当主人对奴仆发怒，责罚奴仆后，奴仆会不会主动靠近主日？显然不会，奴仆的明智选择就是离主人远点。一个聪明的儿子、体贴父亲心意的儿子，在被挨打之后会主动认错，然后再投入父亲的怀抱。

* 成为神的后嗣的恩典
  4:7 可见，从此以后，你不是奴(nu)仆，乃是儿子了。既是儿子，就靠着神为后嗣。
  
 在新译本中，后半句翻译为：“既然是儿子，就靠着神承受产业了”


保罗在提到成为儿子之后，又提到承受产业。承受产业比成为儿子更进一步了。不是所有的儿子都有资格承受产业。亚伯拉罕有很多儿子，包括大儿子以实玛利，圣经上说他们没有与以撒一同承受产业，只有以撒一人独自承受产业。神对我们格外开恩，让每一位信徒都可以承受产业。西1:12，又感谢父，叫我们能与众圣徒在光明中同得基业。

** 如何得到更多产业
 翻开中国历史，可以看到很多例子:做儿子的为了得到更多产业，导致家庭不和，纷争，甚至弟兄相残，把本来应该是一个和睦同居的地方变成战场。特别是帝王之家，弟兄之间为了争夺王位，不惜杀害弟兄，手段残忍。圣经上也有例子，最为残忍的就是士师记中9章所记载的亚比米勒，他是基甸的儿子，为了抢夺治地方的治理权，凶残地杀害同父异母的七十个弟兄。

世上的儿子们为了承受父亲的产业，采用阴险毒辣的手段。人的罪性在这里没有任何遮盖地表现出来。世界的法则是通过弱肉强食来争夺产业。从一个角度看，贫穷的父母是有福的，因为他们没有产业，儿子们反而更容易相安无事。

人间的父亲留下的产业有限。即使是皇帝，他的财富如果算一算的话，虽然数字很大，但总能用个数字表示。当一个儿子从父亲多拿一份产业后，其他的儿子能分到的就少了。人间的儿子

神的儿子怎么得到更多的产业呢？是通过谦卑自己。主耶稣自己卑微，存心顺服，以至于死，且死在十字架上。祂所得的基业是最大的。我们也要学习主耶稣的顺服。


** 寻求的心
向神大大张口：
在寻求神这件事上要有心志。路加福音22:25-27，当门徒争论谁为大的时候，主耶稣并没有责备他们，而是告诉他们为大的人该怎样做，也就间接告诉他们怎样做一个在天堂为大的人。在犯罪的事上要做婴孩，但在天国的事上，要做大人，不能不思进取。要有雅各那种渴慕神的心态，神啊你得给我祝福，不然我就缠住你不放。
在世上的事要学会知足，在属灵的事上要不知足。

* 总结：
我们是神的儿子。是天国里的小主人，不是天国打工仔。不是难民，是子民。神赐给我们的事丰富丰富的产业。

林前3:21-23 所以无论是谁，都不可拿人夸口，因为万有全是你们的。或保罗，或亚波罗，或矶法，或世界，或生，或死，或现在的事，或将来的事，全是你们的。并且你们是属基督的，基督又是属神的。 



