* 引言
  游戏制作人利用人的软弱，沉(chem)溺(li)于游戏的人放纵自己的罪性。

  
* 末世的人性
  末世的日子
保罗提醒提摩太：“你该知道”。
末世的危险，不是外面的压力和逼迫，而是假敬虔。糖衣炮弹的威力胜于大炮的威力。大炮打过来，还是要隐藏避免受害，而在糖衣炮弹面前常常不打仗就投降了。
保罗在这里提到的恶基本上都是内心深处的，而不是表面的外在行为。人一生的果效都是由心发出的，圣经教导我们保守我们的心胜过保守一切。作为神的百姓，因着相信神的话，默想神的律法，让我们比世人更有洞察力，能透过外在的表象洞察内心的问题。有一次我家妹妹对姐姐闹脾气，对姐姐大声不礼貌地说话，我听到后把妹妹叫到一边，问她你犯了什么罪，她说我对姐姐大声说话，凶她了。妹妹讲出了她的问题，但不是症结所在。我继续问她，这个是表面的问题，有没有更深地问题？她不明白，我就跟她解释，你对姐姐凶，大声跟她说话，是不是因为嫉妒她的缘故？她点头承认。我们就认罪祷告。对二天我下班回到家，问妹妹，你今天有没有犯罪得罪神的地方？她说没有，因为姐姐给我做了个好榜样，我吃说过的时候，姐姐没有到妈妈那里告状，只是跟妈妈说她也想吃水果。过了几秒钟，妹妹有跟我说，我还是犯罪了，因为姐姐吃了2个，我只吃了一个。我没有问她，她自己说出自己的问题，让我很感恩。

保罗在这里提到的罪恶清单，不单针（zhen）对假教师，而是指向末世中所有的人。
** 错位的爱 
保罗开了一个末世的罪恶清单，清单的头一个就是专顾自己，或者说专爱自己，其次是贪爱钱财，最后一个以不爱上帝结束。贪爱钱财的人必定专爱自己，专爱自己的人必定不爱上帝。保罗在提摩太前书中说：“贪财是万恶之根”，但在这个清单里保罗把贪财放在专爱自己的后面，表示贪爱钱财的背后还有更深(shen)一层(ceng)的专爱自己。如果一个人不贪爱钱财，不表明他不专爱自己。专爱自己可以表现在贪爱钱财上，也可以表现在贪爱面子，贪爱长寿，对有些人来说面子比钱财更有价值。虽然他不爱钱财，但他还是爱自己，因为面子就是他的全部。如果一个人不爱自己，他也不一定就爱上帝，他可能心灰意冷，啥都不爱，就像心理有严重疾病的人，自己都不想活下去。神对被造的人的要求是，尽心，尽性，尽力，尽意爱主你的神。罪的症结就是不爱上帝，就是保罗列在这个清单最后的总结性陈述。

我们仔细看看这些错配的爱
*** 人的爱
**** 专爱自己
     我们要区分专爱自己和爱自己。保罗不反对我们爱自己，其实他也要我们爱自己，他在以弗所书5：33节说：然而你们个人都当爱妻子，如同爱自己一样。这句话隐含着人要爱自己，否则的话，如果他像对待自己那样对待妻子，其实就是爱妻子了。所以爱自己是好的，但专爱自己就不好了。就像保罗说不要单顾自己的事，也要顾别人的是一样。
过度爱自己表现在跟人发生冲突的时候，你是否只是想找自己的损失，而没有考虑对方的损失。基督徒容易辨别这钟专爱自己。还有一种比较隐蔽：那就是一个跟别人没有直接冲突情况下的专爱自己。比如一个有意无意的动作，引发周围人的嫉妒或者失落，使其他的人落在试探之中。就像保罗说哥林多教会举行爱宴的时候，富足的吃饱了，喝醉了，但是那些贫（pin）穷的却在一旁忍饥挨饿。保罗要求那些富足的人在家里吃了再来教会，免得那些贫穷的人羞愧，实落。
人都是习惯专爱自己，因为你要爱其他人的时候，你的视角就要从自己切换到他人了，这个不是人的本性。我有次早上上班，下楼梯的时候，看到一个阿姨正在扫楼道，灰尘(chen)满天飞。赶快急急忙忙迈开大步逃走了。后来一想，我这么急急忙忙的逃走了，那个阿姨怎么想？是不是会让她觉得自己的工作并轻视呢？我虽然没有和她发生正面冲突，但她的心受到了歧视的伤害。如果我实在担心这个灰尘会伤到自己，可以回家吸一口新鲜的空气，再以正常的方式下楼，这样就不会伤害到她了。而且就算吸进几口灰尘，就真的会少活几天么？

**** 爱钱财
爱钱财是爱自己的第一个表现形式。而且爱钱财在这个社会被贴上有进取心的标签。天下熙熙皆为利来，天下攘攘皆为利往。普天下的都是为着钱财在忙碌。老祖宗知道爱财的手段不能低劣，君子爱财，取之有道。但到了现今这个时代，爱财的手段有时很恶劣，1998年的山西朔州假酒案，农民王青华用34吨甲醛加水勾兑57.5吨白酒，导致27人丧生，222人中毒，多人失明。在他们心里，能赚到钱才是王道，根本不顾及他人死活。如果说王青华是低劣的爱财手段，甲醛用的剂量太大而直接导致人死亡，眼睛失眠。那么还有很多高级版本，加入少量甲醛，不会要你的命，同时能赚到你的钱，这种例子大概就很多了。10年前的三聚氰胺奶粉，吃了不会马上要人的命，一时半会儿发现不了，这种情况就更要命了。

前一段时间我赶地铁的时候，听见后面一个人开心的说：“没人要我就要了”，我回头一看，是一个从地上捡起来50块钱。他脸上的笑容跟周围其他人脸上的那种沉闷的表情对比很明显。我能猜到他没有捡起这50块钱的时候，他的表情跟周围其他人一样，没有笑容，面无表情。但是50块钱就能改变一个人的心情，改变一个人的表情。当时让我体验了一下钱财的能力。我回头继续往前走，脑海中闪过一个念头：“应该见着有份啊”。当然我没有说出来。我更加体会了钱财的势力。

钱财的魅力实在太大了。有了钱就不会有人瞧不起。

这些爱财的手段咋一看看不出有啥问题，还觉得很有创意。我想起以前看过一篇文章，大概是讲金点子的，就是这个点子想法很有创意，很值钱，其中一个例子就是某家牙膏生产厂商，为了提高牙膏的的销量，调研用户的使用习惯，发现用户挤牙膏都是随意挤那么一下。调研得到结果，就让人想到金点子了，那就把牙膏的口子开大一点，用户刷牙的时候，就会每次用更多的牙膏，会直接导致牙膏需求增加。我当时看了这个点子后，真的很佩服这些人，只恨自己没有这种能耐。现状回过头来，就知道自己是被自己的私欲引诱了，以至于认同这些被神厌恶的事情。当我反思过往的经历的时候，神就借着这些事情让我越来越深地知道我是一个罪人，需要被救赎。当你在一个浸（jin）泡一中文化中的时候，你完全被他所塑造，很难看出其中的问题，就有借着神的话才能知道其中的邪恶和败坏。愿神给我们明亮的眼睛，认出看似正常现象中的罪恶本质，好让自己能避开陷阱。这个社会以经济挂帅，不管白猫黑猫，抓住钱财的就是好猫。人人一个心思，一个意念，怎样才能发展经济。作为基督徒，如果你真的要在主里面长进的时候，当你为着福音的缘故，放下钱财的时候，周围的人认为你的的脑袋有问题，脑子进水了。传道人面临的试探不仅仅是钱财，也有面子，被周围不信的人另眼相看，怀疑的是否是一个正常人。


/我们基督徒当怎么面对钱财的？要跳出这个世界的框框。人生如梦，钱财只在你的梦中，在这个世界中发挥它的功效，等主耶稣来了的时候，我们的梦也就醒了，钱财就结束了它的一切功能。这个梦总有梦醒时分，求神赐给我们明亮的眼睛，真知道那在天上的真实，地上的都是影儿。/

**** 爱宴乐
吃喝是正常的需要，以维持正常的生命状态。传道书2：24说，人莫强于吃喝，且在劳碌中享福，我看这也是出于神的手。正常的吃喝是神所赐的，出于神的手。神给我们这个时代极大的恩典，在上海你能吃到全世界的水果，各个国家的特产。但对吃喝的过度追求就成了爱宴乐。对吃喝的追求，在现在的时代表现得极为突出，心被口味所引导。末世的时候美食家多起来。神对我们的要求是有衣有食就当知足，过一个简朴的生活。在财主和拉撒路的故事中，财主天天奢华宴乐，死了后在阴间受苦，亚伯拉罕对他说：“你该回想你生前享过福，如今你到受苦了”。受苦也就罢了，再想想生前爱宴乐享过福，就更苦了。

我们也不希望我们的孩子们以后爱宴乐，在小时候不要坏了他们的胃口，不然以后可能会变成为一个爱宴乐的人。



*** 人的不爱
****  不爱良善

****  不爱上帝
     不爱上帝是罪的根源所在，也是人自己陷害自己的地方，因为他离开了活水的源头，为自己凿出一个破裂不能存水的池子。上帝命令我们爱祂，不是祂需要我们的爱。三位一体的神彼此相爱，彼此交通。没有污秽罪人对祂的爱，神并没有任何损失，因为祂自己是完全的，不需要外来的东西弥补什么。那神为什么命令我们爱祂？因为祂爱我们。约翰派克牧师在这一点上有很好的看见：如果你是一个无私的人，满有爱心的人，当你知道全世界有一个最好的宝藏，你会不会把其他人带到宝藏那里？当然会的，否则你就是因着自己的私心，不愿意跟人分享。神也是这样，因为神就是爱。祂乐意把最好的分享给其他的人。这个世界、宇宙、万有中最好的是什么呢？那就是神自己，因为这个缘故，神愿意把祂自己分享给其他人。而且神做事很彻底，他不但把最好的指给我们，还命令我们到最好的那位那里去，就是到神那里去。如果是人，你把宝藏指给别人就很不错了，至于别人信不信，自己看着办吧。神是怎么做的呢？希伯来1：1说，神既在古时籍着众先知多次多方的晓谕列祖，就在这个末世借着祂儿子晓谕我们。神通过各种方式吸引人归向祂。然而人还是不爱上帝，约翰福音5：40节，耶稣对以色列人说：“然而你们不肯到我这里来得生命”。
** 其他的罪
* 末世的假教师
** 假教师 v3:13
*** 敬虔的外貌
假教师有敬虔的外貌，却没有敬虔的生命。他们是披着羊皮的狼，所以保罗嘱咐提摩太远离他们。 这些人偷偷的溜进别人的家里，去勾引那些无知的妇女。假教师偷偷摸摸的行动，表明所做的不是来自于真理。
假教师没有敬虔的能力，没有道德的能力。

假教师有敬虔的外貌，表面上看很敬虔，走近了看却没有敬虔的果子。就像主耶稣咒诅的那颗无花果树，远远看去枝繁叶茂，给人带来很大的期待和盼望，走近了却发现没有期望的果子。假教师不在光明中行，而偷偷溜进别人的家，目的是去勾引人。对假教师，提摩太要躲开，也要带带领弟兄姐妹一起躲开。2：13 只是作恶的和迷惑人的，必越久越恶，欺哄人也被人欺哄。这些假教师的状况螺旋下降，越来越恶，他们用虚假的教义欺骗人，最后也那恶者撒旦利用而被欺哄。假教师的猎物是无知的妇女，这些属灵上无知妇女的特征就是被自己的私欲诱惑。当时提摩太牧羊的以弗所有很多妇女，============.拿到今天来说，重点就是那些被私欲引诱的人，不分男女了。我自己就差点儿被诱惑了。3:8, 从前雅尼和佯庇怎样抵挡摩西，这等人也怎样敌挡真道。圣经在其他的经文里没有提到雅尼和佯庇这两个人。根据传统，他们就是出埃及记中抵挡摩西的埃及术士。这些法术
*** 抵挡真道
3:8, 从前雅尼和佯庇怎样抵挡摩西，这等人也怎样敌挡真道。圣经在其他的经文里没有提到雅尼和佯庇这两个人。根据传统，他们就是出埃及记中抵挡摩西的埃及术士。这些法术
*** 他们的结局
** 受害者 
* 末世的真工人
** 顺服
   3:10 但你已经服从了我的教训、品行、志向、信心、宽容、爱心、忍耐

提摩太与保罗多年同工，跟保罗近距离的接触，使提摩太对保罗有清楚的认识，知道保罗所教训的内容，也知道保罗行事为人的品格。透过保罗的品行，提摩太知道保罗传讲的和行出来的是一致的。知道保罗在基督里所立的志向，就是要传福音，得主的喜悦（林后5：9，所以，无论是住在身内，离开身外，我们立了志向，要得主的喜悦）。知道保罗那不以福音为耻的信心，还有保罗的宽容，爱心，忍耐。 保罗生活的目标、方向都聚焦在福音上。这一切提摩太清楚明白，而且他也顺服保罗，效法保罗。末世的假教师自高自大，任意妄为，但末世的真工人不受周围环境的影响，出污泥而不染，展现出来美好顺服的品质。

** 忍受苦难
保罗第一次传道的途中路过安提阿，以哥念和路司得，在那里受到了一个又一个，越来越大的逼迫。对安提阿稍作解释，圣经提到两个安提阿，一个是宣教大本营的安提阿，位于叙利亚，另一个是这个看到的安提阿，位于彼西底。在这里讲述的逼迫、苦难都记载在使徒行传13~14章。我们简单回顾一下：在彼西底的安提阿保罗，巴拿巴被赶出城外。就前往以哥念，在那里抵挡真道的人要用石头打保罗一行人，但他们毫发无损地逃到路司得。而在路司得，他们用石头打保罗，这次真的被打着了，而且他们以为保罗被打死了，就把保罗拖到城外。

保罗在这个三个城市经历的苦难，逼迫一个比一个重，开始的时候只是赶走而已，后来就有人要用石头打他，虽然有惊无险地逃跑了，并没有受到身体的伤害，但在最后一个地方就不一样了，不但真实地受到了人身攻击，而且都快要死了。但保罗在这些逼迫中也看到主对他的保守和拯救。提后3:11后半节：在这一切的苦难中，主把我救出来。主没有让保罗免（mian）受苦难，而是先允许他经历苦难，然后把他从苦难之中救出来。神不会忘记在苦难中属神百姓，更不会忘记在苦难中神的仆人，不会任由苦难一直持续下去。就像保罗在路司得的时候，徒14:20，门徒正围着他，他就起来，走进城去。众人都以为他死了，但他却能站起来，走进城去。一个被打得快要死的人，就算是逃过一劫，也应该是遍体鳞伤，需要好好休养才能慢慢恢复。而且是被石头打的，受到的伤害肯定不是皮肉之伤，而是伤筋（jin）动骨。我们有个说法是伤筋动骨一百天，但保罗当天起来了，而且经文里没有提到有人扶他起来，也没有人扶他走，可以看到他应该是自己起来，自己走进城的。这个不能不说是一个神迹。我们在苦难中才会经历神迹，更重要的是在苦难中才能真知神是帮助我们的，才会发自肺腑地说神是帮助我的，神是拯救我的。就像保罗所说，在这一切的苦难中，主把我救出来。

保罗提到的这些遭遇提摩太没有亲身经历，但提摩太是路司得人，而且他从小是一个敬虔的人，他不会不关注信仰相关的事情。所以发生在提摩太老家逼迫保罗的暴动，提摩太就算没有亲眼看见也肯定听周围的人讲过，那时的提摩太的很年轻，对比年长的人，逼迫在年轻人心中打下的烙印更深。保罗提醒提摩太，为着信仰的缘故，提摩太心里要有预备，像保罗一样遭受逼迫和苦难。提摩太是一个胆小的人，跟我们中间大部分人一样，但保罗坚固他，告诉他最终主会实行拯救，好帮助提摩太有力量可以承受苦难。

神的百姓中，不仅仅是使徒、先知、教师们要受逼迫。保罗告诉我们所有的信徒都要受逼迫。 提后3:12，不但如此，凡立志在基督耶稣里敬虔度日的，也都要受逼迫。这句话换一个角度说，如果你不受逼迫，就你就没有在基督耶稣里立志敬虔度日。看看保罗的经历，他不认识主之前，是逼迫人的，一旦他信主之后，就开始被逼迫了。保罗在这里提醒提摩太，对前面的道路要清晰的认识，苦难在前面等待着他，但正是前方的苦难表明他是在基督里敬虔度日的人。当然我们所处的环境中不太可能碰到保罗经历的那种逼迫，我们碰到的逼迫更多来自于心灵和心理层面，逼迫表现出来的方式也不同。我们团契中有位姐妹，信主才2年时间不到，没信主前跟她丈夫闹矛盾，总是她得胜，有时还对他老公动拳头，扔凳子。后来她信主了，跟团契的人谈她的难处，说她老公奚落她，还怪罪她因为信主的缘故生意不如从前。这位姐妹不信主的时候，不受逼迫，信了主后，就受到来自不信的丈夫的逼迫。这是基督徒生命成长的一个过程， 从一个人受逼迫的状况，逼迫中的心态大概就能看出一个人的信仰程度。每一个对信仰认真负责的人，都应当反思：我为主的缘故受到过逼迫、苦难吗？

对有心服侍教会的弟兄姐妹，如果想要成为末世的真工人，就更要预备心志，为主的缘故而受苦。
** 把真道存在心里
*** 真理的源头来自于神
圣经都是神所默示的。这个“都”字表明圣经中所有的句子，所有的字都是神默示的。当然这个是指原文圣经，我们手里拿到的和合本圣经是翻译过来的，不具备原文圣经的权威，但和合本对我们普通信徒研读圣经已经足够了。如果你对真理更追求，可以去参考原文圣经。精读圣经这个软件中有个原文菜单，能查到中文圣经所对应的希腊文或希伯来文原文，还有每个原文字词的词典可供参考。神所默示的表明圣经的源头来自于神。来自于神当然很宝贵。18世纪末在英国的威尔士就有个小姑凉非常珍爱圣经。她叫马利琼斯，父亲是虔诚的基督徒，8岁时就相信耶稣，非常渴慕圣经，就定下目标要拥有一本属于自己的圣经。当时的圣经昂贵稀缺，家里又很贫（pin）穷，不得不自己打工赚钱攒钱买圣经，6年过后，她积攒下来的钱财终于可以买一本圣经。离家最近卖圣经的地方有42公里远，因为圣经稀奇，有钱不一定买得到。当时没有电话跟卖家确认有货再前往，只能自己去看看才知道有没有卖的。1800年的一个清晨（chen）女孩琼斯从家里出发，跟往常一样光着脚丫，穿过42公里的山地，差不多就是从周浦东到滴水湖的距离。到达目的地后，找到唯一的卖家查尔斯牧师，查尔斯牧师告诉琼斯所有的圣经不是已经卖掉了就是已经预定了。琼斯在那里等待新的货源，2天后她终于买到了自己梦寐以求的圣经。琼斯的事迹感动了查尔斯牧师，在一次会议上，查尔斯牧师讲述了琼斯的故事，参加会议的牧师达成一致，成立圣经公会。他们万众一心，为要使英国和海外地方的信徒都能够以付担得起的价格、拥有一本自己的圣经。我们手上的圣经，价格比同等书籍便宜很多，得益于小女孩琼斯。
*** 真理存在心里的原因
    保罗劝勉提摩太把真道存在心里，这真道是提摩太一直以来都在学习的，小时候跟母亲和外祖母学习，后来再跟保罗学习。而且提摩太确信所学习的真道，没有疑惑。提摩太对真道的信心基于两点，第一是提摩太学习圣经带领人的品格，第二是圣经本身的神圣。保罗把跟谁学的摆在第一位，就是他的母亲和外祖母，再加上保罗自己。提摩太母亲和外祖母有诚实无伪的信心，得到保罗的称（cheng）赞，提后1：5，想到你心里无伪之信，这信是先在你外祖母罗以和你母亲友尼基心里。在保罗的心里，真信心伴随着良好的品（xin）行，表里如一。难能可贵的是，提摩太母亲和外祖母在不长的时间里为提摩太的信仰打下很好的根基。在古罗马，七岁以前的小孩，母亲承担教养的责任，如果是儿子，七岁以后，父亲开始主导儿子的教育。提摩太的父亲不信主，自然不会想到要培养出一个在信徒。所以提摩太接受圣经的教导主要在七岁以前短短几年时间里，由母亲和外祖母主导，可见提摩太母亲和外祖母在他信仰上下的功夫和认真程度。提摩太从外祖母和母亲的对信仰的认真，她们的品行，行事为人的方式中知道她们所传讲是真理，是可靠的。保罗更是用他的生命来证实信仰的真实可靠，作为保罗同工和真儿子的提摩太，能信靠保罗的为人，也能信靠保罗传讲的信仰。

提摩太信心的第二个基础就是圣经。提后3：15 并且知道你是从小明白圣经，这圣经能使你因信基督耶稣有得救的智慧。圣经使人得救的智慧，是借着相信耶稣基督。提摩太小时候学习的圣经主要是旧约圣经，旧约圣经是为耶稣引路的，新约圣经更是直接宣讲耶稣。如果研读圣经，但是不信耶稣基督，仍然不能得救。

在我们的周围也有一些人用他们的生命影响我们，包括带领我们信主的信仰领（ling）路人，还有周围敬虔爱主的弟兄姐妹，这些人用生活中实际的行动把真理的能力表达出来，他们对真理的执着追求和坚信不疑的态度，和因为真理而改变的生命，使我们更加相信真理。

*** 真道的理解，功效。
    真道的两方面的功效
**** 使人因信基督有得救的智慧
借着相信耶稣基督，圣经使人有得救的智慧。保罗写这封信的时候，新约圣经还没有完全成书，所以他指的主要是旧约圣经。旧约圣经里虽然没有明确地提到耶稣，但整本旧约圣经都是为耶稣做见证。主耶稣也亲自证实旧约是为祂作见证，约翰福音5：39，你们查看圣经，因你们以为内中有永生，给我做见证的就是这经。
**** 装备圣徒，预备行各样的善事
     圣经的另一个目的就是装备圣徒。可以用于教训，督责，使人归正，教导人学义。
