做真理的勇士

* 引言

保罗不久就会离开这个世界，留下提摩太。保罗在世的时候，可以指导、提醒、安慰提摩太。当保罗离开世界以后，提摩太就需要彻底独自一人承担教会带领人的重担，成为真理的勇士。作为真理的勇士，要认识末世的人性。
  
* 认识末世的人性
3:1 你该知道，末世必有危险的日子来到
保罗提醒年轻的提摩太末世必有危险的日子，不要期待末世的人会越来越好。末世危险的症结不是环境污染，也不是温室效应，更不是转基因大豆，地沟油，这些只是表象，根源就是保罗下面要讲说的被罪所玷污的人性。保罗在这里提到的罪恶清单，不单针（zhen）对假教师，而是指向末世中所有的人。
我们先看错位的爱。
** 错位的爱 
清单的头一个就是专顾自己，或者说专爱自己，其次是贪爱钱财，最后一个以不爱上帝结束。贪爱钱财的人必定专爱自己，专爱自己的人必定不爱上帝。保罗在提摩太前书中说：“贪财是万恶之根”，但在这个清单里保罗把贪财放在专爱自己的后面，表示贪爱钱财的背后还有更深(shen)一层(ceng)的专爱自己。如果一个人不贪爱钱财，不表明他不专爱自己。专爱自己可以表现在贪爱钱财上，也可以表现在贪爱面子。对有些人来说面子比钱财更有价值。虽然他不爱钱财，但他还是爱自己，因为面子就是他的全部。如果一个人不爱自己，他也不一定就爱上帝，他可能心灰意冷，啥都不爱，就像心理有严重疾病的人，自己都不想活下去。神对被造的人的要求是，尽心，尽性，尽力，尽意爱主你的神。罪的症结就是不爱上帝，就是保罗列在这个清单最后的总结性陈述。

我们仔细看看这些错配的爱
*** 人的爱
**** 专爱自己
     爱自己没错，但只爱自己就是罪了。人总是容易看到对方的问题，善于指出对方的缺点，希望对方改变做事的方式，却因为爱自己就看不到自己的问题。我以前刚信主的时候，当我读到圣经关于怎样做妻子的教导，就特别想我太太好好看看那段经文。每次讲道如果讲到妻子该怎样顺服丈夫，我就在下面焦急，我太太怎么就恰恰在这个时候去主日学，正好错过了这篇讲道呢？接下来就听不进去丈夫该怎么爱妻子的教导。我能清清楚楚地看见太太眼中的刺，却看不见自己眼睛中的木头。我用显微镜看她的问题，却对自己的问题不但近视，而且健忘。如果当时我能够不专爱自己，能用神的话对付自己，我在跟随神的道路。
**** 爱钱财
  钱可以让你开宝马，买别墅，拉鼻子，吃海鲜，国外游。让你可以财富自由，就可以不受老板的气，不用挤公交，爱买啥就买，不皱眉，不眨（zha）眼，不心疼。在法律许可的范围内，即使不道德，只要能赚钱，就放开手脚大干一场，开发让人上瘾的游戏，制造香烟，公司上市圈钱。神对我们的教导是有衣有食就当知足，过一个简朴的生活，同时警告我们贪财是万恶之根。
*** 人的不爱
****  不爱上帝
     不爱上帝是罪的根源所在。上帝创造了你，每天赐给你阳光，雨露、赐给你空气维持生命，赐给你子孙后代，赐给你智慧可以养家糊口。而我们却不认上帝，说这都是靠着我的能力。我们能来到上海，完全是靠自己的努力吗？谋事在人，成事在天。有很多跟你一样努力的人，你成功了，别人失败了，不全是你的功劳。我们能努力，还要有能努力的资本。靠着智力谋生的人，智力起码要正常，如果从小脑萎缩，再怎么努力也没用。靠体力谋生的人，肌肉不能萎缩，不然后天努力也没用。如果到医院看看，在那里躺着的不是你。这些都不是靠着谁的能力或者努力能得到的。我们能谋生，能坐在教会而不是躺在医院，都是神的恩典。我从湖北的一个乡下，能考上大学，妈妈很为我骄傲，我自己也很骄傲。现在回过头来想想，我周围的同年人基本上读完了小学就出去打工，而我的父母支持我读书，如果不是父母支持我不会有今天。我可以说我有个好父母，但是我生来是一个智障的人，我也不会有今天。父母没法保证生下的孩子都是健康的，都是神的恩典。我们生活在和平的年代，生活在中国这片和平的土地而不是朝鲜、伊朗、伊拉克，这个不是靠着人的能力，只能是出于上帝。我们骄傲地说我通过勤奋努力，考上了大学，确实有自己的劳苦，但如果神把你放在一个温饱都难解决的家庭，还能上大学么？上帝给了我们很多，我们却不承认祂，不爱祂。上帝创造了世界，盼望我们能透过世界看到世界背后的上帝，去爱上帝。我们却只爱上帝创造的世界，却不爱创造者上帝。
** 其他的罪
  
 还有很多其他的罪，比如自夸，一种外在的骄傲，狂傲一种心里的骄傲。忘恩负义，心不圣洁等等。我们重点看看违背父母，
*** 违背父母
古罗马的法律、文化赋予父亲在孩子身上绝对的权柄。中国古代也是如此，父为子纲。在古犹太人中，按照旧约，违背父母后果很严重，甚至会被石头砸死。所以古代世界，因为有文化、法律上对父母权威的保障，违反父母是件很不自然的事情，会受到很大的舆论压力，法律制裁。保罗写这封的时候，违背父母的事已经时有发生。因为保罗列出了的这些罪性不单指遥远的未来，而且包括他所在的世代。因为之前主耶稣已经警告过犹太人，他们因着私心用人的遗传废掉了神的诫命，好逃避承担赡养父母的责任，这个也是违背父母表现。
回顾历史，父母在家里的权威持续下降。结果不难想象违背父母在我们这个时代更为突出。十诫中的一诫就是孝敬父母，违背父母直接和这个诫命抵触。我想神把孝敬父母列在十诫之中，其中有一点就是要尊重在地上的父亲母亲，因为神是我们的天父。如果一个人不孝敬、尊重地上的父亲，时常违背父母，敬畏天父基本上就是一句空话。我们当中有很多人不是本地上海人，当我们来到上海，成立新的家庭，面对的一个挑战就是带小孩的问题，谁来带小孩？如果是双职工，很多就让父母来帮忙，如果父母不情愿，就开始有怨言。其实父母的责任是带儿女，而不是带孙子，如果他们愿意带，我们就当感恩，因为带孙子不是父母分内（nei）的责任。如果他们不带，我们也不可以埋怨他们。当周围的朋友都有爸爸妈妈帮忙带孩子时，真的很希望自己的爸爸妈妈也能来带，这个能理解。但无论如何那是他们的自由选择。如果父母选择去你的哥哥家帮忙带孩子，而没有帮你带的时候，更加难受，因为我们觉得不公平，觉得他帮我带孩子是理所当然的。我们嘴里把他们当父母，心里他们当保姆。这是这个时代特别的地方。所以需要靠神的帮助才能让自己的心平静，而不至于在心里犯违背父母的罪。不违背父母，先从感恩开始。对那些觉得父母不公的弟兄姐妹，要从心里认识到父母不欠我们的。

对于做父母的弟兄姐妹,不要纵容孩子违背父母。有的父母很爱孩子，到了一个地步，只要孩子好，自己受点委屈，也心甘情愿。看起来是爱他，其实是害了他，因为你在助（zhu）长他违背父母的罪。求神帮助我们，不要按世界的原则来爱孩子。当你纵容孩子违背父母，其实就是在犯尊重儿女过于尊重神的尊。一旦纵容孩子，孩子就不服权威了，在家里违背父母，在学校不服老师，以后长大了在公司违背上司，带来一连串恶果，最终结果就是不服神。

** 应用
透过这个清单，看见自己的污秽和邪恶。就生出悔改的心，去向我们所得罪的神认罪悔改，真正成为一个蒙恩的罪人。
还没有真正信主的朋友，虽然末世的人性邪恶，但神已经给你开了一条路，就是借着相信为你而死的耶稣，那位为你流血赎罪，上帝独一的儿子，那位死里复活，以后还要来审判死人活人的耶稣，你的罪就被神赦免，不再纪念，脱离地狱的审判。已经信主的弟兄姐妹，神借着祂的话让我们对罪有灵（ling）敏（min）的嗅（xiu）觉，让我们时常反省自己人生的方向，我的生命到底是爱神更多呢？还是爱自己更多？ 
作为真理的勇士，要防备末世的假教师
* 防备末世的假教师
** 假教师
*** 敬虔的外貌
假教师有敬虔的外貌，却没有敬虔的生命。他们是披着羊皮的狼，不但自己走向灭亡，还偷偷的溜进别人的家里，勾引那些无知的人,引诱一些人，迷惑一些人，把人从正道带到岔路上，最终的结果就是一批人跟着假教师一起沉（chen）沦。假教师偷偷摸摸的行为，明显他们不在光明中行，表明所做的不是来自于真理。所以保罗嘱咐提摩太远离他们，把假教师赶出教会，免得刚刚信主的人受到伤害。
*** 抵挡真道
3:8, 从前雅尼和佯庇怎样抵挡摩西，这等人也怎样敌挡真道。圣经在其他的经文里没有提到雅尼和佯庇这两个人。根据传统，他们就是出埃及记中抵挡摩西的埃及术士，也就是行邪术的。他们抵挡摩西，当摩西按照神的旨意行（xing）神（shen）迹的时候，这些人也行出看起来一样的神迹来抵挡神的工作。假教师不但传讲听起来迷惑人的教训，他们甚至还利用来自撒旦的超自然的现象，用神迹奇事来引诱软弱信徒。
*** 他们的结局
    只是作恶的和迷惑人的，必越久越恶，欺哄人也被人欺哄。这些假教师的生命状态螺旋式下降，越来越差，他们用虚假的教义欺骗人，最后也被恶者撒旦利用，被撒旦欺哄。神会拦阻假教师的手，制止他们兴风作浪，把他们的愚昧无知在众人面前显露（lu）出来。就像埃及的术士，他们刚开始的时候用各种邪术抵挡摩西，但最后的时候他们的邪术就失效了，被神制止。
** 受害者 
提后3：6下：这些妇女担负罪恶，被各样的私欲引诱。
假教师的猎物是无知的妇女，她们问题所在就是被自己的私欲诱惑。当时提摩太牧养的以弗所教会有很多妇女，她们普遍没有受到好的教育。现在我们所处的环境，跟以前不一样了，妇女受教育的程度很高，甚至超过男性。但属灵的无知在任何一个时代都很普遍，因为这个世界敌对神，被撒旦弄瞎了眼睛，看不见属灵的事。假教师吞吃的就是这些人，当一个人放纵各种私欲诱惑而不收敛，不警惕的时候，就会恶化到心地刚硬的地步。一旦心地刚硬，再怎么劝解都没有用，只是一意孤行。就像被传销洗脑的人，你告诉他直白，简单的道理，告诉他传销会最终毒害自己，他还是不听，因为发财的梦紧紧地抓住他的心。提后3：7，这些人常常学习，终久不能明白真道。常常学习是一种好的习惯，但如果带着错误的动机，去实现自己的野心，满足自己的私欲，只会离真道越来越远。学习圣经也是这样，如果带着私欲学习圣经，而不是谦卑悔改的心，并不能得救。
** 应用
假教师不仅自己与神为敌，还鼓动其他的人远离神，作为教会的一员，如果发现这种情况，请向牧者报告。

作为真理的勇士，要做末世的真工人
* 做末世的真工人
** 真工人要学会顺服
   3:10 但你已经服从了我的教训、品行、志向、信心、宽容、爱心、忍耐

使徒行传16章记载，路司得和以哥念的弟兄都称赞提摩太。路司得和以哥念两地相距30公里，可见提摩太的影响力不小。一个年轻人受到这么多的赞誉还能顺服保罗。
提摩太与保罗多年同工，跟保罗近距离的接触，使提摩太对保罗有清楚的认识，知道保罗所教训的内容，也知道保罗行事为人的品格。透过保罗的品行，提摩太知道保罗传讲的和行出来的是一致的。知道保罗在基督里所立的志向，就是要传福音，得主的喜悦（林后5：9，所以，无论是住在身内，离开身外，我们立了志向，要得主的喜悦）。知道保罗那不以福音为耻的信心，还有保罗的宽容，爱心，忍耐。 保罗生活的目标、方向都聚焦在福音上。这一切提摩太清楚明白，而且他也顺服保罗，效法保罗。末世的假教师自高自大，任意妄为，但末世的真工人不受周围环境的影响，出污泥而不染，展现出来美好顺服的品质。

** 真工人要忍受苦难
保罗第一次传道的途中路过安提阿，以哥念和路司得，在那里受到了一个又一个，越来越大的逼迫。在这里讲述的逼迫、苦难都记载在使徒行传13~14章。我们简单回顾一下：在彼西底的安提阿保罗，巴拿巴被赶出城外。就前往以哥念，在那里抵挡真道的人要用石头打保罗一行人，但他们毫发无损地逃到路司得。而在路司得，他们用石头打保罗，这次真的被打着了，而且他们以为保罗被打死了，就把保罗拖到城外。
但保罗在逼迫中看到主对他的保守和拯救。保罗说：在这一切的苦难中，主把我救出来。主没有让保罗免（mian）受苦难，而是先允许他经历苦难，然后把他从苦难之中救出来。神不会忘记在苦难中属神百姓，更不会忘记在苦难中神的仆人，不会任由苦难一直持续下去。就像保罗在路司得的时候，徒14:20，门徒正围着他，他就起来，走进城去。众人都以为他死了，但他却能站起来，走进城去。一个被打得快要死的人，就算是逃过一劫，也应该是遍体鳞伤，需要好好休养才能慢慢恢复。但保罗当时自己起来了，这个不能不说是一个神迹。我们在苦难中才会经历神迹，更重要的是在苦难中才能真知神是帮助我们的，才会发自肺腑地说神是帮助我的，神是拯救我的。就像保罗所说，在这一切的苦难中，主把我救出来。

神的百姓中，不仅仅是使徒、先知、教师们要受逼迫。保罗告诉我们所有的信徒都要受逼迫。 提后3:12，不但如此，凡立志在基督耶稣里敬虔度日的，也都要受逼迫。这句话换一个角度说，如果你不受逼迫，就你就没有在基督耶稣里立志敬虔度日。保罗在这里提醒提摩太，对前面的道路要清晰的认识，苦难在前面等待着他，但正是前方的苦难表明他是在基督里敬虔度日的人。当然我们所处的环境中不太可能碰到保罗经历的那种逼迫，我们碰到的逼迫更多来自于心灵和心理层面，逼迫表现出来的方式也不同。我们团契中有位姐妹，信主才2年时间不到，没信主前跟她丈夫闹矛盾，总是她得胜，有时还对他老公动拳头，扔凳子。后来她信主了，跟团契的人谈她的难处，说老公奚落她，老公还怪罪她因为信主的缘故生意不如从前。这位姐妹不信主的时候，逼迫丈夫，信了主后，就被丈夫的逼迫。这是基督徒生命成长的一个过程， 从一个人受逼迫的状况，在逼迫中的心态大概就能看出一个人的信仰程度。每一个对信仰认真负责的人，都应当反思：我为主的缘故受到过逼迫、苦难、嘲笑、歧视、白眼吗？

** 真工人要牢记真道
*** 真理的源头来自于神
圣经大约四十位的作者，66卷书，最早的一卷的写作时间是公元前1500左右，最后一卷是公元后95年左右。他们生活的年代跨越1600年，他们没有见过面，也没有商量过，但却写出主题一致，没有冲突的圣经。是什么力量组织不同的人，在1600的时间里写出一致的内容呢？圣经在历史上受到了很多的攻击。公元303年罗马皇帝戴克里先，下令焚烧所有的圣经。在文革期间，圣经也遭到焚烧。但圣经还是很神奇保存下来了。什么力量保守圣经在几千年的时间里能面对破坏，却能完好地流传下来呢？全世界发行量最大的书籍就是圣经，累计超过100亿本，目前大约每年卖1亿本。没有其他的任何书籍可以和圣经相比。2013年统计全世界共有70亿人，只有3亿五千万的人没有自己的母语圣经，只有不到5%的人没有自己的母语圣经。2016年10月份的统计数据显示，全世界有7097种仍在使用的语言，其中3223种语言已经有翻译好的圣经，另外有2422种语言的圣经正在翻译中。是什么力量把圣经推向全世界，是什么力量把圣经翻译成这么多种的文字呢？我们周围的人把圣经当做一种书而已，但我们信徒要知道圣经的源头就是神。如果圣经不是来自于神，怎么解释这些事实呢？提后3：16，圣经都是神所默示的。这个“都”字表明圣经中所有的句子，所有的字都是神默示的，没有例外。这个当然是指的原文圣经，我们现在手上拿到的和合本圣经是翻译过来的，没有原文圣经那样的权威，但对普通信徒来说已经足够满足属灵生命的需要。神所默示的就是神吹气的意思，可以理解为神说出这些圣经的话语。表面上看圣经是人写的，但本质是人被圣经感动说出神的话来。

*** 真理存在心里的原因
 保罗劝勉提摩太把真道存在心里。提摩太一直以来都在学习真道，小时候跟母亲和外祖母学习，后来再跟保罗学习。而且提摩太确信所学习的真道，没有疑惑。把真道存在心里有两个原因，首先是跟谁学的，其次是圣经本身。保罗把跟谁学的摆在前面，因为带领学习圣经的那个人对信徒的影响巨大。如果你跟着异端学习圣经，最后很有可能你就成为一个异端。如果带领你学圣经的人，对圣经马马虎虎，最后你对圣经也马马虎虎。我知道有个弟兄，不但向自己的同学传福音，把同学带到教会，而且还跟他私下经常在微信上读经打卡。读经打卡表明他对圣经很当真，用实际行动表明圣经很重要，很宝贵。鼓励弟兄姐妹带领人信主的时候，不但能带到教会，还能自己带领他一起学习圣经。带领提摩太学习圣经的是谁呢？就是他的母亲和外祖母。在古罗马，七岁以前的小孩，母亲承担教养的责任，如果是儿子，七岁以后，父亲开始主导儿子的教育。提摩太的父亲不信主，自然不会想到要培养出一个在信徒。所以提摩太接受圣经的教导主要在七岁以前短短几年时间里，由母亲和外祖母主导，可见提摩太母亲和外祖母在他信仰上所下的功夫和认真的程度。提摩太从外祖母和母亲对信仰的认真，她们的品行，行事为人的方式中知道她们所传讲是真理，是可靠的。我想提摩太的外祖母和母亲在生活中经历了一些难处，不然提摩太的母亲，作为一个敬（jing）虔（qian）的人，不会嫁一个不信主的人。但尽管有难处，她们还是结出丰硕的成果，不但自己的名字能记载在圣经上，被神纪念，还培养出敬虔的提摩太，成为带领教会、被神重用的仆人。我们中间的妈妈们，即使家里只有你一人信主，只要你在孩子面前对信仰认真，给孩子树立榜样，一样能结出丰盛的果实。把真道存在心里的第二个原因就是圣经。提后3：15并且知道你是从小明白圣经。提摩太在母亲和外祖母的带领下，以正确的态度、方式学习圣经，明白圣经，知道圣经就是神的话。如果我们以谦卑的态度读圣经，就能知道耶和华是带来安慰平安的神，保守我们灵魂的神，是永远爱我们的神，拯救我们脱离审判的神。

*** 真道在人心里的果效
**** 使人因信基督有得救的智慧
保罗写这封信的时候，新约圣经还没有完全成书，所以他指的主要是旧约圣经。旧约圣经里虽然没有明确地提到耶稣，但整本旧约圣经都是为耶稣做见证。主耶稣也亲自证实旧约是为祂作见证，约翰福音5：39，你们查看圣经，因你们以为内中有永生，给我做见证的就是这经。圣经有它的文学价值，道德高度，但这些不是圣经的目的。圣经的目的就是使人得救。通过圣经，就能更深刻认识自己，明白自己是一个完全的罪人，清楚神的公义，知道罪的后果就是死，晓得神预备了耶稣代替我们流血牺牲。借着相信耶稣基督为我们所做的一切，圣经使人有得救的智慧。研读圣经，如果不信耶稣，仍然不能得救。

**** 装备圣徒预备行各样的善事
     圣经的另一个目的就是装备圣徒。有四个不同的方面：教训，督责，使人归正，教导人学义。教训和督责有关于教义，使人归正和教导人学义有关于行为。圣经不但告诉我们信仰的内容，也告诉我们行动的指南。错误教义下面的好行为会助（zhu）长人的骄傲，错误行为下面的正确教义说明教义只在头脑里，还没有进到心里。圣经从积极的方面来教训、教导人学义。从消极方面督责、使人归正。我们读圣经的时候，神就借着圣经教训我们真实的，责备我们的错失，纠正我们的方向，引导我们行在良善之中。一方面神借着祂的话直接教训，管教，另一方面神也借着弟兄姐妹彼此教训，管教。作为神的真工人，应当按着圣经的教导去教训别人，督责他人，使他人归正，教导他人学义。积极的方面容易做，但消极的方面不容易做，比如使他人归正很少做到。不但怕得罪人，同时尺度难把握，万一力度不当就会伤害人。还担心搞不好对方以后不来教会，这种担心也是合理的，但神不是要我们做好好先生，神要我们顺服他的话去使人归正。如果看到弟兄姐妹的问题，而不指出来，会使他错失成长的机会，导致他一直活在人生的低谷。我认识一位培训主日学老师的老师，或者说，她的学生就是主日学的老师。她的课程对主日学的老师帮助很大。我参加过她的培训，那段时间里，大家一起早上灵修的时候，每个人轮流分享灵修的心得，好多人被她批评责备，因为灵修的内容不够深度。在分享个人难处的时候，如果她听到不合圣经的地方，她也毫不客气，一针见血（xie）地指明问题所在，指出很多自怨自怜的问题，而不是一味地纵容人活在软弱里面。教训，督责，使人归正，教导人学义这四方面都是来自于圣经真理，是被神所使用的方法，全面地使用能祝福到教会。在被弟兄姐妹归正的时候，可能心理上有点难受，而且对方的观点不一定正确，这个时候要我们有特别的宽容和爱心，因为对方也是因着爱心在归正我们。如果面子薄，不想被人纠正，最好的方法就是，(3s),多读圣经，被圣经的话直接归正。
     
* 结论
  末世的人性专爱自己，不爱上帝。提醒我们要省察日常的工作、生活中，到底有多少是为着爱自己，又有多少是为着爱神。神把我们放在这末世，不希望我们随从末世的人性，而是希望我们在这末世之中仍然能爱上帝。末世的假教师放纵私欲，要从无知的人身上骗得地上的好处，神对他的惩罚不会延迟。我们也要谨慎自己，在真理上好好用功，免得自己被假教师欺骗，免得落入神的审判。末世的真工人顺服真道，向生命好的信徒学习，预备为主的缘故受苦，用圣经装备自己，预备行各样的善事。
* 问题
1：分享你曾经教训、督责别人的经历，如果没有，请分享你被圣经，或被人教训、督责的经历。
2: 你是什么时候相信圣经就是神的话的？你用什么方式把圣经存在心里。
