* 引言
  游戏制作人利用人的软弱，沉(chem)溺(li)于游戏的人放纵自己的罪性。

* 末世的人性
末世的日子
保罗提醒提摩太：“你该知道”。
末世的危险，不是外面的压力和逼迫，而是假敬虔。糖衣炮弹的威力胜于大炮的威力。大炮打过来，还是要隐藏避免受害，而在糖衣炮弹面前常常不打仗就投降了。
** 错位的爱 
*** 人的爱
**** 专爱自己
专顾自己，有的版本中是专爱自己。 
保罗把专爱自己列在第一位，其他的一切恶都是从专爱自己中引发出来的。爱自己没有错，也是应当的。如果一个人连自己都不爱，麻烦很大。这种人没有生存的欲望，不关心自己看得见的利益，更别说关系自己看不见的灵魂，是属于不正常的一种人。在座都爱自己灵魂的人，不然不会做在这里。主耶稣来是要拯救我们的灵魂，所以我们需要有一个爱自己灵魂的心，不然就不会接受这个救恩，更不用说珍惜这个救恩了。但过度爱自己，以致专爱自己，就是罪了。

过度爱自己表现在跟人发生冲突的时候，你是否只是想找自己的得失，而没有考虑对方的得失。基督徒容易辨别这钟专爱自己。

另一种表现就有些隐蔽了：那就是一个有意无意的动作，引发周围人的嫉妒或者实落。这种情况没有引发看得见上的冲突。就像保罗说哥林多教会举行爱宴的时候，富足的吃饱了，喝醉了，但是那些贫（pin）穷的却在一旁忍饥挨饿。保罗要求那些富足的人在家里吃了再来教会，免得那些贫穷的人羞愧，实落。

我有次早上上班，下楼梯的时候，看到一个阿姨正在扫楼道，灰尘(chen)满天飞。赶快急急忙忙迈开大步逃走了。后来一想，我这么急急忙忙的逃走了，那个阿姨怎么想？是不是会让她觉得自己的工作下贱呢？我虽然没有和她发生正面冲突，其实心已经开始冲突了，她的心受到了歧视的伤害。如果我实在担心这个灰尘会伤到自己，可以回家吸一口新鲜的空气，再以正常的方式下楼，这样就不会伤害到她了。而且就算吸进几口灰尘，就真的会少活几天么？

**** 爱钱财
爱钱财是爱自己的第一个表现形式。而且爱钱财会被贴上有进取心的标签。天下熙熙皆为利来，天下攘攘皆为利往。普天下的都是为着钱财在忙碌。老祖宗知道爱财的手段不能低劣，君子爱财，取之有道。但到了现今这个时代，爱财的手段有时很恶劣，1998年的山西朔州假酒案，农民王青华用34吨甲醛加水勾兑57.5吨白酒，导致27人丧生，222人中毒，多人失明。在他们心里，能赚到钱才是王道，根本不顾及他人死活。如果说王青华是低劣的爱财手段，甲醛用的剂量太大而直接导致人死亡，眼睛失眠。那么还有很多高级版本，加入少量甲醛，不会要你的命，同时能赚到你的钱，这种例子大概就很多了。10年前的三聚氰胺奶粉，吃了不会马上要人的命，一时半会儿发现不了，这种情况就更要命了。

前一段时间我赶地铁的时候，听见后面一个人开心的说：“没人要我就要了”，我回头一看，是一个从地上捡起来50块钱。他脸上的笑容跟周围其他人脸上的那种沉闷的表情对比很明显。我能猜到他没有捡起这50块钱的时候，他的表情跟周围其他人一样，没有笑容，面无表情。但是50块钱就能改变一个人的心情，改变一个人的表情。当时让我体验了一下钱财的能力。我回头继续往前走，脑海中闪过一个念头：“应该见着有份啊”。当然我没有说出来。我更加体会了钱财的势力。

钱财的魅力实在太大了。有了钱就不会有人瞧不起，

/我们基督徒当怎么面对钱财的？要跳出这个世界的框框。人生如梦，钱财只在你的梦中，在这个世界中发挥它的功效，等主耶稣来了的时候，我们的梦也就醒了，钱财就结束了它的一切功能。这个梦总有梦醒时分，求神赐给我们明亮的眼睛，真知道那在天上的真实，地上的都是影儿。/

**** 爱宴乐
末世的时候美食家多起来。
吃喝是正常的需要。但对吃喝的过度追求就成了爱宴了。对吃喝的追求，在现在的时代表现得极为突出。神给我们这个时代极大的恩典，在上海你能吃到全世界的水果，全世界的特产。
神对我们的要求是有衣有食就当知足。过一个简谱的生活。

爱宴乐。

钱财的魅力，他的美，他的荣耀。
*** 人的不爱
****  不爱良善
****  不爱上帝
** 其他的罪
* 假敬虔
** 假敬虔的特征
*** 易察觉的假敬虔

那偷进人家，牢笼无知妇女的，正式这等人。

保罗那个年代的妇女没有什么地位，常常带在家里。而这些
*** 难察觉的假敬虔（卖主的犹大，爱世界的底马）
    有敬虔的外貌，却背了敬虔的实意。

 假敬虔是一种伪装的敬虔。有的伪装是一种低级的伪装，不用相处很长时间就能分辨出来。有的伪装是高级的伪装，非常难分辨。

 再看看高级伪装。卖主犹大跟随主耶稣3年之久，没人预先能察觉到犹大的敬虔是假的。当然主耶稣是知道的，因为没有任(ren)何事在耶稣面前是隐藏的。主耶稣差遣12使徒两个两个结伴传福音时，犹大也在其中。犹大传过福音，从主耶稣那里得到过权柄(bing)制伏污鬼。从表面上看，其他门徒所作的服侍，犹大照样做，而且他还多了一个管理钱囊的服侍，至少表面上看犹大不比其他的人少服事主。但是在主的晚餐的时候，主耶稣说你们当中有一个人要卖我的时候，门徒们没有一个怀疑是犹大。底马贪爱现今的世界，离开保罗时，保罗才突然发现原来底马也是假敬虔。保罗被囚禁的时候，底马已经开始和保罗同工了。当时的保罗有名气，但没有世上的身份让底马可以沾光，也没有钱财可以分给底马。从人的角度看保罗只有深重的苦难可以分给底马，底马是因为什么原因跟随保罗，值得我们每个跟随主的人思考，免得我们步其后尘。保罗提到底马因为贪爱现今的世界，就背叛了主。底马跟随主的那个世界，和他离开主时的那个世界，我想不会有很大的变化。因为古代的世界不像现在世界变化这么快。我们可以大胆猜测变了的不是底马的世界，而是底马的处境，从而导致他的心发生了变化。



 同样的世界，跟保罗同工的人，公元62年的时候，保罗写歌罗西书和腓力门书，那时保罗还说底马是同工。公元64-65年，保罗写提摩太后书时，此时底马已经原形毕露了

 。一个初级的伪装，生命好的信徒能察觉到，如果有人对他特别有爱心，还有挽回他的机会。高级的伪装，也有两种：一种是自己知道自己在伪装，就像犹大回答主耶稣：“要卖的叛徒的是我们？”，犹大自己清楚地知道他已经计划好要卖主了。还有一种是自己不知道自己在伪装，就像有人对主耶稣说：“我不是奉你的名赶过鬼吗”。只能靠自己省(xing)察内心深处的信仰状况，常常祷告神的恩典托住自己。
 从外表上没法区分真假敬虔，

** 受害者的特征
*** 充满罪恶
*** 常常学习 
**** 学习新奇的观点

以前的妇女受教育程度低，现在的社会男性受教育程度反而更低。
这些妇女负担罪恶，被各样的私欲引诱，常常学习，终久不能明白真道。

这些妇女因为自己从前的罪，特别容易受假教师的主张影响。假教师有两种主张：一种禁(jin)欲主义，鼓吹虚伪的克己（提前4：3）， 另一种是反律法主义，主张各种罪都可以接受（提后3：2-4）
这些被保罗批评的妇女，常常学习。常常学习好不好？好是好。还要看跟谁学，学习什么，怎样学习。这些妇女跟假教师学，被各种稀奇古怪的思想吸引。

但学习的目的是要明白真道，如果不明白正道，学习也没有什么益处。为什么常常学习，终久不能明白真道了？是因为她们承担罪恶，被各样的私欲引诱。学习圣经的目的要是认识神，并借着圣经话语省察自己的心，好在神面前知罪，并悔改。如果带着

圣经是神的话。神邀请我们查考圣经。
约5:39, 主耶稣说：应当查考圣经，因你们以为内中有永生，给我作见证的就是这经。

奇异恩典的作者约翰牛顿晚年的时候得了老年痴呆，但他牢记两件事，他是个大罪人，耶稣基督的恩典拯救了他。读圣经带给约翰牛顿的2个宝贵财富就是，他深知自己是个大罪人，耶稣是他的拯救。

圣经是一座金矿，我们要在里面挖掘自己的罪，和基督的恩典。在圣经里越往深处挖，就越清楚自己的罪，越知道自己是多么地得罪神，也越知道基督恩典的宝贵。如果没有挖到自己的罪和耶稣的恩典，读圣经的方法就不对。
年轻的官，跪着求问耶稣，怎么才能承受永生，他回答耶稣，诫命他都遵守了。表明他不认为犯了任何罪。
而当彼得看到耶稣行神迹的时候，直接承认自己是个罪人。
读经的心态直接关系读经的效果。

**** 不正确地学习圣经
     圣经也会成为你的偶像。
**** 正确地学习圣经
**** 宝贵的圣经
     买圣经的小女孩。

* 敌挡真道者的结局

  
* 末世的人性
* 末世的假教师
** 假教师 v3:13
*** 敬虔的外貌
假教师有敬虔的外貌，却没有敬虔的生命。他们是披着羊皮的狼，所以保罗嘱咐提摩太远离他们。 这些人偷偷的溜进别人的家里，去勾引那些无知的妇女。假教师偷偷摸摸的行动，表明所做的不是来自于真理。
假教师没有敬虔的能力，没有道德的能力。

假教师有敬虔的外貌，表面上看很敬虔，走近了看却没有敬虔的果子。就像主耶稣咒诅的那颗无花果树，远远看去枝繁叶茂，给人带来很大的期待和盼望，走近了却发现没有期望的果子。假教师不在光明中行，而偷偷溜进别人的家，目的是去勾引人。对假教师，提摩太要躲开，也要带带领弟兄姐妹一起躲开。2：13 只是作恶的和迷惑人的，必越久越恶，欺哄人也被人欺哄。这些假教师的状况螺旋下降，越来越恶，他们用虚假的教义欺骗人，最后也那恶者撒旦利用而被欺哄。假教师的猎物是无知的妇女，这些属灵上无知妇女的特征就是被自己的私欲诱惑。当时提摩太牧羊的以弗所有很多妇女，============.拿到今天来说，重点就是那些被私欲引诱的人，不分男女了。我自己就差点儿被诱惑了。大概11年前，那时刚刚接触福音，有人带我去教会，知道一些基督教的教义，比如地狱的存在于可怕，我有一些了解。一次偶然的机会遇到一个耶和华见证人，要跟我一起学习圣经，我就跟他一起学习，他跟我讲没有地狱。慈爱的神怎么容忍地狱的存在呢？还拿出圣经，希腊文字典跟我详细讲解，我一看这个信徒好认真，都拿原文字典学习了，我也没有看到教会的牧师看原文字典啊，所以对他心里满是敬佩。而且那时我很喜欢没有地狱的教义，没有地狱就不需要承担后果了。我心里开始盘算，我跟着学，学好了，能进天堂，得赏赐，那时上上签，要是中途觉得让人不舒服，随时下车，也没有损失，反正人死如灯灭，没有地狱嘛。这个教义能满足我的私欲，让我在放纵私欲的时候可以不考虑后果。但是真敬虔能帮助人遏制私欲，约瑟被波提乏的妻子诱惑的时候，说的是：”我怎能作这大恶，得罪神呢？“，约瑟知道得罪神会有永远审（审）判，下地狱的后果。如果约瑟当时相信耶和华见证人，我想他就无力抵挡这个诱惑了，反正没有地狱吧。
他们是做
*** 抵挡真道
*** 他们的结局
** 受害者 
* 末世的真工人
** 顺服
   3:10 但你已经服从了我的教训、品行、志向、信心、宽容、爱心、忍耐

提摩太与保罗多年同工，跟保罗近距离的接触，使提摩太对保罗有清楚的认识，知道保罗所教训的内容，也知道保罗行事为人的品格。透过保罗的品行，提摩太知道保罗传讲的和行出来的是一致的。知道保罗在基督里所立的志向，就是要传福音，得主的喜悦（林后5：9，所以，无论是住在身内，离开身外，我们立了志向，要得主的喜悦）。知道保罗那不以福音为耻的信心，还有保罗的宽容，爱心，忍耐。 保罗生活的目标、方向都聚焦在福音上。这一切提摩太清楚明白，而且他也顺服保罗，效法保罗。末世的假教师自高自大，任意妄为，但末世的真工人不受周围环境的影响，出污泥而不染，展现出来美好顺服的品质。

** 忍受苦难
保罗第一次传道的途中路过安提阿，以哥念和路司得，在那里受到了一个又一个，越来越大的逼迫。对安提阿稍作解释，圣经提到两个安提阿，一个是宣教大本营的安提阿，位于叙利亚，另一个是这个看到的安提阿，位于彼西底。在这里讲述的逼迫、苦难都记载在使徒行传13~14章。我们简单回顾一下：在彼西底的安提阿保罗，巴拿巴被赶出城外。就前往以哥念，在那里抵挡真道的人要用石头打保罗一行人，但他们毫发无损地逃到路司得。而在路司得，他们用石头打保罗，这次真的被打着了，而且他们以为保罗被打死了，就把保罗拖到城外。

保罗在这个三个城市经历的苦难，逼迫一个比一个重，开始的时候只是赶走而已，后来就有人要用石头打他，虽然有惊无险地逃跑了，并没有受到身体的伤害，但在最后一个地方就不一样了，不但真实地受到了人身攻击，而且都快要死了。但保罗在这些逼迫中也看到主对他的保守和拯救。提后3:11后半节：在这一切的苦难中，主把我救出来。主没有让保罗免（mian）受苦难，而是先允许他经历苦难，然后把他从苦难之中救出来。神不会忘记在苦难中属神百姓，更不会忘记在苦难中神的仆人，不会任由苦难一直持续下去。就像保罗在路司得的时候，徒14:20，门徒正围着他，他就起来，走进城去。众人都以为他死了，但他却能站起来，走进城去。一个被打得快要死的人，就算是逃过一劫，也应该是遍体鳞伤，需要好好休养才能慢慢恢复。而且是被石头打的，受到的伤害肯定不是皮肉之伤，而是伤筋（jin）动骨。我们有个说法是伤筋动骨一百天，但保罗当天起来了，而且经文里没有提到有人扶他起来，也没有人扶他走，可以看到他应该是自己起来，自己走进城的。这个不能不说是一个神迹。我们在苦难中才会经历神迹，更重要的是在苦难中才能真知神是帮助我们的，才会发自肺腑地说神是帮助我的，神是拯救我的。就像保罗所说，在这一切的苦难中，主把我救出来。

保罗提到的这些遭遇提摩太没有亲身经历，但提摩太是路司得人，而且他从小是一个敬虔的人，他不会不关注信仰相关的事情。所以发生在提摩太老家逼迫保罗的暴动，提摩太就算没有亲眼看见也肯定听周围的人讲过，那时的提摩太的很年轻，对比年长的人，逼迫在年轻人心中打下的烙印更深。保罗提醒提摩太，为着信仰的缘故，提摩太心里要有预备，像保罗一样遭受逼迫和苦难。提摩太是一个胆小的人，跟我们中间大部分人一样，但保罗坚固他，告诉他最终主会实行拯救，好帮助提摩太有力量可以承受苦难。

神的百姓中，不仅仅是使徒、先知、教师们要受逼迫。保罗告诉我们所有的信徒都要受逼迫。 提后3:12，不但如此，凡立志在基督耶稣里敬虔度日的，也都要受逼迫。这句话换一个角度说，如果你不受逼迫，就你就没有在基督耶稣里立志敬虔度日。看看保罗的经历，他不认识主之前，是逼迫人的，一旦他信主之后，就开始被逼迫了。保罗在这里提醒提摩太，对前面的道路要清晰的认识，苦难在前面等待着他，但正是前方的苦难表明他是在基督里敬虔度日的人。当然我们所处的环境中不太可能碰到保罗经历的那种逼迫，我们碰到的逼迫更多来自于心灵和心理层面，逼迫表现出来的方式也不同。我们团契中有位姐妹，信主才2年时间不到，没信主前跟她丈夫闹矛盾，总是她得胜，有时还对他老公动拳头，扔凳子。后来她信主了，跟团契的人谈她的难处，说她老公奚落她，还怪罪她因为信主的缘故生意不如从前。这位姐妹不信主的时候，不受逼迫，信了主后，就受到来自不信的丈夫的逼迫。这是基督徒生命成长的一个过程， 从一个人受逼迫的状况，逼迫中的心态大概就能看出一个人的信仰程度。每一个对信仰认真负责的人，都应当反思：我为主的缘故受到过逼迫、苦难吗？

对有心服侍教会的弟兄姐妹，如果想要成为末世的真工人，就更要预备心志，为主的缘故而受苦。
** 把真道存在心里
*** 真理的源头来自于神
圣经都是神所默示的。这个“都”字表明圣经中所有的句子，所有的字都是神默示的。当然这个是指原文圣经，我们手里拿到的和合本圣经是翻译过来的，不具备原文圣经的权威，但和合本对我们普通信徒研读圣经已经足够了。如果你对真理更追求，可以去参考原文圣经。精读圣经这个软件中有个原文菜单，能查到中文圣经所对应的希腊文或希伯来文原文，还有每个原文字词的词典可供参考。神所默示的表明圣经的源头来自于神。来自于神当然很宝贵。18世纪末在英国的威尔士就有个小姑凉非常珍爱圣经。她叫马利琼斯，父亲是虔诚的基督徒，8岁时就相信耶稣，非常渴慕圣经，就定下目标要拥有一本属于自己的圣经。当时的圣经昂贵稀缺，家里又很贫（pin）穷，不得不自己打工赚钱攒钱买圣经，6年过后，她积攒下来的钱财终于可以买一本圣经。离家最近卖圣经的地方有42公里远，因为圣经稀奇，有钱不一定买得到。当时没有电话跟卖家确认有货再前往，只能自己去看看才知道有没有卖的。1800年的一个清晨（chen）女孩琼斯从家里出发，跟往常一样光着脚丫，穿过42公里的山地，差不多就是从周浦东到滴水湖的距离。到达目的地后，找到唯一的卖家查尔斯牧师，查尔斯牧师告诉琼斯所有的圣经不是已经卖掉了就是已经预定了。琼斯在那里等待新的货源，2天后她终于买到了自己梦寐以求的圣经。琼斯的事迹感动了查尔斯牧师，在一次会议上，查尔斯牧师讲述了琼斯的故事，参加会议的牧师达成一致，成立圣经公会。他们万众一心，为要使英国和海外地方的信徒都能够以付担得起的价格、拥有一本自己的圣经。我们手上的圣经，价格比同等书籍便宜很多，得益于小女孩琼斯。
*** 真理存在心里的原因
    保罗劝勉提摩太把真道存在心里，这真道是提摩太一直以来都在学习的，小时候跟母亲和外祖母学习，后来再跟保罗学习。而且提摩太确信所学习的真道，没有疑惑。提摩太对真道的信心基于两点，第一是提摩太学习圣经带领人的品格，第二是圣经本身的神圣。保罗把跟谁学的摆在第一位，就是他的母亲和外祖母，再加上保罗自己。提摩太母亲和外祖母有诚实无伪的信心，得到保罗的称（cheng）赞，提后1：5，想到你心里无伪之信，这信是先在你外祖母罗以和你母亲友尼基心里。在保罗的心里，真信心伴随着良好的品（xin）行，表里如一。难能可贵的是，提摩太母亲和外祖母在不长的时间里为提摩太的信仰打下很好的根基。在古罗马，七岁以前的小孩，母亲承担教养的责任，如果是儿子，七岁以后，父亲开始主导儿子的教育。提摩太的父亲不信主，自然不会想到要培养出一个在信徒。所以提摩太接受圣经的教导主要在七岁以前短短几年时间里，由母亲和外祖母主导，可见提摩太母亲和外祖母在他信仰上下的功夫和认真程度。提摩太从外祖母和母亲的对信仰的认真，她们的品行，行事为人的方式中知道她们所传讲是真理，是可靠的。保罗更是用他的生命来证实信仰的真实可靠，作为保罗同工和真儿子的提摩太，能信靠保罗的为人，也能信靠保罗传讲的信仰。

提摩太信心的第二个基础就是圣经。提后3：15 并且知道你是从小明白圣经，这圣经能使你因信基督耶稣有得救的智慧。圣经使人得救的智慧，是借着相信耶稣基督。提摩太小时候学习的圣经主要是旧约圣经，旧约圣经是为耶稣引路的，新约圣经更是直接宣讲耶稣。如果研读圣经，但是不信耶稣基督，仍然不能得救。

在我们的周围也有一些人用他们的生命影响我们，包括带领我们信主的信仰领（ling）路人，还有周围敬虔爱主的弟兄姐妹，这些人用生活中实际的行动把真理的能力表达出来，他们对真理的执着追求和坚信不疑的态度，和因为真理而改变的生命，使我们更加相信真理。

*** 真道的理解，功效。
    真道的两方面的功效
**** 使人因信基督有得救的智慧
借着相信耶稣基督，圣经使人有得救的智慧。保罗写这封信的时候，新约圣经还没有完全成书，所以他指的主要是旧约圣经。旧约圣经里虽然没有明确地提到耶稣，但整本旧约圣经都是为耶稣做见证。主耶稣也亲自证实旧约是为祂作见证，约翰福音5：39，你们查看圣经，因你们以为内中有永生，给我做见证的就是这经。
**** 装备圣徒，预备行各样的善事
     圣经的另一个目的就是装备圣徒。可以用于教训，督责，使人归正，教导人学义。
