应对末世
* 引言
  游戏制作人利用人的软弱，沉(chem)溺(li)于游戏的人放纵自己的罪性。======有待完善
  有位小学生

有位总是靠第二名的小学生，杀死第一名。他受的教育可以说相当不错，第二名不那么容易考。孩子是以后祖国的花朵，未来的希望，承载着我们的厚望，给予最好的教育，盼望以后一天好过一天。但第二名杀死第一名，告诉我们教育不能改变人，因为人心不是靠世界的教育能改变的。人的石头心靠外面的说教并不能融化他。我们对比看看圣经对末世人性的描述，

  
* 认识末世的人性
  末世的日子
3:1 你该知道，末世必有危险的日子来到
保罗提醒年轻的提摩太末世必有危险的日子，对末世不要抱有幻想，不要期待末世的人会越来越好。保罗对现今的世界持悲观的态度，人性持续堕落。现在的人对这个世界的看法跟保罗很不同，现代人很乐观，全世界的教育水准都在提高，特别是中国，遍地都是大学生。以为教育水平高了，人就会越来越好，世界越来越美。但我们看到的各种新闻报道证实保罗的看法是对的，各种伤天害理的事情变着花样展现在人的眼前，让人惊叹：“怎么会发生这种事”。但如果透过圣经的角度，用保罗的眼光看，你不会惊讶，都是预料之中的事，人性就是这么的恶。大卫在诗篇15篇中说：“我在母腹中就有了罪”，三字经说：”人之初，性本善“。如果用事实说话，圣经是对的。做父母的如果带着客观的态度，就能认同生在罪中的事实，除非带着溺爱的有色眼镜。大家应该还记得5年前李天一轮奸案件，他是著名歌星李双江60岁左右生的，唯一的儿子。李双江说他儿子小时候可爱的像个天使，李双江太太在儿子被抓的时候还说，”李天一本质善良、忠义，也热爱学习“。事实证明他们的看法不客观，是在爱子心切的情况下讲出的不合实际的话。末世危险的症结不是环境污染，也不是温室效应，更不是转基因大豆，地沟油，这些只是表象，根源就是保罗下面要讲说的被罪所玷污的人性。人性就是人里面最深处的东西，看不见摸不着，但它指挥，影响外在行为。保罗在这里提到的罪恶清单，不单针（zhen）对假教师，而是指向末世中所有的人。有人说，“什么恶事我都干过，如果没有干过也曾经说过，如果没有说过，也曾经想过”，用在每个人身上不会太过分。
我们先看错位的爱。
** 错位的爱 
保罗开了一个末世的罪恶清单，清单的头一个就是专顾自己，或者说专爱自己，其次是贪爱钱财，最后一个以不爱上帝结束。贪爱钱财的人必定专爱自己，专爱自己的人必定不爱上帝。保罗在提摩太前书中说：“贪财是万恶之根”，但在这个清单里保罗把贪财放在专爱自己的后面，表示贪爱钱财的背后还有更深(shen)一层(ceng)的专爱自己。如果一个人不贪爱钱财，不表明他不专爱自己。专爱自己可以表现在贪爱钱财上，也可以表现在贪爱面子，贪爱长寿，对有些人来说面子比钱财更有价值。虽然他不爱钱财，但他还是爱自己，因为面子就是他的全部。如果一个人不爱自己，他也不一定就爱上帝，他可能心灰意冷，啥都不爱，就像心理有严重疾病的人，自己都不想活下去。神对被造的人的要求是，尽心，尽性，尽力，尽意爱主你的神。罪的症结就是不爱上帝，就是保罗列在这个清单最后的总结性陈述。

我们仔细看看这些错配的爱
*** 人的爱
**** 专爱自己
     我们要区分专爱自己和爱自己。保罗不反对我们爱自己，其实他也要我们爱自己，他在以弗所书5：33节说：然而你们个人都当爱妻子，如同爱自己一样。这句话隐含着人要爱自己，否则的话，如果他就要像虐（nue）待自己那样虐待妻子了。所以爱自己是好的，但专爱自己就不好了。过度爱自己表现在跟人发生冲突的时候，你是否只是想找自己的损失，而没有考虑对方的损失。基督徒容易辨别这钟专爱自己。还有一种比较隐蔽：那就是一个跟别人没有直接冲突情况下的专爱自己。比如一个有意无意的动作，引发周围人的嫉妒或者失落，使其他的人落在试探之中。就像保罗说哥林多教会举行爱宴的时候，富足的吃饱了，喝醉了，但是那些贫（pin）穷的却在一旁忍饥挨饿。保罗要求那些富足的人在家里吃了再来教会，免得那些贫穷的人羞愧，失落。 人都是习惯专爱自己，因为你要爱其他人的时候，你的视角就要从自己切换到他人了，这个不是人的本性。我有次早上上班，下楼梯的时候，看到一个阿姨正在扫楼道，灰尘(chen)满天飞。赶快急急忙忙迈开大步逃走了。后来一想，我这么急急忙忙的逃走了，那个阿姨怎么想？是不是会让她觉得自己的工作并轻视呢？我虽然没有和她发生直接冲突，但她的心受到了歧视的伤害。如果我实在担心这个灰尘会伤到自己，可以回家吸一口新鲜的空气，再以正常的方式下楼，这样就不会伤害到她了。而且就算吸进几口灰尘，就真的会少活几天么？

**** 爱钱财
爱钱财是爱自己的第一个表现形式。而且爱钱财在这个社会被贴上有进取心的标签。天下熙熙皆为利来，天下攘攘皆为利往。普天下的都是为着钱财在忙碌。老祖宗知道爱财的手段不能低劣，君子爱财，取之有道。但到了现今这个时代，爱财的手段有时很恶劣，1998年的山西朔州假酒案，农民王青华用34吨甲醛加水勾兑57.5吨白酒，导致27人丧生，222人中毒，多人失明。在他们心里，能赚到钱才是王道，根本不顾及他人死活。如果说王青华是低劣的爱财手段，甲醛用的剂量太大而直接导致人死亡，眼睛失眠。那么还有很多高级版本，加入少量甲醛，不会要你的命，同时能赚到你的钱，这种例子大概就很多了。

有些爱财的手段咋一看看不出有啥问题，还觉得很有创意。我想起以前看过一篇文章，大概是讲金点子的，就是这个点子想法很有创意，很值钱，其中一个例子就是某家牙膏生产厂商，为了提高牙膏的的销量，调研用户的使用习惯，发现用户挤牙膏都是随意挤那么一下。调研得到结果，就让人想到金点子了，那就把牙膏的口子开大一点，用户刷牙的时候，就会每次用更多的牙膏，会直接导致牙膏需求增加。我当时看了这个点子后，真的很佩服这些人，只恨自己没有这种能耐。现在用圣经的眼光看问题，就是知道这个不讨神喜欢：这个点子没有带给客户任何好处，还会造成浪费，其实是暗地里偷钱的行为，只是手段比较高明。当我反思过往的经历的时候，神就借着这些事情让我越来越深地知道我是一个罪人，需要被救赎。当你在一个浸（jin）泡一种文化中的时候，你完全被他所塑造，很难看出其中的问题，只有借着神的话才能知道其中的邪恶和败坏。愿神给我们明亮的眼睛，认出看似正常现象中的罪恶本质，好让自己能避开陷阱。

**** 爱宴乐
吃喝是正常的需要，以维持正常的生命状态。传道书2：24说，人莫强于吃喝，且在劳碌中享福，我看这也是出于神的手。正常的吃喝是神所赐的，出于神的手。神给我们这个时代极大的恩典，在上海你能吃到全世界的水果，各个国家的特产。但对吃喝的过度追求就成了爱宴乐。对吃喝的追求，在现在的时代表现得极为突出，心被口味所引导。末世的时候美食家多起来。神对我们的要求是有衣有食就当知足，过一个简朴的生活。在财主和拉撒路的故事中，财主天天奢华宴乐，死了后在阴间受苦，亚伯拉罕对他说：“你该回想你生前享过福，如今你到受苦了”。这个财主受苦也就罢了，再想想生前爱宴乐享过福，就更苦了。

*** 人的不爱
****  不爱良善

****  不爱上帝
     不爱上帝是罪的根源所在。不爱上帝也是人自己欺哄自己的地方，因为他离开了活水的源头，为自己凿出一个破裂不能存水的池子。上帝命令我们爱祂，不是祂需要我们的爱。三位一体的神彼此相爱，彼此交通。没有污秽罪人对祂的爱，神并没有任何损失，因为祂自己是完全的，不需要外来的东西弥补什么。那神为什么命令我们爱祂？因为祂爱我们。约翰派克牧师在这一点上有很好的看见：如果你是一个无私的人，满有爱心的人，当你知道全世界有一个最好的宝藏，你会不会把其他人带到宝藏那里？当然会的，否则你就是因着自己的私心，不愿意跟人分享。神也是这样，因为神就是爱。祂乐意把最好的分享给其他的人。这个世界、宇宙、万有中最好的是什么呢？那就是神自己，因为这个缘故，神愿意把祂自己分享给其他人。而且神做事很彻底，他不但把最好的指给我们，还命令我们到最好的那位那里去，就是到神那里去。如果是人，你把宝藏指给别人就很不错了，至于别人信不信，自己看着办吧。神是怎么做的呢？希伯来1：1说，神既在古时籍着众先知多次多方的晓谕列祖，就在这个末世借着祂儿子晓谕我们。神通过各种方式吸引人归向祂。然而人还是不爱上帝，约翰福音5：40节，耶稣对以色列人说：“然而你们不肯到我这里来得生命”。
** 其他的罪
*** 违背父母
古罗马的法律、文化赋予父亲在孩子身上绝对的权柄。中国古代也是如此，父为子纲。在古犹太人中，按照旧约，违背父母后果很严重，甚至会被石头砸死。所以古代世界，因为有文化、法律上对父母权威的保障，违反父母是件很不自然的事情，会受到很到的舆论压力，法律制裁。保罗写这封的时候，违背父母的事已经时有发生。因为保罗列出了的这些罪性不单指遥远的未来，而且包括他所在的世代。因为之前主耶稣已经警告过犹太人，他们因着私心用人的遗传废掉了神的诫命，好逃避承担赡养父母的责任，这个也是违背父母表现。
回顾历史，父母在家里的权威持续下降。结果不难想象违背父母在我们这个时代更为突出。十诫中的一诫就是孝敬父母，违背父母直接和这个诫命抵触。作为神的百姓，第一要紧的关系是跟神，第二是跟配偶，其次才是父母。但神的诫命十诫中，有的讲到跟神有关系，有的讲到跟父母有关系。但没有一条诫命关系到配偶。可见神很关心我们怎么对待父母。我想神把孝敬父母列在十诫之中，其中有一点就是要尊重在地上的父亲母亲，因为神是我们的天父。如果一个人不孝敬、尊重地上的父亲，时常违背父母，敬畏天父基本上就是一句空话。况且神已经命令我们孝敬父母。这个时代违背父母的例证太多，随手挑一个例子。我们当中有很多人不是本地上海人，当我们来到上海，成立新的家庭，面对的一个挑战就是带小孩的问题，谁来带小孩？如果是双职工，很多就让父母来帮忙，如果父母不情愿，就开始有怨言。其实父母的责任是带儿女，而不是带孙子辈，如果他们愿意带，我们就当感恩，因为带孙子不是父母分内（nei）的责任。如果他们不带，我们也不可以埋怨他们。我们能理解的一点是，当周围的朋友都有爸爸妈妈帮忙带孩子时，真的很希望自己的爸爸妈妈也能来带。但无论如何那是他们的自由选择。如果父母选择去你的哥哥家帮忙带孩子，而没有帮你带的时候，更加难受，因为我们觉得不公平，觉得他帮我带孩子是理所当然的。我们嘴里把他们当父母，心里他们当保姆，这是这个时代特别的。所以需要靠神的帮助才能让自己的心平静，而不至于在心里犯违背父母的罪。不违背父母，先从感恩开始，对那些觉得父母不公的弟兄姐妹，要从心里认识到父母不欠我们的。

对于做父母的弟兄姐妹，对孩子提的要求要合神心意，同时也不要纵容孩子违背父母。有的父母很爱孩子，到了一个地步，只要孩子好，自己受点委屈，也心甘情愿。看起来是爱他，其实是害了他，因为你在助（zhuang）长他违背父母的罪。恳求圣灵光照做父母的，不要按世界的原则来爱孩子。当你纵容孩子违背父母，其实就是在犯尊重儿女过于尊重神的尊。撒母耳记中的祭司以利，弟兄姐妹们知道他的结局，神对以利的审判就是因为儿子的问题。以利劝解哈拿不要醉酒，虽然当时是误会，但以利尽到了劝解百信的责任。以利为哈拿祝福，他尽到了在神面前祝福百姓的责任。还带出来敬虔的撒母耳。撒母耳断奶后跟着以利长大，以利的一言一行对撒母耳，我想他对撒母耳的影响大过任何人。但就是这位以利，被神审判，因为他尊重儿子过于尊重神。尊重儿子过于尊重神常常伴随着孩子违背父母，因为小孩也是罪人，你给他不当有的尊重、纵容时，他的罪就开始膨胀，以致有一天就开始违背父母了。看看以利对儿子的劝诫：“我儿啊，不可这样！我听见你们的风声（sheng）不好，你们使耶和华的百姓（xing）犯了罪，人.....”，他儿子的态度就是置之不理，根本就不听从。

我对我的孩子比较严格，因为我知道纵容她们的后果。我对她们的期待是不要违背我跟他们发出的指令，不是我希望她们被尊敬，被顺服，当然被顺服，被尊敬的感觉很好，感更重要的时，不要让他们因为违背父母而得罪神。当我真的这么做的时候，神真的会很祝福我，前几天我问我家五岁的吴越，你最喜欢爸爸的什么的地方。她先回答，我喜欢你亲我，你抱我。我继续追问，还有其他的吗。她回答，还有就是你打我，因为你打我就是爱我。小孩口里说的就是打，其实就是管教了。她亲口对我说她喜欢我的一点就是我打她。我很受安慰。当我管教孩子不要违背父母是，不仅仅神喜悦，孩子以后也不会凡违背父母的罪，还让孩子喜欢、感谢我，真实一举三得。如果我纵容孩子，神不喜悦，孩子以后违背父母得罪神，他也不会喜欢我，三重恶果
** 应用
如何面对末世的人性？ 我们要明白神的话，因为只有通过神的话才能明白什么是罪，什么是恶。借着神的话照亮自己，看见自己的污秽和邪恶。就生出悔改的心，去向我们所得罪的神认罪，真正成为一个蒙恩的罪人。
还没有真正信主的朋友，虽然末世的人性邪恶，但神已经给你开了一条路，就是借着相信为你而死的耶稣，那位为你流血赎罪，上帝独一的儿子，那位死里复活，以后还要来审判死人活人的耶稣，你的罪就被神赦免，不再纪念，脱离地狱的审判，这是耶稣用祂的血跟你立的约。已经信主的，神给我们的功课是要远离这些恶事，不是靠着来自人意的努力，而是靠着住在我们心里的主，从主来的提醒和帮助。
* 防备末世的假教师
** 假教师 v3:13
*** 敬虔的外貌
假教师有敬虔的外貌，却没有敬虔的生命。他们是披着羊皮的狼，不但自己走向灭亡，还要引诱一些人，迷惑一些人，把人从正道带到岔路上，最终的结果就是一批人跟着假教师一起沉（chen）沦。所以保罗嘱咐提摩太远离他们，把假教师赶出教会，免得神的小羊受到伤害。 假教师偷偷的溜进别人的家里，去勾引那些无知的人。假教师偷偷摸摸的行为，表明所做的不是来自于真理。

假教师远看很敬虔，走近了看却没有敬虔的果子。就像主耶稣咒诅的那颗无花果树，远远看去枝繁叶茂，给人带来很大的期待和盼望，走近了却发现没有期望的果子。假教师不在光明中行，而偷偷溜进别人的家，目的是去勾引人。对假教师，提摩太要躲开，也要带带领弟兄姐妹一起躲开。
*** 抵挡真道
3:8, 从前雅尼和佯庇怎样抵挡摩西，这等人也怎样敌挡真道。圣经在其他的经文里没有提到雅尼和佯庇这两个人。根据传统，他们就是出埃及记中抵挡摩西的埃及术士，也就是行邪术的。他们抵挡摩西，当摩西按照神的旨意行（xing）神（shen）迹的时候，这些人也行出看起来一样的神迹来抵挡神的工作。假教师不但传讲听起来迷惑人的教训，他们甚至还利用来自撒旦的超自然的现象，向信徒证明他们的教训是可靠的。
*** 他们的结局
    只是作恶的和迷惑人的，必越久越恶，欺哄人也被人欺哄。这些假教师的生命状态螺旋式下降，越来越差，他们用虚假的教义欺骗人，最后也被恶者撒旦利用，被撒旦欺哄。神会拦阻假教师的手，制止他们兴风作浪，把他们的愚昧无知在众人面前显露（lu）出来。就像埃及的术士，他们刚开始的时候用各种邪术抵挡摩西，但最后的时候他们的邪术就失效了，被神制止。
** 受害者 
提后3：6下：这些妇女担负罪恶，被各样的私欲引诱。
假教师的猎物是无知的妇女，她们问题所在就是被自己的私欲诱惑。当时提摩太牧养的以弗所教会有很多妇女，她们普遍没有受到好的教育。现在我们所处的环境，跟以前不一样了，妇女受教育的程度很高，甚至超过男性。但属灵的无知在任何一个时代都很普遍，因为这个世界敌对神，被撒旦弄瞎了眼睛，看不见属灵的事。假教师吞吃的就是这些人，当一个人放纵各种私欲诱惑而不收敛，不警惕的时候，就会恶化到心地刚硬的地步。一旦心地刚硬，再怎么劝解都没有用，只是一意孤行。就像被传销洗脑的人，你告诉他直白，简单的道理，告诉他传销会最终毒害自己，他还是不听，因为发财的梦紧紧地抓住他的心。提后3：7，这些人常常学习，终久不能明白真道。常常学习是一种好的习惯，但如果带着错误的动机，去实现自己的野心，满足自己的私欲，只会离真道越来越远。学习圣经也是这样，如果带着私欲学习圣经，而不是谦卑悔改的心，并不能得救。
** 应用
假教师不仅自己与神为敌，还鼓动其他的人远离神，作为教会的一员，如果发现这个情况，请向牧者报告。

* 做末世的真工人
** 真工人要学会顺服
   3:10 但你已经服从了我的教训、品行、志向、信心、宽容、爱心、忍耐

提摩太与保罗多年同工，跟保罗近距离的接触，使提摩太对保罗有清楚的认识，知道保罗所教训的内容，也知道保罗行事为人的品格。透过保罗的品行，提摩太知道保罗传讲的和行出来的是一致的。知道保罗在基督里所立的志向，就是要传福音，得主的喜悦（林后5：9，所以，无论是住在身内，离开身外，我们立了志向，要得主的喜悦）。知道保罗那不以福音为耻的信心，还有保罗的宽容，爱心，忍耐。 保罗生活的目标、方向都聚焦在福音上。这一切提摩太清楚明白，而且他也顺服保罗，效法保罗。末世的假教师自高自大，任意妄为，但末世的真工人不受周围环境的影响，出污泥而不染，展现出来美好顺服的品质。

** 真工人要忍受苦难
保罗第一次传道的途中路过安提阿，以哥念和路司得，在那里受到了一个又一个，越来越大的逼迫。对安提阿稍作解释，圣经提到两个安提阿，一个是宣教大本营的安提阿，位于叙利亚，另一个是这个看到的安提阿，位于彼西底。在这里讲述的逼迫、苦难都记载在使徒行传13~14章。我们简单回顾一下：在彼西底的安提阿保罗，巴拿巴被赶出城外。就前往以哥念，在那里抵挡真道的人要用石头打保罗一行人，但他们毫发无损地逃到路司得。而在路司得，他们用石头打保罗，这次真的被打着了，而且他们以为保罗被打死了，就把保罗拖到城外。

保罗在这个三个城市经历的苦难，逼迫一个比一个重，开始的时候只是赶走而已，后来就有人要用石头打他，虽然有惊无险地逃跑了，并没有受到身体的伤害，但在最后一个地方就不一样了，不但真实地受到了人身攻击，而且都快要死了。但保罗在这些逼迫中也看到主对他的保守和拯救。提后3:11后半节：在这一切的苦难中，主把我救出来。主没有让保罗免（mian）受苦难，而是先允许他经历苦难，然后把他从苦难之中救出来。神不会忘记在苦难中属神百姓，更不会忘记在苦难中神的仆人，不会任由苦难一直持续下去。就像保罗在路司得的时候，徒14:20，门徒正围着他，他就起来，走进城去。众人都以为他死了，但他却能站起来，走进城去。一个被打得快要死的人，就算是逃过一劫，也应该是遍体鳞伤，需要好好休养才能慢慢恢复。而且是被石头打的，受到的伤害肯定不是皮肉之伤，而是伤筋（jin）动骨。我们有个说法是伤筋动骨一百天，但保罗当天起来了，而且经文里没有提到有人扶他起来，也没有人扶他走，可以看到他应该是自己起来，自己走进城的。这个不能不说是一个神迹。我们在苦难中才会经历神迹，更重要的是在苦难中才能真知神是帮助我们的，才会发自肺腑地说神是帮助我的，神是拯救我的。就像保罗所说，在这一切的苦难中，主把我救出来。

保罗提到的这些遭遇提摩太没有亲身经历，但提摩太是路司得人，而且他从小是一个敬虔的人，他不会不关注信仰相关的事情。所以发生在提摩太老家逼迫保罗的暴动，提摩太就算没有亲眼看见也肯定听周围的人讲过，那时的提摩太的很年轻，对比年长的人，逼迫在年轻人心中打下的烙印更深。保罗提醒提摩太，为着信仰的缘故，提摩太心里要有预备，像保罗一样遭受逼迫和苦难。提摩太是一个胆小的人，跟我们中间大部分人一样，但保罗坚固他，告诉他最终主会实行拯救，好帮助提摩太有力量可以承受苦难。

神的百姓中，不仅仅是使徒、先知、教师们要受逼迫。保罗告诉我们所有的信徒都要受逼迫。 提后3:12，不但如此，凡立志在基督耶稣里敬虔度日的，也都要受逼迫。这句话换一个角度说，如果你不受逼迫，就你就没有在基督耶稣里立志敬虔度日。看看保罗的经历，他不认识主之前，是逼迫人的，一旦他信主之后，就开始被逼迫了。保罗在这里提醒提摩太，对前面的道路要清晰的认识，苦难在前面等待着他，但正是前方的苦难表明他是在基督里敬虔度日的人。当然我们所处的环境中不太可能碰到保罗经历的那种逼迫，我们碰到的逼迫更多来自于心灵和心理层面，逼迫表现出来的方式也不同。我们团契中有位姐妹，信主才2年时间不到，没信主前跟她丈夫闹矛盾，总是她得胜，有时还对他老公动拳头，扔凳子。后来她信主了，跟团契的人谈她的难处，说她老公奚落她，还怪罪她因为信主的缘故生意不如从前。这位姐妹不信主的时候，不受逼迫，信了主后，就受到来自不信的丈夫的逼迫。这是基督徒生命成长的一个过程， 从一个人受逼迫的状况，逼迫中的心态大概就能看出一个人的信仰程度。每一个对信仰认真负责的人，都应当反思：我为主的缘故受到过逼迫、苦难吗？

对有心服侍教会的弟兄姐妹，如果想要成为末世的真工人，就更要预备心志，为主的缘故而受苦。
** 真工人要牢记真道
*** 真理的源头来自于神
圣经都是神所默示的。这个“都”字表明圣经中所有的句子，所有的字都是神默示的，没有例外。这个当然是指的原文圣经，我们现在手上拿到的和合本圣经是翻译过来的，没有原文圣经那样的权威，但对普通信徒来说已经足够满足属灵生命的需要。神所默示的就是神吹气的意思，可以理解为神说出这些圣经的话语。表面上看圣经是人写的，但本质是人被圣经感动说出神的话来。

先看看圣经本身的内容。圣经中几百次讲“耶和华如此说”。当先知说“耶和华如此说”的时候，他们就是在宣告，自己就是从神那里来的大使，他们的话就是神自己的话。另外，圣经经常说神籍着先知说话，所以先知奉神的名说话，也就是神说的话。再看看有关圣经的事实。圣经大约四十位的作者，66卷书，最早的一卷的写作时间是公元前1500左右，最后一卷是公元后95年左右。他们生活的年代跨越1600年，他们没有见过面，也没有商量过，但却写出主题一致，没有冲突的圣经。圣经的作者来自犹太民族，比起希腊人和罗马人，犹太人在文学上没有什么大的成就，但就是这样一本来自犹太的书，却能鹤立鸡群。看看关于圣经的数据，全世界发行量最大的书籍就是圣经，累计超过100亿本，目前大约每年卖1亿本。没有其他的任何书籍可以和圣经相比。2013年统计世界有70亿人，只有3亿五千万的人没有自己的母语圣经。2016年10月份的统计数据显示，全世界有7097种仍在使用的语言，其中3223中已经有翻译好的圣经，另外有2422种语言的圣经正在翻译中。如果圣经不是来自于神，怎么解释这些事实呢？是什么力量把圣经推向全世界，是什么力量把圣经翻译成这么多种的文字呢？


*** 真理存在心里的原因

    保罗劝勉提摩太把真道存在心里，这真道是提摩太一直以来都在学习的，小时候跟母亲和外祖母学习，后来再跟保罗学习。而且提摩太确信所学习的真道，没有疑惑。提摩太对真道的信心基于两点，第一是提摩太学习圣经带领人的品格，第二是圣经本身的神圣。保罗把跟谁学的摆在第一位，就是他的母亲和外祖母，再加上保罗自己。提摩太母亲和外祖母有诚实无伪的信心，得到保罗的称（cheng）赞，提后1：5，想到你心里无伪之信，这信是先在你外祖母罗以和你母亲友尼基心里。在保罗的心里，真信心伴随着良好的品（xin）行，表里如一。难能可贵的是，提摩太母亲和外祖母在不长的时间里为提摩太的信仰打下很好的根基。在古罗马，七岁以前的小孩，母亲承担教养的责任，如果是儿子，七岁以后，父亲开始主导儿子的教育。提摩太的父亲不信主，自然不会想到要培养出一个在信徒。所以提摩太接受圣经的教导主要在七岁以前短短几年时间里，由母亲和外祖母主导，可见提摩太母亲和外祖母在他信仰上下的功夫和认真程度。提摩太从外祖母和母亲的对信仰的认真，她们的品行，行事为人的方式中知道她们所传讲是真理，是可靠的。保罗更是用他的生命来证实信仰的真实可靠，作为保罗同工和真儿子的提摩太，能信靠保罗的为人，也能信靠保罗传讲的信仰。

提摩太信心的第二个基础就是圣经。提后3：15 并且知道你是从小明白圣经，这圣经能使你因信基督耶稣有得救的智慧。圣经使人得救的智慧，是借着相信耶稣基督。提摩太小时候学习的圣经主要是旧约圣经，旧约圣经是为耶稣引路的，新约圣经更是直接宣讲耶稣。如果研读圣经，但是不信耶稣基督，仍然不能得救。

在我们的周围也有一些人用他们的生命影响我们，包括带领我们信主的信仰领（ling）路人，还有周围敬虔爱主的弟兄姐妹，这些人用生活中实际的行动把真理的能力表达出来，他们对真理的执着追求和坚信不疑的态度，和因为真理而改变的生命，使我们更加相信真理。

*** 真道的理解以及果效
    真道的两方面的功效
**** 使人因信基督有得救的智慧
借着相信耶稣基督，圣经使人有得救的智慧。保罗写这封信的时候，新约圣经还没有完全成书，所以他指的主要是旧约圣经。旧约圣经里虽然没有明确地提到耶稣，但整本旧约圣经都是为耶稣做见证。主耶稣也亲自证实旧约是为祂作见证，约翰福音5：39，你们查看圣经，因你们以为内中有永生，给我做见证的就是这经。
**** 装备圣徒，预备行各样的善事
     圣经的另一个目的就是装备圣徒。可以用于教训，督责，使人归正，教导人学义。
** 应用
神的真工人更要牢记真道，
* 结论
末世的人性专爱自己，不爱上帝。这提醒我们不要被它们所引诱、所捆绑，要省察自己日常的工作、生活中，到底有多少是为着爱自己，又有多少是为着爱神。神把我们放在这末世，不希望我们跟随着末世的人性，而是希望我们在这末世之中仍然能爱上帝。末世的假教师放纵私欲，要从无知的人身上骗得地上的好处，神对他的惩罚不会延迟。我们也要谨慎自己，在真理上好好用功，免得自己被假教师欺骗，免得落入神的审判。末世的真工人顺服真道，向生命好的信徒学习，预备为主的缘故受苦，用圣经装备自己，预备行各样的善事。
