* 引言
  游戏制作人利用人的软弱，沉(chem)溺(li)于游戏的人放纵自己的罪性。

* 末世的人性
末世的日子
保罗提醒提摩太：“你该知道”。
末世的危险，不是外面的压力和逼迫，而是假敬虔。糖衣炮弹的威力胜于大炮的威力。大炮打过来，还是要隐藏避免受害，而在糖衣炮弹面前常常不打仗就投降了。
** 错位的爱 
*** 人的爱
**** 专爱自己
专顾自己，有的版本中是专爱自己。 
保罗把专爱自己列在第一位，其他的一切恶都是从专爱自己中引发出来的。爱自己没有错，也是应当的。如果一个人连自己都不爱，麻烦很大。这种人没有生存的欲望，不关心自己看得见的利益，更别说关系自己看不见的灵魂，是属于不正常的一种人。在座都爱自己灵魂的人，不然不会做在这里。主耶稣来是要拯救我们的灵魂，所以我们需要有一个爱自己灵魂的心，不然就不会接受这个救恩，更不用说珍惜这个救恩了。但过度爱自己，以致专爱自己，就是罪了。

过度爱自己表现在跟人发生冲突的时候，你是否只是想找自己的得失，而没有考虑对方的得失。基督徒容易辨别这钟专爱自己。

另一种表现就有些隐蔽了：那就是一个有意无意的动作，引发周围人的嫉妒或者实落。这种情况没有引发看得见上的冲突。就像保罗说哥林多教会举行爱宴的时候，富足的吃饱了，喝醉了，但是那些贫（pin）穷的却在一旁忍饥挨饿。保罗要求那些富足的人在家里吃了再来教会，免得那些贫穷的人羞愧，实落。

我有次早上上班，下楼梯的时候，看到一个阿姨正在扫楼道，灰尘(chen)满天飞。赶快急急忙忙迈开大步逃走了。后来一想，我这么急急忙忙的逃走了，那个阿姨怎么想？是不是会让她觉得自己的工作下贱呢？我虽然没有和她发生正面冲突，其实心已经开始冲突了，她的心受到了歧视的伤害。如果我实在担心这个灰尘会伤到自己，可以回家吸一口新鲜的空气，再以正常的方式下楼，这样就不会伤害到她了。而且就算吸进几口灰尘，就真的会少活几天么？

**** 爱钱财
爱钱财是爱自己的第一个表现形式。而且爱钱财会被贴上有进取心的标签。天下熙熙皆为利来，天下攘攘皆为利往。普天下的都是为着钱财在忙碌。老祖宗知道爱财的手段不能低劣，君子爱财，取之有道。但到了现今这个时代，爱财的手段有时很恶劣，1998年的山西朔州假酒案，农民王青华用34吨甲醛加水勾兑57.5吨白酒，导致27人丧生，222人中毒，多人失明。在他们心里，能赚到钱才是王道，根本不顾及他人死活。如果说王青华是低劣的爱财手段，甲醛用的剂量太大而直接导致人死亡，眼睛失眠。那么还有很多高级版本，加入少量甲醛，不会要你的命，同时能赚到你的钱，这种例子大概就很多了。10年前的三聚氰胺奶粉，吃了不会马上要人的命，一时半会儿发现不了，这种情况就更要命了。

前一段时间我赶地铁的时候，听见后面一个人开心的说：“没人要我就要了”，我回头一看，是一个从地上捡起来50块钱。他脸上的笑容跟周围其他人脸上的那种沉闷的表情对比很明显。我能猜到他没有捡起这50块钱的时候，他的表情跟周围其他人一样，没有笑容，面无表情。但是50块钱就能改变一个人的心情，改变一个人的表情。当时让我体验了一下钱财的能力。我回头继续往前走，脑海中闪过一个念头：“应该见着有份啊”。当然我没有说出来。我更加体会了钱财的势力。

钱财的魅力实在太大了。有了钱就不会有人瞧不起，

/我们基督徒当怎么面对钱财的？要跳出这个世界的框框。人生如梦，钱财只在你的梦中，在这个世界中发挥它的功效，等主耶稣来了的时候，我们的梦也就醒了，钱财就结束了它的一切功能。这个梦总有梦醒时分，求神赐给我们明亮的眼睛，真知道那在天上的真实，地上的都是影儿。/

**** 爱宴乐
末世的时候美食家多起来。
吃喝是正常的需要。但对吃喝的过度追求就成了爱宴了。对吃喝的追求，在现在的时代表现得极为突出。神给我们这个时代极大的恩典，在上海你能吃到全世界的水果，全世界的特产。
神对我们的要求是有衣有食就当知足。过一个简谱的生活。

爱宴乐。

钱财的魅力，他的美，他的荣耀。
*** 人的不爱
****  不爱良善
****  不爱上帝
** 其他的罪
* 假敬虔
** 假敬虔的特征
*** 易察觉的假敬虔

那偷进人家，牢笼无知妇女的，正式这等人。

保罗那个年代的妇女没有什么地位，常常带在家里。而这些
*** 难察觉的假敬虔（卖主的犹大，爱世界的底马）
    有敬虔的外貌，却背了敬虔的实意。

 假敬虔是一种伪装的敬虔。有的伪装是一种低级的伪装，不用相处很长时间就能分辨出来。有的伪装是高级的伪装，非常难分辨。

 再看看高级伪装。卖主犹大跟随主耶稣3年之久，没人预先能察觉到犹大的敬虔是假的。当然主耶稣是知道的，因为没有任(ren)何事在耶稣面前是隐藏的。主耶稣差遣12使徒两个两个结伴传福音时，犹大也在其中。犹大传过福音，从主耶稣那里得到过权柄(bing)制伏污鬼。从表面上看，其他门徒所作的服侍，犹大照样做，而且他还多了一个管理钱囊的服侍，至少表面上看犹大不比其他的人少服事主。但是在主的晚餐的时候，主耶稣说你们当中有一个人要卖我的时候，门徒们没有一个怀疑是犹大。底马贪爱现今的世界，离开保罗时，保罗才突然发现原来底马也是假敬虔。保罗被囚禁的时候，底马已经开始和保罗同工了。当时的保罗有名气，但没有世上的身份让底马可以沾光，也没有钱财可以分给底马。从人的角度看保罗只有深重的苦难可以分给底马，底马是因为什么原因跟随保罗，值得我们每个跟随主的人思考，免得我们步其后尘。保罗提到底马因为贪爱现今的世界，就背叛了主。底马跟随主的那个世界，和他离开主时的那个世界，我想不会有很大的变化。因为古代的世界不像现在世界变化这么快。我们可以大胆猜测变了的不是底马的世界，而是底马的处境，从而导致他的心发生了变化。



 同样的世界，跟保罗同工的人，公元62年的时候，保罗写歌罗西书和腓力门书，那时保罗还说底马是同工。公元64-65年，保罗写提摩太后书时，此时底马已经原形毕露了

 。一个初级的伪装，生命好的信徒能察觉到，如果有人对他特别有爱心，还有挽回他的机会。高级的伪装，也有两种：一种是自己知道自己在伪装，就像犹大回答主耶稣：“要卖的叛徒的是我们？”，犹大自己清楚地知道他已经计划好要卖主了。还有一种是自己不知道自己在伪装，就像有人对主耶稣说：“我不是奉你的名赶过鬼吗”。只能靠自己省(xing)察内心深处的信仰状况，常常祷告神的恩典托住自己。
 从外表上没法区分真假敬虔，

** 受害者的特征
*** 充满罪恶
*** 常常学习 
**** 学习新奇的观点

以前的妇女受教育程度低，现在的社会男性受教育程度反而更低。
这些妇女负担罪恶，被各样的私欲引诱，常常学习，终久不能明白真道。

这些妇女因为自己从前的罪，特别容易受假教师的主张影响。假教师有两种主张：一种禁(jin)欲主义，鼓吹虚伪的克己（提前4：3）， 另一种是反律法主义，主张各种罪都可以接受（提后3：2-4）
这些被保罗批评的妇女，常常学习。常常学习好不好？好是好。还要看跟谁学，学习什么，怎样学习。这些妇女跟假教师学，被各种稀奇古怪的思想吸引。

但学习的目的是要明白真道，如果不明白正道，学习也没有什么益处。为什么常常学习，终久不能明白真道了？是因为她们承担罪恶，被各样的私欲引诱。学习圣经的目的要是认识神，并借着圣经话语省察自己的心，好在神面前知罪，并悔改。如果带着

圣经是神的话。神邀请我们查考圣经。
约5:39, 主耶稣说：应当查考圣经，因你们以为内中有永生，给我作见证的就是这经。

奇异恩典的作者约翰牛顿晚年的时候得了老年痴呆，但他牢记两件事，他是个大罪人，耶稣基督的恩典拯救了他。读圣经带给约翰牛顿的2个宝贵财富就是，他深知自己是个大罪人，耶稣是他的拯救。

圣经是一座金矿，我们要在里面挖掘自己的罪，和基督的恩典。在圣经里越往深处挖，就越清楚自己的罪，越知道自己是多么地得罪神，也越知道基督恩典的宝贵。如果没有挖到自己的罪和耶稣的恩典，读圣经的方法就不对。
年轻的官，跪着求问耶稣，怎么才能承受永生，他回答耶稣，诫命他都遵守了。表明他不认为犯了任何罪。
而当彼得看到耶稣行神迹的时候，直接承认自己是个罪人。
读经的心态直接关系读经的效果。

**** 不正确地学习圣经
     圣经也会成为你的偶像。
**** 正确地学习圣经
**** 宝贵的圣经
     买圣经的小女孩。

* 敌挡真道者的结局

  
* 末世的人性
* 末世的假教师
** 假教师 v3:13
*** 敬虔的外貌
*** 抵挡真道
*** 他们的结局
** 受害者 
* 末世的真工人
** 顺服
** 忍受苦难
** 把真道存在心里
*** 什么是真道 
*** 怎么存
*** 真道的理解，功效。
